### ISSUE TITLE
'Problem' object has no attribute '_compute_once_is_mixed_integer'

### ISSUE THREAD

**Issue by MicahMungal** [cvxgrp/cvxpy#1001]
I am trying to solve the Unit Commitment Problem (Mixed Integer Quadratic Programming problem) using the CVXPY framework for modelling the problem and CPLEX for solving the problem.  

When I run my code I get an
AttributeError: 'Problem' object has no attribute '_compute_once_is_mixed_integer'

And this is the error I get:

Traceback (most recent call last):
  File "C:\Users\micah\AppData\Local\Programs\Python\Python37\lib\site-packages\cvxpy\utilities\performance_utils.py", line 41, in _compute_once
    return getattr(self, attr_name)
AttributeError: 'Problem' object has no attribute '_compute_once_is_mixed_integer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\micah\AppData\Local\Programs\Python\Python37\lib\site-packages\cvxpy\utilities\performance_utils.py", line 41, in _compute_once
    return getattr(self, attr_name)
AttributeError: 'Problem' object has no attribute '_compute_once_variables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/micah/PycharmProjects/test/MIQP", line 114, in <module>
    problem.solve(solver=cp.CPLEX)
  File "C:\Users\micah\AppData\Local\Programs\Python\Python37\lib\site-packages\cvxpy\problems\problem.py", line 290, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\Users\micah\AppData\Local\Programs\Python\Python37\lib\site-packages\cvxpy\problems\problem.py", line 568, in _solve
    self._construct_chains(solver=solver, gp=gp)
  File "C:\Users\micah\AppData\Local\Programs\Python\Python37\lib\site-packages\cvxpy\problems\problem.py", line 511, in _construct_chains
    raise e
  File "C:\Users\micah\AppData\Local\Programs\Python\Python37\lib\site-packages\cvxpy\problems\problem.py", line 497, in _construct_chains
    gp=gp)
  File "C:\Users\micah\AppData\Local\Programs\Python\Python37\lib\site-packages\cvxpy\problems\problem.py", line 456, in _find_candidate_solvers
    if self.is_mixed_integer():
  File "C:\Users\micah\AppData\Local\Programs\Python\Python37\lib\site-packages\cvxpy\utilities\performance_utils.py", line 43, in _compute_once
    setattr(self, attr_name, func(self))
  File "C:\Users\micah\AppData\Local\Programs\Python\Python37\lib\site-packages\cvxpy\problems\problem.py", line 169, in is_mixed_integer
    for v in self.variables())
  File "C:\Users\micah\AppData\Local\Programs\Python\Python37\lib\site-packages\cvxpy\utilities\performance_utils.py", line 43, in _compute_once
    setattr(self, attr_name, func(self))
  File "C:\Users\micah\AppData\Local\Programs\Python\Python37\lib\site-packages\cvxpy\problems\problem.py", line 182, in variables
    vars_ += constr.variables()
AttributeError: 'numpy.bool_' object has no attribute 'variables'

**Comment by rileyjmurray** [comment]
What version of cvxpy are you using?

Separately: the error
```
File "C:\Users\micah\AppData\Local\Programs\Python\Python37\lib\site-packages\cvxpy\problems\problem.py", line 182, in variables
vars += constr.variables()
AttributeError: 'numpy.bool' object has no attribute 'variables'
```
 suggests that some constraint ``constr`` was posed as something like ``a <= b`` or ``a == b`` where neither ``a`` nor ``b`` are cvxpy Expressions. Can you (1) rename your variable ``constr`` to ``constrs``, just to remove confusion there, and (2) iterate over ``con in constrs`` in check that each is a cvxpy Expression?

**Comment by MicahMungal** [comment]
> What version of cvxpy are you using?
 I am using version 1.0.31.

Thanks for the suggestions. I will try them out.
