### ISSUE TITLE
`indicator` transform not working as expected

### ISSUE THREAD

**Issue by gindij** [cvxgrp/cvxpy#1005]
I'm trying to run the following code to solve a relatively simple linear program:   

```python
q = np.random.randint(1, 10, size=n)
a = np.ones((m, n))
b = np.ones((m, 1))
x = cp.Variable((n, 1), name='x')
constraints = [a @ x == b]
objective = cp.Minimize((1/2) * q.T @ x + cp.transforms.indicator(constraints))
problem = cp.Problem(objective, constraints)
solution = problem.solve()
```

When I run, I see the following error message:

```
Traceback (most recent call last):
  File "/Users/gindij/Documents/projects/experiments/proj/venv/lib/python3.7/site-packages/cvxpy/utilities/performance_utils.py", line 41, in _compute_once
    return getattr(self, attr_name)
AttributeError: 'Problem' object has no attribute '_compute_once_is_dcp'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/gindij/Documents/projects/experiments/proj/venv/lib/python3.7/site-packages/cvxpy/utilities/performance_utils.py", line 41, in _compute_once
    return getattr(self, attr_name)
AttributeError: 'AddExpression' object has no attribute '_compute_once_is_convex'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/gindij/Documents/projects/experiments/proj/venv/lib/python3.7/site-packages/cvxpy/expressions/expression.py", line 169, in is_affine
    return self.__is_affine
AttributeError: 'indicator' object has no attribute '_Expression__is_affine'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/gindij/Documents/projects/experiments/proj/venv/lib/python3.7/site-packages/cvxpy/expressions/expression.py", line 159, in is_constant
    return self.__is_constant
AttributeError: 'indicator' object has no attribute '_Expression__is_constant'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/gindij/Documents/projects/experiments/proj/cvx/examples.py", line 137, in <module>
    pprint.pprint(bug(2, 2))
  File "/Users/gindij/Documents/projects/experiments/proj/cvx/examples.py", line 90, in bug
    return solve(objective, constraints)
  File "/Users/gindij/Documents/projects/experiments/proj/cvx/examples.py", line 14, in solve
    solution = problem.solve()
  File "/Users/gindij/Documents/projects/experiments/proj/venv/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 290, in solve
    return solve_func(self, *args, **kwargs)
  File "/Users/gindij/Documents/projects/experiments/proj/venv/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 568, in _solve
    self._construct_chains(solver=solver, gp=gp)
  File "/Users/gindij/Documents/projects/experiments/proj/venv/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 511, in _construct_chains
    raise e
  File "/Users/gindij/Documents/projects/experiments/proj/venv/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 500, in _construct_chains
    construct_intermediate_chain(self, candidate_solvers, gp=gp)
  File "/Users/gindij/Documents/projects/experiments/proj/venv/lib/python3.7/site-packages/cvxpy/reductions/solvers/intermediate_chain.py", line 88, in construct_intermediate_chain
    if not gp and not problem.is_dcp():
  File "/Users/gindij/Documents/projects/experiments/proj/venv/lib/python3.7/site-packages/cvxpy/utilities/performance_utils.py", line 43, in _compute_once
    setattr(self, attr_name, func(self))
  File "/Users/gindij/Documents/projects/experiments/proj/venv/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 138, in is_dcp
    expr.is_dcp() for expr in self.constraints + [self.objective])
  File "/Users/gindij/Documents/projects/experiments/proj/venv/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 138, in <genexpr>
    expr.is_dcp() for expr in self.constraints + [self.objective])
  File "/Users/gindij/Documents/projects/experiments/proj/venv/lib/python3.7/site-packages/cvxpy/problems/objective.py", line 147, in is_dcp
    return self.args[0].is_convex()
  File "/Users/gindij/Documents/projects/experiments/proj/venv/lib/python3.7/site-packages/cvxpy/utilities/performance_utils.py", line 43, in _compute_once
    setattr(self, attr_name, func(self))
  File "/Users/gindij/Documents/projects/experiments/proj/venv/lib/python3.7/site-packages/cvxpy/atoms/atom.py", line 172, in is_convex
    if not (arg.is_affine() or
  File "/Users/gindij/Documents/projects/experiments/proj/venv/lib/python3.7/site-packages/cvxpy/expressions/expression.py", line 171, in is_affine
    self.__is_affine = self.is_constant() or (
  File "/Users/gindij/Documents/projects/experiments/proj/venv/lib/python3.7/site-packages/cvxpy/expressions/expression.py", line 162, in is_constant
    arg.is_constant() for arg in self.args)
  File "/Users/gindij/Documents/projects/experiments/proj/venv/lib/python3.7/site-packages/cvxpy/expressions/expression.py", line 162, in <genexpr>
    arg.is_constant() for arg in self.args)
AttributeError: 'Equality' object has no attribute 'is_constant'
```

I'm using cvxpy 1.0.31.

**Comment by SteveDiamond** [comment]
Thanks @gindij for posting this! I've fixed the bug on master.
