### ISSUE TITLE
nosetests failed: cannot import name 'logsumexp'

### ISSUE THREAD

**Issue by MegicLF** [cvxgrp/cvxpy#1056]
Hello, I got the following error message when trying the nosetests:

```

(base) C:\Users\Linghui>pip install cvxpy
Requirement already satisfied: cvxpy in c:\users\linghui\anaconda3\lib\site-packages (0.4.10)
Requirement already satisfied: ecos>=2 in c:\users\linghui\anaconda3\lib\site-packages (from cvxpy) (2.0.7.post1)
Requirement already satisfied: scs>=1.1.3 in c:\users\linghui\anaconda3\lib\site-packages\scs-1.2.6-py3.6-win-amd64.egg (from cvxpy) (1.2.6)
Requirement already satisfied: multiprocess in c:\users\linghui\anaconda3\lib\site-packages\multiprocess-0.70.4-py3.6-win-amd64.egg (from cvxpy) (0.70.4)
Requirement already satisfied: fastcache in c:\users\linghui\anaconda3\lib\site-packages (from cvxpy) (1.0.2)
Requirement already satisfied: six in c:\users\linghui\anaconda3\lib\site-packages (from cvxpy) (1.15.0)
Requirement already satisfied: toolz in c:\users\linghui\anaconda3\lib\site-packages (from cvxpy) (0.9.0)
Requirement already satisfied: numpy>=1.9 in c:\users\linghui\anaconda3\lib\site-packages (from cvxpy) (1.18.1)
Requirement already satisfied: scipy>=0.15 in c:\users\linghui\anaconda3\lib\site-packages (from cvxpy) (1.4.1)
Requirement already satisfied: CVXcanon>=0.0.22 in c:\users\linghui\anaconda3\lib\site-packages\cvxcanon-0.1.1-py3.6-win-amd64.egg (from cvxpy) (0.1.1)
Requirement already satisfied: dill>=0.2.5 in c:\users\linghui\anaconda3\lib\site-packages (from multiprocess->cvxpy) (0.3.1.1)

(base) C:\Users\Linghui>pip install nose
Requirement already satisfied: nose in c:\users\linghui\anaconda3\lib\site-packages (1.3.7)

(base) C:\Users\Linghui>nosetests cvxpy
E
======================================================================
ERROR: Failure: ImportError (cannot import name 'logsumexp')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Linghui\Anaconda3\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Users\Linghui\Anaconda3\lib\site-packages\nose\loader.py", line 406, in loadTestsFromName
    module = resolve_name(addr.module)
  File "C:\Users\Linghui\Anaconda3\lib\site-packages\nose\util.py", line 312, in resolve_name
    module = __import__('.'.join(parts_copy))
  File "C:\Users\Linghui\Anaconda3\lib\site-packages\cvxpy\__init__.py", line 18, in <module>
    from cvxpy.atoms import *
  File "C:\Users\Linghui\Anaconda3\lib\site-packages\cvxpy\atoms\__init__.py", line 25, in <module>
    from cvxpy.atoms.log_sum_exp import log_sum_exp
  File "C:\Users\Linghui\Anaconda3\lib\site-packages\cvxpy\atoms\log_sum_exp.py", line 22, in <module>
    from scipy.misc import logsumexp
ImportError: cannot import name 'logsumexp'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)


```

Any ideas will be appreciated! Thanks!

**Comment by SteveDiamond** [comment]
Try installing from conda (``conda install -c conda-forge cvxpy``).
