### ISSUE TITLE
KeyError: 'eq_dual'

### ISSUE THREAD

**Issue by boiro9** [cvxgrp/cvxpy#1088]
I am implementing the ADMM algorithm solving each of the subproblems using CVXPY. At one iteration of the algorithm, for one of the subproblems, I obtained the following error:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition with Anaconda plugin 2020.1.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition with Anaconda plugin 2020.1.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Angel/Documents/Git repositories/CBEpy/CBEpy/De-Centralized_AND_RealTime_v.3.py", line 257, in <module>
    result = prob.solve(solver=cp.GUROBI)
  File "C:\Users\Angel\anaconda3\envs\CBE\lib\site-packages\cvxpy\problems\problem.py", line 290, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\Users\Angel\anaconda3\envs\CBE\lib\site-packages\cvxpy\problems\problem.py", line 575, in _solve
    self.unpack_results(solution, full_chain, inverse_data)
  File "C:\Users\Angel\anaconda3\envs\CBE\lib\site-packages\cvxpy\problems\problem.py", line 714, in unpack_results
    solution = chain.invert(solution, inverse_data)
  File "C:\Users\Angel\anaconda3\envs\CBE\lib\site-packages\cvxpy\reductions\chain.py", line 73, in invert
    solution = r.invert(solution, inv)
  File "C:\Users\Angel\anaconda3\envs\CBE\lib\site-packages\cvxpy\reductions\solvers\conic_solvers\gurobi_conif.py", line 106, in invert
    solution['eq_dual'],
KeyError: 'eq_dual'

I have checked gurobi_conif.py under debbuging and it seems that gurobi returns the status as optimal but the dictionary solution in this case does not contain the key "eq_dual". Follow it is a picture:
![error](https://user-images.githubusercontent.com/12407309/88056105-50232180-cb60-11ea-90e0-05913b2d80c0.JPG)

I do not understand what is the problem in this case, it seems that gurobi it is not able to provide dual information although it returns optimal status. I would really appreciate help to manage this issue.

**Comment by SteveDiamond** [comment]
Do you have the latest cvxpy?

**Comment by SteveDiamond** [comment]
If you're not sure if you have the latest cvxpy, try this tool: https://github.com/cvxgrp/cvxpyanalyzer
