### ISSUE TITLE
Problem.solve() gives ValueError with constraints (Cannot reduce problem to symbolic QP)

### ISSUE THREAD

**Issue by Dradeliomecus** [cvxgrp/cvxpy#1115]
I have the following code:

```
import numpy as np
import cvxpy as cvx
 

A0 = np.array([0+1j, 2-1j])
A1 = np.array([[2, -1+1j], [4-3j, -3+2j]])
Z = cvx.Variable(complex = True)
X = cvx.Variable(2)
B = np.array([2+1j, -2j])

objective = cvx.Minimize(cvx.sum_squares(A0*Z + A1@X - B))
prob = cvx.Problem(objective, constraints)
prob.solve()
>>> 1.083377539867636e-41

print(Z.value)
>>> (-0.5000000000000001-0.4999999999999998j)
print(X.value)
>>> array([1.5, 1.5])
```

As you can see it works perfectly fine and as expected.

However, if I put constraints on `X`:
```
constraints = [X >= 0]
prob = cvx.Problem(objective, constraints)
prob.solve()
```

I get the following:
```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    prob.solve()
  File "/users/nsr/wyngaard/miniconda3/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 396, in solve
    return solve_func(self, *args, **kwargs)
  File "/users/nsr/wyngaard/miniconda3/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 745, in _solve
    solver, gp, enforce_dpp)
  File "/users/nsr/wyngaard/miniconda3/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 525, in get_problem_data
    data, inverse_data = solving_chain.apply(self)
  File "/users/nsr/wyngaard/miniconda3/lib/python3.7/site-packages/cvxpy/reductions/chain.py", line 71, in apply
    problem, inv = r.apply(problem)
  File "/users/nsr/wyngaard/miniconda3/lib/python3.7/site-packages/cvxpy/reductions/qp2quad_form/qp2symbolic_qp.py", line 59, in apply
    raise ValueError("Cannot reduce problem to symbolic QP")
ValueError: Cannot reduce problem to symbolic QP
```

I would expect `constraints` to work, as both values for X are greater than 0 in the solution.

I am using Ubuntu 18.04 LTS, with CVXPY 1.1.4 on Python 3.7.4.

**Comment by kevkevinpal** [comment]
Strange I seem to be struggling to reproduce this issue when I add the constraint and then solve I don't receive an error. Is anyone else able to reproduce?

**Comment by Dradeliomecus** [comment]
I tried using python 3.6.9 from a non-miniconda version (still with CVXPY 1.1.4), and I still have the error.

Here is the complete code and error:
```
import numpy as np
import cvxpy as cvx
 

A0 = np.array([0+1j, 2-1j])
A1 = np.array([[2, -1+1j], [4-3j, -3+2j]])
Z = cvx.Variable(complex = True)
X = cvx.Variable(2)
B = np.array([2+1j, -2j])

objective = cvx.Minimize(cvx.sum_squares(A0*Z + A1@X - B))
prob = cvx.Problem(objective)
prob.solve()

print(Z.value)
print(X.value)


constraints = [X >= 0]
prob = cvx.Problem(objective, constraints)
prob.solve()
```

Output:
```
(-0.5000000000000001-0.4999999999999998j)
[1.5 1.5]
Traceback (most recent call last):
  File "test_128_0.1_p1/test.py", line 21, in <module>
    prob.solve()
  File "/users/nsr/wyngaard/.local/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 396, in solve
    return solve_func(self, *args, **kwargs)
  File "/users/nsr/wyngaard/.local/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 745, in _solve
    solver, gp, enforce_dpp)
  File "/users/nsr/wyngaard/.local/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 525, in get_problem_data
    data, inverse_data = solving_chain.apply(self)
  File "/users/nsr/wyngaard/.local/lib/python3.6/site-packages/cvxpy/reductions/chain.py", line 71, in apply
    problem, inv = r.apply(problem)
  File "/users/nsr/wyngaard/.local/lib/python3.6/site-packages/cvxpy/reductions/qp2quad_form/qp2symbolic_qp.py", line 59, in apply
    raise ValueError("Cannot reduce problem to symbolic QP")
ValueError: Cannot reduce problem to symbolic QP
```
