### ISSUE TITLE
negative row index in QP solver

### ISSUE THREAD

**Issue by Albert65** [cvxgrp/cvxpy#1135]
**Describe the bug**
Solver failed to initialize the problem for the reason of negative row indices.
I checked the indices myself (at coeff_extractor.py:269), they are really negative,
some have values around ~ -1e9.
My matrices are big (require 64-bit indices), but very sparse. 
Is that a sign of int32 index overflow somewhere?
I also noticed that (rows, cols) are float64 arrays rather than int64.

**To Reproduce**
A standard quadratic program.
I can upload a pickle file with all involved entities therein (very large ~7.5G),
say on Google Drive, if that works.

x = cvxpy.Variable(size)
    prob = cvxpy.Problem(
        cvxpy.Minimize((1 / 2) * cvxpy.quad_form(x, P) + q.T @ x),
        [G @ x <= h,
         A @ x == b])
    prob.solve()

**Expected behavior**
Input matrices P, G, A are very big and sparse, csr_matrix type.
All the matrices were created without issues.

**Output**
Traceback (most recent call last):
...................
    prob.solve()
  File "/Users/albert/miniconda3/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 396, in solve
    return solve_func(self, *args, **kwargs)
  File "/Users/albert/miniconda3/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 745, in _solve
    solver, gp, enforce_dpp)
  File "/Users/albert/miniconda3/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 525, in get_problem_data
    data, inverse_data = solving_chain.apply(self)
  File "/Users/albert/miniconda3/lib/python3.7/site-packages/cvxpy/reductions/chain.py", line 71, in apply
    problem, inv = r.apply(problem)
  File "/Users/albert/miniconda3/lib/python3.7/site-packages/cvxpy/reductions/qp2quad_form/qp_matrix_stuffing.py", line 263, in apply
    problem, extractor)
  File "/Users/albert/miniconda3/lib/python3.7/site-packages/cvxpy/reductions/qp2quad_form/qp_matrix_stuffing.py", line 247, in stuffed_objective
    params_to_P, params_to_q = extractor.quad_form(expr)
  File "/Users/albert/miniconda3/lib/python3.7/site-packages/cvxpy/utilities/coeff_extractor.py", line 269, in quad_form
    P = sp.coo_matrix((vals, (rows, cols)), shape=(acc_height, num_params))
  File "/Users/albert/miniconda3/lib/python3.7/site-packages/scipy/sparse/coo.py", line 196, in __init__
    self._check()
  File "/Users/albert/miniconda3/lib/python3.7/site-packages/scipy/sparse/coo.py", line 287, in _check
    raise ValueError('negative row index found')
ValueError: negative row index found
ERROR: negative row index found

**Version**
 - OS: MacOS and RedHat Linux 
 - CVXPY Version: Anaconda, v 1.1.5

**Additional context**

**Comment by SteveDiamond** [comment]
Could you post the google drive file? We'd like to get to the bottom of this issue.

**Comment by Albert65** [comment]
Hi Steve, here you go:
https://drive.google.com/file/d/1nzzpJ_Xp92F7UQnjJBZF8Oc5qhgb_8n6/view?usp=sharing

I used the following code to pickle everything:
```
with open("/tmp/qp.pkl", "wb") as f:
        pickle.dump((P, q, G, h, A, b), f)
```
and un-pickle:
```
with open("/tmp/qp.pkl", "rb") as f:
        P, q, G, h, A, b = pickle.load(f)
```
and run the code:
```
size = 1229600
x = cvxpy.Variable(size)
prob = cvxpy.Problem(cvxpy.Minimize((1 / 2) * cvxpy.quad_form(x, P) + q.T @ x),
        [G @ x <= h,
        A @ x == b])
prob.solve()
```
Note, P, G, A have scipy csr_matrix type, and q, b, h are np.ndarrays.

**Comment by SteveDiamond** [comment]
I got this working on master, in the sense that it reaches the solver without error. But it fails in the solver. For such an immense problem that's already in standard form you should probably call OSQP directly: https://osqp.org/

**Comment by Albert65** [comment]
Thank you for clarification and suggestion.
Could you add checking in the code: assert nnz <= np.iinfo(np.int32).max  ?
