### ISSUE TITLE
'import cvxpy': AttributeError: 'module' object has no attribute 'utilities'

### ISSUE THREAD

**Issue by steve3141** [cvxgrp/cvxpy#115]
I see this same error in current builds at: https://readthedocs.org/builds/cvxpy/1471353/

I've downloaded the latest master from github but still have this error. 

It appears to be related to circular imports.

>>> import cvxpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "U:\python\lib\python\cvxpy-0.2.1-py2.7.egg\cvxpy\__init__.py", line 20, in <module>
    from atoms import *
  File "U:\python\lib\python\cvxpy-0.2.1-py2.7.egg\cvxpy\atoms\__init__.py", line 20, in <module>
    from geo_mean import geo_mean
  File "U:\python\lib\python\cvxpy-0.2.1-py2.7.egg\cvxpy\atoms\geo_mean.py", line 20, in <module>
    import cvxpy.utilities as u
AttributeError: 'module' object has no attribute 'utilities'
>>>

**Comment by polostan** [comment]
Hello steve 3141 !
I am facing with the same problem currently but it has not gone away like you. Did you have a solution ? Because even if you explained why is there a problem, i don't know what i must do to fix it.
Thank you for your help.

**Comment by JohnRobson** [comment]
Same Problem:

File "/usr/lib/python3.5/site-packages/cvxpy/constraints/bool_constr.py", line 23, in <module>
    import cvxpy.utilities.performance_utils as pu

AttributeError: module 'cvxpy.utilities' has no attribute 'performance_utils'
