### ISSUE TITLE
Unclear exception

### ISSUE THREAD

**Issue by adishavit** [cvxgrp/cvxpy#1176]
I'm getting this error with Gurobi: **`AttributeError: Unable to retrieve attribute 'X'`**  

The full stack:
```
Traceback (most recent call last):
  File "C:\Users\Public\Miniconda3\envs\...\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-948b20075a95>", line 1, in <module>
    prob.solve(solver=solver, verbose=0, TimeLimit=time_limit)
  File "C:\Users\Public\Miniconda3\envs\...\lib\site-packages\cvxpy\problems\problem.py", line 396, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\Users\Public\Miniconda3\envs\...\lib\site-packages\cvxpy\problems\problem.py", line 754, in _solve
    self.unpack_results(solution, solving_chain, inverse_data)
  File "C:\Users\Public\Miniconda3\envs\...\lib\site-packages\cvxpy\problems\problem.py", line 1058, in unpack_results
    solution = chain.invert(solution, inverse_data)
  File "C:\Users\Public\Miniconda3\envs\...\lib\site-packages\cvxpy\reductions\chain.py", line 79, in invert
    solution = r.invert(solution, inv)
  File "C:\Users\Public\Miniconda3\envs\...\lib\site-packages\cvxpy\reductions\solvers\qp_solvers\gurobi_qpif.py", line 67, in invert
    x = np.array([x_grb[i].X for i in range(n)])
  File "C:\Users\Public\Miniconda3\envs\...\lib\site-packages\cvxpy\reductions\solvers\qp_solvers\gurobi_qpif.py", line 67, in <listcomp>
    x = np.array([x_grb[i].X for i in range(n)])
  File "var.pxi", line 91, in gurobipy.Var.__getattr__
  File "var.pxi", line 119, in gurobipy.Var.getAttr
  File "attrutil.pxi", line 100, in gurobipy.__getattr
AttributeError: Unable to retrieve attribute 'X'
```
The problem solves fine or returns infeasible with slightly different constraints/constants.  
What does this mean?

Versions:
```
cvxopt                    1.2.5                    pypi_0    pypi
cvxpy                     1.1.7            py37h1834ac0_0    conda-forge
cvxpy-base                1.1.7            py37h414f9d2_0    conda-forge
gurobi                    9.0.3                    py37_0    gurobi
```

**Comment by SteveDiamond** [comment]
Maybe the problem is infeasible or unbounded, and that's generating an error? We would need a code snippet that reproduces the bug to say more.

**Comment by adishavit** [comment]
The model I have is very large and the error somewhat sporadic. Using
verbose output, we think this happens when the time limit is hit while the
internal search had only found infeasible solutions by that time.
When given more time, a solution is found and returned.

**Comment by SteveDiamond** [comment]
Got it, it might be easier for you to fix this then, and make a PR? As you can see the key file is "gurobi_qpif.py". Happy to help if you have any questions.

**Comment by yaara-shoval** [comment]
I debugged the error, the problem is in the file gurobi_qpif.py in lines 65-67:
```
if (status in s.SOLUTION_PRESENT) or (model.solCount > 0):
    opt_val = model.objVal + inverse_data[s.OFFSET]
    x = np.array([x_grb[i].X for i in range(n)])
```
It looks like if opt_val  is _inf_ then an error is thrown when trying to access attribute X of x_grb[i].
I'm not sure what is the best way to fix this.

**Comment by SteveDiamond** [comment]
Hmm it should not be giving USER_LIMIT here. Why don't you add the following at line 64 
```
if status == s.USER_LIMIT and model.solCount == 0:
   status = s.SOLVER_ERROR
```
