### ISSUE TITLE
quad_form.grad generate error message

### ISSUE THREAD

**Issue by kch382001** [cvxgrp/cvxpy#1260]
**Describe the bug**
If you have a constraint that uses quad_form.  After successfully calling the prob.solve().  
If you try to access this constraint 'expr.grad', it will generate exception. 
The problem is  in **quad_form._grad** implemention. P is created as an numpy array and it does not have .H property. 
```
    def _grad(self, values):
        x = np.array(values[0])
        P = np.array(values[1])
        D = (P + P.H) @ x.T
        return [sp.csc_matrix(D.ravel(order='F')).T]
```

**To Reproduce**
The following codes can reproduce the problem: 
```
import cvxpy as cp
import numpy as np

m = 15
n = 10
p = 5
np.random.seed(1)
P = np.random.randn(n, n)
P = P.T @ P
q = np.random.randn(n)
s = np.random.randn(n)

# define the optimization problem with the 2nd constraint as a quad_form constraint
x = cp.Variable(n)
prob = cp.Problem(cp.Maximize(q.T @ x - (1/2)*cp.quad_form(x, P)),
                 [cp.norm(x, 1) <= 1.0,
                  cp.quad_form(x, P) <= 10,   # quad form constraint
                  cp.abs(x) <= 0.01
                  ])
prob.solve()

# access quad_form.expr.grad
a = prob.constraints[1].expr.grad`
```
**Expected behavior**
The expected result should be a matrix of quad_form gradient.  However the code throw out an exception. 

**Output**
```
Traceback (most recent call last):
  File "/XXXX/pycharm-community-2020.3.3/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/XXXX/anaconda3/envs/app/lib/python3.6/site-packages/cvxpy/atoms/atom.py", line 399, in grad
    grad_arg = arg.grad
  File "/XXXX/anaconda3/envs/app/lib/python3.6/site-packages/cvxpy/atoms/atom.py", line 393, in grad
    grad_self = self._grad(arg_values)
  File "/XXXX/envs/app/lib/python3.6/site-packages/cvxpy/atoms/quad_form.py", line 112, in _grad
    D = (P + P.H) @ x.T
AttributeError: 'numpy.ndarray' object has no attribute 'H'
```

**Version**
 - OS:  Linux
 - CVXPY Version:  1.1.7

**Comment by SteveDiamond** [comment]
Fixed on master.

**Comment by SteveDiamond** [comment]
Thanks for letting us know about this issue!
