### ISSUE TITLE
Bug: AttributeError: module '_cvxcore' has no attribute 'ConstLinOpVector_swiginit'

### ISSUE THREAD

**Issue by r-barnes** [cvxgrp/cvxpy#1286]
**Describe the bug**
I am trying to run `problem.solve("XPRESS")` and seeing

> AttributeError: module '_cvxcore' has no attribute 'ConstLinOpVector_swiginit'

I do not have other versions of cvxpy on my system.

**To Reproduce**
I'm unable to reproduce this outside of a proprietary environment, sadly.

**Expected behavior**
I expected the problem to solve.

**Output**
```
Traceback (most recent call last):
  File "my_program.py", line 394, in my_function
    optval: float = problem.solve(solver="XPRESS")
  File "cvxpy/problems/problem.py", line 436, in solve
    return solve_func(self, *args, **kwargs)
  File "cvxpy/problems/problem.py", line 918, in _solve
    data, solving_chain, inverse_data = self.get_problem_data(
  File "cvxpy/problems/problem.py", line 591, in get_problem_data
    data, inverse_data = solving_chain.apply(self, verbose)
  File "cvxpy/reductions/chain.py", line 76, in apply
    problem, inv = r.apply(problem)
  File "cvxpy/reductions/qp2quad_form/qp_matrix_stuffing.py", line 262, in apply
    params_to_P, params_to_q, flattened_variable = self.stuffed_objective(
  File "cvxpy/reductions/qp2quad_form/qp_matrix_stuffing.py", line 247, in stuffed_objective
    params_to_P, params_to_q = extractor.quad_form(expr)
  File "cvxpy/utilities/coeff_extractor.py", line 195, in quad_form
    coeffs, constant = self.extract_quadratic_coeffs(root.args[0],
  File "cvxpy/utilities/coeff_extractor.py", line 106, in extract_quadratic_coeffs
    param_coeffs = canonInterface.get_problem_matrix(op_list,
  File "cvxpy/cvxcore/python/canonInterface.py", line 295, in get_problem_matrix
    lin_vec = cvxcore.ConstLinOpVector()
  File "cvxpy/cvxcore/python/cvxcore.py", line 971, in __init__
    _cvxcore.ConstLinOpVector_swiginit(self, _cvxcore.new_ConstLinOpVector(*args))
AttributeError: module '_cvxcore' has no attribute 'ConstLinOpVector_swiginit'
```

**Version**
 - OS: Linux
 - CVXPY Version: 1.1.11

**Additional context**
It's kind of a complex build environment; any assistance or pointers to resources would be appreciated.

**Comment by r-barnes** [comment]
I do see a large number of other things in `_cvxcore`, just nothing like `_swiginit`:
```
ConstLinOpVector___bool__
ConstLinOpVector___delitem__
ConstLinOpVector___delslice__
ConstLinOpVector___getitem__
ConstLinOpVector___getslice__
ConstLinOpVector___len__
ConstLinOpVector___nonzero__
ConstLinOpVector___setitem__
ConstLinOpVector___setslice__
ConstLinOpVector_append
ConstLinOpVector_assign
ConstLinOpVector_back
ConstLinOpVector_begin
ConstLinOpVector_capacity
ConstLinOpVector_clear
ConstLinOpVector_empty
ConstLinOpVector_end
ConstLinOpVector_erase
ConstLinOpVector_front
ConstLinOpVector_get_allocator
ConstLinOpVector_insert
ConstLinOpVector_iterator
ConstLinOpVector_pop
ConstLinOpVector_pop_back
ConstLinOpVector_push_back
ConstLinOpVector_rbegin
ConstLinOpVector_rend
ConstLinOpVector_reserve
ConstLinOpVector_resize
ConstLinOpVector_size
ConstLinOpVector_swap
ConstLinOpVector_swigregister
DENSE_CONST
DIAG_MAT
DIAG_VEC
DIV
DoubleVector2D___bool__
DoubleVector2D___delitem__
DoubleVector2D___delslice__
DoubleVector2D___getitem__
DoubleVector2D___getslice__
DoubleVector2D___len__
DoubleVector2D___nonzero__
DoubleVector2D___setitem__
DoubleVector2D___setslice__
DoubleVector2D_append
DoubleVector2D_assign
DoubleVector2D_back
DoubleVector2D_begin
DoubleVector2D_capacity
DoubleVector2D_clear
DoubleVector2D_empty
DoubleVector2D_end
DoubleVector2D_erase
DoubleVector2D_front
DoubleVector2D_get_allocator
DoubleVector2D_insert
DoubleVector2D_iterator
DoubleVector2D_pop
DoubleVector2D_pop_back
DoubleVector2D_push_back
DoubleVector2D_rbegin
DoubleVector2D_rend
DoubleVector2D_reserve
DoubleVector2D_resize
DoubleVector2D_size
DoubleVector2D_swap
DoubleVector2D_swigregister
DoubleVector___bool__
DoubleVector___delitem__
DoubleVector___delslice__
DoubleVector___getitem__
DoubleVector___getslice__
DoubleVector___len__
DoubleVector___nonzero__
DoubleVector___setitem__
DoubleVector___setslice__
DoubleVector_append
DoubleVector_assign
DoubleVector_back
DoubleVector_begin
DoubleVector_capacity
DoubleVector_clear
DoubleVector_empty
DoubleVector_end
DoubleVector_erase
DoubleVector_front
DoubleVector_get_allocator
DoubleVector_insert
DoubleVector_iterator
DoubleVector_pop
DoubleVector_pop_back
DoubleVector_push_back
DoubleVector_rbegin
DoubleVector_rend
DoubleVector_reserve
DoubleVector_resize
DoubleVector_size
DoubleVector_swap
DoubleVector_swigregister
HSTACK
INDEX
IntIntMap___bool__
IntIntMap___contains__
IntIntMap___delitem__
IntIntMap___getitem__
IntIntMap___len__
IntIntMap___nonzero__
IntIntMap___setitem__
IntIntMap_asdict
IntIntMap_begin
IntIntMap_clear
IntIntMap_count
IntIntMap_empty
IntIntMap_end
IntIntMap_erase
IntIntMap_find
IntIntMap_get_allocator
IntIntMap_has_key
IntIntMap_items
IntIntMap_iterator
IntIntMap_key_iterator
IntIntMap_keys
IntIntMap_lower_bound
IntIntMap_rbegin
IntIntMap_rend
IntIntMap_size
IntIntMap_swap
IntIntMap_swigregister
IntIntMap_upper_bound
IntIntMap_value_iterator
IntIntMap_values
IntVector2D___bool__
IntVector2D___delitem__
IntVector2D___delslice__
IntVector2D___getitem__
IntVector2D___getslice__
IntVector2D___len__
IntVector2D___nonzero__
IntVector2D___setitem__
IntVector2D___setslice__
IntVector2D_append
IntVector2D_assign
IntVector2D_back
IntVector2D_begin
IntVector2D_capacity
IntVector2D_clear
IntVector2D_empty
IntVector2D_end
IntVector2D_erase
IntVector2D_front
IntVector2D_get_allocator
IntVector2D_insert
IntVector2D_iterator
IntVector2D_pop
IntVector2D_pop_back
IntVector2D_push_back
IntVector2D_rbegin
IntVector2D_rend
IntVector2D_reserve
IntVector2D_resize
IntVector2D_size
IntVector2D_swap
IntVector2D_swigregister
IntVector___bool__
IntVector___delitem__
IntVector___delslice__
IntVector___getitem__
IntVector___getslice__
IntVector___len__
IntVector___nonzero__
IntVector___setitem__
IntVector___setslice__
IntVector_append
IntVector_assign
IntVector_back
IntVector_begin
IntVector_capacity
IntVector_clear
IntVector_empty
IntVector_end
IntVector_erase
IntVector_front
IntVector_get_allocator
IntVector_insert
IntVector_iterator
IntVector_pop
IntVector_pop_back
IntVector_push_back
IntVector_rbegin
IntVector_rend
IntVector_reserve
IntVector_resize
IntVector_size
IntVector_swap
IntVector_swigregister
KRON
LinOpVector___bool__
LinOpVector___delitem__
LinOpVector___delslice__
LinOpVector___getitem__
LinOpVector___getslice__
LinOpVector___len__
LinOpVector___nonzero__
LinOpVector___setitem__
LinOpVector___setslice__
LinOpVector_append
LinOpVector_assign
LinOpVector_back
LinOpVector_begin
LinOpVector_capacity
LinOpVector_clear
LinOpVector_empty
LinOpVector_end
LinOpVector_erase
LinOpVector_front
LinOpVector_get_allocator
LinOpVector_insert
LinOpVector_iterator
LinOpVector_pop
LinOpVector_pop_back
LinOpVector_push_back
LinOpVector_rbegin
LinOpVector_rend
LinOpVector_reserve
LinOpVector_resize
LinOpVector_size
LinOpVector_swap
LinOpVector_swigregister
LinOp_get_args
LinOp_get_data_ndim
LinOp_get_dense_data
LinOp_get_linOp_data
LinOp_get_shape
LinOp_get_slice
LinOp_get_sparse_data
LinOp_get_type
LinOp_has_numerical_data
LinOp_is_constant
LinOp_is_sparse
LinOp_push_back_slice_vec
LinOp_set_data_ndim
LinOp_set_dense_data
LinOp_set_linOp_data
LinOp_set_sparse_data
LinOp_swigregister
MUL
MUL_ELEM
NEG
NO_OP
PARAM
PROMOTE
ProblemData_TensorI_get
ProblemData_TensorI_set
ProblemData_TensorJ_get
ProblemData_TensorJ_set
ProblemData_TensorV_get
ProblemData_TensorV_set
ProblemData_getI
ProblemData_getJ
ProblemData_getLen
ProblemData_getV
ProblemData_init_id
ProblemData_param_id_get
ProblemData_param_id_set
ProblemData_swigregister
ProblemData_vec_idx_get
ProblemData_vec_idx_set
RESHAPE
RMUL
SCALAR_CONST
SPARSE_CONST
SUM
SUM_ENTRIES
SWIG_PyInstanceMethod_New
SwigPyIterator___add__
SwigPyIterator___eq__
SwigPyIterator___iadd__
SwigPyIterator___isub__
SwigPyIterator___ne__
SwigPyIterator___next__
SwigPyIterator___sub__
SwigPyIterator_advance
SwigPyIterator_copy
SwigPyIterator_decr
SwigPyIterator_distance
SwigPyIterator_equal
SwigPyIterator_incr
SwigPyIterator_next
SwigPyIterator_previous
SwigPyIterator_swigregister
SwigPyIterator_value
TRACE
TRANSPOSE
UPPER_TRI
VARIABLE
VSTACK
__doc__
__file__
__loader__
__name__
__package__
__spec__
acc_tensor
build_matrix
cvar
delete_ConstLinOpVector
delete_DoubleVector
delete_DoubleVector2D
delete_IntIntMap
delete_IntVector
delete_IntVector2D
delete_LinOp
delete_LinOpVector
delete_ProblemData
delete_SwigPyIterator
diagonalize
new_ConstLinOpVector
new_DoubleVector
new_DoubleVector2D
new_IntIntMap
new_IntVector
new_IntVector2D
new_LinOp
new_LinOpVector
new_ProblemData
tensor_mul
vecprod
vecprod_before
```

**Comment by r-barnes** [comment]
Okay, I think I've solved this. I'd been trying to compile the SWIG interface myself, but it turns out that a pre-made interface is in `cvxcore_wrap.cpp`, so you can just compile everything as a Python extension.
