### ISSUE TITLE
XPRESS solver doesn't work

### ISSUE THREAD

**Issue by r-barnes** [cvxgrp/cvxpy#1287]
**Describe the bug**
When I try to run the simple program below I get the error message:

> TypeError: cannot unpack non-iterable NoneType object

**To Reproduce**
I use [this](https://www.cvxpy.org/examples/basic/least_squares.html) cvxpy example modified to use XPRESS.
```
import cvxpy as cp
import numpy as np

# Generate data.
m = 20
n = 15
np.random.seed(1)
A = np.random.randn(m, n)
b = np.random.randn(m)

# Define and solve the CVXPY problem.
x = cp.Variable(n)
cost = cp.sum_squares(A @ x - b)
prob = cp.Problem(cp.Minimize(cost))
prob.solve("XPRESS")

# Print result.
print("\nThe optimal value is", prob.value)
print("The optimal x is")
print(x.value)
print("The norm of the residual is ", cp.norm(A @ x - b, p=2).value)
```

**Expected behavior**
I expected the program to run without problems.

**Output**
```
Traceback (most recent call last):
  File "bob.py", line 15, in <module>
    prob.solve("XPRESS")
  File "/home/rick/.local/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 290, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/rick/.local/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 569, in _solve
    data, solving_inverse_data = self._solving_chain.apply(
  File "/home/rick/.local/lib/python3.8/site-packages/cvxpy/reductions/chain.py", line 65, in apply
    problem, inv = r.apply(problem)
TypeError: cannot unpack non-iterable NoneType object
```

**Version**
 - OS: Ubuntu 20.04.02
 - CVXPY Version: 1.0.31

**Additional context**

**Comment by r-barnes** [comment]
The XPRESS interface is broken in this version of CVXPY; it is known to work in 1.1.11. Therefore, upgrading fixed this problem.
