### ISSUE TITLE
On Queuing Design Example - solve()

### ISSUE THREAD

**Issue by Hadi2525** [cvxgrp/cvxpy#1336]
I am trying to run the `queuing design` example from the documentation website and the repository: 

https://github.com/cvxgrp/cvxpy/blob/master/doc/source/examples/index.rst

Running on GoogleColab with the .ipynb file leads to the following error:
```
DGPError                                  Traceback (most recent call last)
<ipython-input-1-bec48a1b9f33> in <module>()
     32 
     33 problem = cp.Problem(cp.Minimize(objective_fn), constraints)
---> 34 problem.solve(requires_grad=True, gp=True, eps=1e-14, max_iters=10000, mode='dense')

4 frames
/usr/local/lib/python3.7/dist-packages/cvxpy/reductions/solvers/intermediate_chain.py in construct_intermediate_chain(problem, candidates, gp)
    104             append += ("\nHowever, the problem does follow DQCP rules. "
    105                        "Consider calling solve() with `qcp=True`.")
--> 106         raise DGPError("Problem does not follow DGP rules." + append)
    107 
    108     # Dcp2Cone and Qp2SymbolicQp require problems to minimize their objectives.

DGPError: Problem does not follow DGP rules.The following constraints are not DGP:
(power(ell, -2) / one_minus_pos(power(ell, -1))) / lambda + Promote(1.0, (2,)) / mu <= w_max , because the following subexpressions are not:
1.0 / mu * one_minus_pos(lambda / mu) <= d_max , because the following subexpressions are not:
|--  mu * one_minus_pos(lambda / mu)
power(ell, -2) / one_minus_pos(power(ell, -1)) <= q_max , because the following subexpressions are not:
ell == mu / lambda , because the following subexpressions are not:
```

And running the code on my pc leads to the following error(s):
```
Traceback (most recent call last):
  File "<input>", line 34, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cvxpy/problems/problem.py", line 401, in solve
    return solve_func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cvxpy/problems/problem.py", line 817, in _solve
    solution = solving_chain.solve_via_data(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 340, in solve_via_data
    return self.solver.solve_via_data(data, warm_start, verbose,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cvxpy/reductions/solvers/conic_solvers/ecos_conif.py", line 137, in solve_via_data
    solution = ecos.solve(data[s.C], data[s.G], data[s.H],
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ecos/ecos.py", line 62, in solve
    return _ecos.csolve((m,n1,p), c, data, indices, colptr, h, dims, A.data, A.indices, A.indptr, b, **kwargs)
TypeError: 'requirxes_grad' is an invalid keyword argument for this function
```

I am no expert in diagnosing the bug in the program. I just want to get to know how I can run a queuing design optimization problem using cvxpy.

I would appreciate it if you can help how to run this correctly.

**Comment by akshayka** [comment]
The code example suggests to me that you are using an old version of CVXPY. (Colab comes with an old version pre-installed.)

Add this as the first line of the first code cell:

```
!pip install --upgrade cvxpy
```

That should fix the problem.
