### ISSUE TITLE
Problem extracting data

### ISSUE THREAD

**Issue by dberma15** [cvxgrp/cvxpy#190]
I'm having trouble retrieving value that creates the minimum.

Here is my code: 
        B=Semidef(n)
        problem1=Problem(Minimize(norm(A-B,'fro')),[[trace(B)==0],[trace(B[0,0])==1]])
        problem1.solve()
and I get the error:

Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 4.0.4\helpers\pydev\pydevd.py", line 2222, in <module>
    globals = debugger.run(setup['file'], None, None)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 4.0.4\helpers\pydev\pydevd.py", line 1648, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Users/daniel/Documents/Python Scripts/GST_physics/ComputeClosestPhysicalGate.py", line 57, in <module>
    ComputeClosestPhysicalGate(G_estimated)
  File "C:/Users/daniel/Documents/Python Scripts/GST_physics/ComputeClosestPhysicalGate.py", line 19, in ComputeClosestPhysicalGate
    print problem1.solve()
  File "C:\Users\daniel\Anaconda\lib\site-packages\cvxpy\problems\problem.py", line 156, in solve
    return self._solve(*args, **kwargs)
  File "C:\Users\daniel\Anaconda\lib\site-packages\cvxpy\problems\problem.py", line 219, in _solve
    if not self.is_dcp():
  File "C:\Users\daniel\Anaconda\lib\site-packages\cvxpy\problems\problem.py", line 91, in is_dcp
    return all(exp.is_dcp() for exp in self.constraints + [self.objective])
  File "C:\Users\daniel\Anaconda\lib\site-packages\cvxpy\problems\problem.py", line 91, in <genexpr>
    return all(exp.is_dcp() for exp in self.constraints + [self.objective])
AttributeError: 'list' object has no attribute 'is_dcp'

**Comment by SteveDiamond** [comment]
It should be
```
problem1=Problem(Minimize(norm(A-B,'fro')),[trace(B)==0,trace(B[0,0])==1])
```
That's how you make a list of constraints. You had made a list of lists.

**Comment by dberma15** [comment]
Thanks. Is there a way to incorporate complex numbers?

**Comment by SteveDiamond** [comment]
There's no way right now to represent complex numbers directly. This is a
feature I hope to add soon.

You can still solve complex valued problems by representing a vector in C^n
as a vector in R^2n (see this example):

http://nbviewer.ipython.org/github/cvxgrp/cvxpy/blob/master/examples/notebooks/WWW/ant_array_min_beamwidth.ipynb
