### ISSUE TITLE
Some test failures

### ISSUE THREAD

**Issue by rmcgibbo** [cvxgrp/cvxpy#236]
Hey guys, I got a couple test failures with cvxpy-0.3.1. The platform is win x64, py34, with the following python libraries and extensions installed. FWIW, `scs` is built against OpenBLAS for BLAS/LAPACK support.

```
> conda list
cvxcanon                  0.0.21               np19py34_0
cvxopt                    1.1.7                    py34_0
cvxpy                     0.3.1                    py34_0
ecos                      2.0.4                np19py34_0
nose                      1.3.7                    py34_0
numpy                     1.9.3                    py34_0
pip                       7.1.2                    py34_0
python                    3.4.3                         0
scipy                     0.16.0               np19py34_0
scs                       1.1.7                np19py34_0
setuptools                18.3.2                   py34_0
toolz                     0.7.4                    py34_0
wheel                     0.26.0                   py34_1
```

```
> nosetests cvxpy
..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py:268: RuntimeWarning: Item size computed from the PEP 3118 buffer format string does not match the actual item size.
  arr = N.array(data, dtype=dtype, copy=copy)
E..EE.........................................E.E...EE...E.....E.................E.....E.....E.E..........................................
======================================================================
ERROR: test_transpose_variable (cvxpy.tests.test_expressions.TestExpressions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\tests\test_expressions.py", line 126, in test_transpose_variable
    self.assertEqual(var.value[0,0], 1)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\atoms\atom.py", line 180, in value
    result = self.numeric(arg_values)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\atoms\atom.py", line 194, in new_numeric
    for v in values]
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\atoms\atom.py", line 194, in <listcomp>
    for v in values]
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\base_matrix_interface.py", line 51, in new_converter
    return converter(self, value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\numpy_interface\matrix_interface.py", line 53, in const_to_matrix
    return np.asmatrix(value, dtype='float64')
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py", line 96, in asmatrix
    return matrix(data, dtype=dtype, copy=False)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py", line 268, in __new__
    arr = N.array(data, dtype=dtype, copy=copy)
TypeError: float() argument must be a string or a number, not 'cvxopt.base.matrix'

======================================================================
ERROR: Test conversion between every pair of interfaces.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\tests\test_interfaces.py", line 250, in test_conversion_between_intf
    intf1.index(intf1.const_to_matrix(mat2), key))
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\base_matrix_interface.py", line 51, in new_converter
    return converter(self, value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\cvxopt_interface\dense_matrix_interface.py", line 48, in const_to_matrix
    return cvxopt.matrix(value, tc='d')
TypeError: invalid array type

======================================================================
ERROR: test_cvxopt_dense (cvxpy.tests.test_interfaces.TestInterfaces)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\tests\test_interfaces.py", line 51, in test_cvxopt_dense
    mat = interface.const_to_matrix(sp_mat)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\base_matrix_interface.py", line 51, in new_converter
    return converter(self, value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\cvxopt_interface\dense_matrix_interface.py", line 48, in const_to_matrix
    return cvxopt.matrix(value, tc='d')
TypeError: invalid array type

======================================================================
ERROR: test_dual_variables (cvxpy.tests.test_problem.TestProblem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\tests\test_problem.py", line 718, in test_dual_variables
    [self.A >= T*self.C,
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\expression.py", line 42, in cast_op
    other = self.cast_to_const(other)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\expression.py", line 191, in cast_to_const
    return expr if isinstance(expr, Expression) else types.constant()(expr)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\constants\constant.py", line 42, in __init__
    self._value = intf.DEFAULT_INTF.const_to_matrix(value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\base_matrix_interface.py", line 51, in new_converter
    return converter(self, value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\numpy_interface\matrix_interface.py", line 53, in const_to_matrix
    return np.asmatrix(value, dtype='float64')
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py", line 96, in asmatrix
    return matrix(data, dtype=dtype, copy=False)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py", line 268, in __new__
    arr = N.array(data, dtype=dtype, copy=copy)
TypeError: float() argument must be a string or a number, not 'cvxopt.base.matrix'

======================================================================
ERROR: Test ECOS with no inequality constraints.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\tests\test_problem.py", line 479, in test_ecos_noineq
    p = Problem(Minimize(1), [self.A == T])
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\expression.py", line 42, in cast_op
    other = self.cast_to_const(other)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\expression.py", line 191, in cast_to_const
    return expr if isinstance(expr, Expression) else types.constant()(expr)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\constants\constant.py", line 42, in __init__
    self._value = intf.DEFAULT_INTF.const_to_matrix(value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\base_matrix_interface.py", line 51, in new_converter
    return converter(self, value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\numpy_interface\matrix_interface.py", line 53, in const_to_matrix
    return np.asmatrix(value, dtype='float64')
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py", line 96, in asmatrix
    return matrix(data, dtype=dtype, copy=False)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py", line 268, in __new__
    arr = N.array(data, dtype=dtype, copy=copy)
TypeError: float() argument must be a string or a number, not 'cvxopt.base.matrix'

======================================================================
ERROR: test_hstack (cvxpy.tests.test_problem.TestProblem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\tests\test_problem.py", line 844, in test_hstack
    p = Problem(Minimize(c * hstack(self.x.T, self.y.T).T),
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\expression.py", line 42, in cast_op
    other = self.cast_to_const(other)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\expression.py", line 191, in cast_to_const
    return expr if isinstance(expr, Expression) else types.constant()(expr)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\constants\constant.py", line 42, in __init__
    self._value = intf.DEFAULT_INTF.const_to_matrix(value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\base_matrix_interface.py", line 51, in new_converter
    return converter(self, value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\numpy_interface\matrix_interface.py", line 53, in const_to_matrix
    return np.asmatrix(value, dtype='float64')
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py", line 96, in asmatrix
    return matrix(data, dtype=dtype, copy=False)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py", line 268, in __new__
    arr = N.array(data, dtype=dtype, copy=copy)
TypeError: float() argument must be a string or a number, not 'cvxopt.base.matrix'

======================================================================
ERROR: test_indexing (cvxpy.tests.test_problem.TestProblem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\tests\test_problem.py", line 738, in test_indexing
    p = Problem(Minimize(sum_entries(x)), [x == A])
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\expression.py", line 42, in cast_op
    other = self.cast_to_const(other)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\expression.py", line 191, in cast_to_const
    return expr if isinstance(expr, Expression) else types.constant()(expr)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\constants\constant.py", line 42, in __init__
    self._value = intf.DEFAULT_INTF.const_to_matrix(value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\base_matrix_interface.py", line 51, in new_converter
    return converter(self, value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\numpy_interface\matrix_interface.py", line 53, in const_to_matrix
    return np.asmatrix(value, dtype='float64')
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py", line 96, in asmatrix
    return matrix(data, dtype=dtype, copy=False)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py", line 268, in __new__
    arr = N.array(data, dtype=dtype, copy=copy)
TypeError: float() argument must be a string or a number, not 'cvxopt.base.matrix'

======================================================================
ERROR: test_matrix_lp (cvxpy.tests.test_problem.TestProblem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\tests\test_problem.py", line 487, in test_matrix_lp
    p = Problem(Minimize(1), [self.A == T])
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\expression.py", line 42, in cast_op
    other = self.cast_to_const(other)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\expression.py", line 191, in cast_to_const
    return expr if isinstance(expr, Expression) else types.constant()(expr)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\constants\constant.py", line 42, in __init__
    self._value = intf.DEFAULT_INTF.const_to_matrix(value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\base_matrix_interface.py", line 51, in new_converter
    return converter(self, value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\numpy_interface\matrix_interface.py", line 53, in const_to_matrix
    return np.asmatrix(value, dtype='float64')
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py", line 96, in asmatrix
    return matrix(data, dtype=dtype, copy=False)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py", line 268, in __new__
    arr = N.array(data, dtype=dtype, copy=copy)
TypeError: float() argument must be a string or a number, not 'cvxopt.base.matrix'

======================================================================
ERROR: test_multiplication_on_left (cvxpy.tests.test_problem.TestProblem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\tests\test_problem.py", line 938, in test_multiplication_on_left
    p = Problem(Minimize(c.T*self.A*c), [self.A >= 2])
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\expression.py", line 42, in cast_op
    other = self.cast_to_const(other)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\expression.py", line 191, in cast_to_const
    return expr if isinstance(expr, Expression) else types.constant()(expr)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\constants\constant.py", line 42, in __init__
    self._value = intf.DEFAULT_INTF.const_to_matrix(value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\base_matrix_interface.py", line 51, in new_converter
    return converter(self, value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\numpy_interface\matrix_interface.py", line 53, in const_to_matrix
    return np.asmatrix(value, dtype='float64')
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py", line 96, in asmatrix
    return matrix(data, dtype=dtype, copy=False)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py", line 268, in __new__
    arr = N.array(data, dtype=dtype, copy=copy)
TypeError: float() argument must be a string or a number, not 'cvxopt.base.matrix'

======================================================================
ERROR: Tests problems with reshape.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\tests\test_problem.py", line 1103, in test_reshape
    obj = Minimize(sum_entries(mat*expr))
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\expression.py", line 42, in cast_op
    other = self.cast_to_const(other)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\expression.py", line 191, in cast_to_const
    return expr if isinstance(expr, Expression) else types.constant()(expr)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\constants\constant.py", line 42, in __init__
    self._value = intf.DEFAULT_INTF.const_to_matrix(value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\base_matrix_interface.py", line 51, in new_converter
    return converter(self, value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\numpy_interface\matrix_interface.py", line 53, in const_to_matrix
    return np.asmatrix(value, dtype='float64')
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py", line 96, in asmatrix
    return matrix(data, dtype=dtype, copy=False)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py", line 268, in __new__
    arr = N.array(data, dtype=dtype, copy=copy)
TypeError: float() argument must be a string or a number, not 'cvxopt.base.matrix'

======================================================================
ERROR: test_transpose (cvxpy.tests.test_problem.TestProblem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\tests\test_problem.py", line 889, in test_transpose
    p = Problem(Minimize(sum_entries(self.x)), [self.x.T >= matrix([1,2]).T])
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\expression.py", line 42, in cast_op
    other = self.cast_to_const(other)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\expression.py", line 191, in cast_to_const
    return expr if isinstance(expr, Expression) else types.constant()(expr)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\constants\constant.py", line 42, in __init__
    self._value = intf.DEFAULT_INTF.const_to_matrix(value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\base_matrix_interface.py", line 51, in new_converter
    return converter(self, value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\numpy_interface\matrix_interface.py", line 53, in const_to_matrix
    return np.asmatrix(value, dtype='float64')
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py", line 96, in asmatrix
    return matrix(data, dtype=dtype, copy=False)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py", line 268, in __new__
    arr = N.array(data, dtype=dtype, copy=copy)
TypeError: float() argument must be a string or a number, not 'cvxopt.base.matrix'

======================================================================
ERROR: test_vector_lp (cvxpy.tests.test_problem.TestProblem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\tests\test_problem.py", line 456, in test_vector_lp
    p = Problem(Minimize(c.T*self.x), [self.x >= c])
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\expression.py", line 42, in cast_op
    other = self.cast_to_const(other)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\expression.py", line 191, in cast_to_const
    return expr if isinstance(expr, Expression) else types.constant()(expr)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\constants\constant.py", line 42, in __init__
    self._value = intf.DEFAULT_INTF.const_to_matrix(value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\base_matrix_interface.py", line 51, in new_converter
    return converter(self, value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\numpy_interface\matrix_interface.py", line 53, in const_to_matrix
    return np.asmatrix(value, dtype='float64')
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py", line 96, in asmatrix
    return matrix(data, dtype=dtype, copy=False)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py", line 268, in __new__
    arr = N.array(data, dtype=dtype, copy=copy)
TypeError: float() argument must be a string or a number, not 'cvxopt.base.matrix'

======================================================================
ERROR: test_vstack (cvxpy.tests.test_problem.TestProblem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\tests\test_problem.py", line 806, in test_vstack
    p = Problem(Minimize(c * vstack(self.x, self.y)),
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\expression.py", line 42, in cast_op
    other = self.cast_to_const(other)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\expression.py", line 191, in cast_to_const
    return expr if isinstance(expr, Expression) else types.constant()(expr)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\expressions\constants\constant.py", line 42, in __init__
    self._value = intf.DEFAULT_INTF.const_to_matrix(value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\base_matrix_interface.py", line 51, in new_converter
    return converter(self, value)
  File "C:\Miniconda3\envs\_test\lib\site-packages\cvxpy\interface\numpy_interface\matrix_interface.py", line 53, in const_to_matrix
    return np.asmatrix(value, dtype='float64')
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py", line 96, in asmatrix
    return matrix(data, dtype=dtype, copy=False)
  File "C:\Miniconda3\envs\_test\lib\site-packages\numpy\matrixlib\defmatrix.py", line 268, in __new__
    arr = N.array(data, dtype=dtype, copy=copy)
TypeError: float() argument must be a string or a number, not 'cvxopt.base.matrix'

----------------------------------------------------------------------
Ran 2552 tests in 17.531s

FAILED (errors=13)
```

**Comment by SteveDiamond** [comment]
It looks like NumPy won't convert cvxopt matrices into ndarrays. I'm not sure why this happens on your set up but not on mine.

**Comment by rmcgibbo** [comment]
FWIW, I don't get any of these errors on win-32 -- only win-64. Linux and OS X are fine as well.

**Comment by SteveDiamond** [comment]
This has been fixed.
