### ISSUE TITLE
CVXOPT fails on exp cone problem

### ISSUE THREAD

**Issue by mwytock** [cvxgrp/cvxpy#249]
Adding axis parameter to log_sum_exp seems (https://github.com/cvxgrp/cvxpy/pull/247) to cause CVXOPT to fail in a nondeterministic fashion (is there some randomness in the initialization?). All other solvers pass reliably without problem.

Here is an example a failure case, running the atoms

```
atoms = [
    ([
        (lambda x: log_sum_exp(x, axis=0), (1,2), [ [[5, 7], [0, -3]] ], Constant([7.12692801, 0.04858735]).T),
        (lambda x: log_sum_exp(x, axis=1), (2,1), [ [[5, 7], [0, -3]] ], Constant([5.00671535, 7.0000454])),
    ], Minimize),
]
```
and just CVXOPT solver 

```
SOLVERS_TO_TRY = [CVXOPT]
```
Failure example:

```
cd $HOME/cvxpy && nosetests cvxpy.tests.test_constant_atoms
.E..........
======================================================================
ERROR: cvxpy.tests.test_constant_atoms.test_atom(<function <lambda> at 0x107a926e0>, Problem(Minimize(Expression(CONVEX, UNKNOWN, (1, 1))), [EqConstraint(Variable(2, 2), Constant(CONSTANT, UNKNOWN, (2, 2)))]), 7.12692801, 'CVXOPT')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/mwytock/cvxpy/cvxpy/tests/test_constant_atoms.py", line 266, in run_atom
    result = problem.solve(solver=solver, verbose=True)
  File "/Users/mwytock/cvxpy/cvxpy/problems/problem.py", line 173, in solve
    return self._solve(*args, **kwargs)
  File "/Users/mwytock/cvxpy/cvxpy/problems/problem.py", line 284, in _solve
    self._update_problem_state(results_dict, sym_data, solver)
  File "/Users/mwytock/cvxpy/cvxpy/problems/problem.py", line 396, in _update_problem_state
    "Solver '%s' failed. Try another solver." % solver.name())
SolverError: Solver 'CVXOPT' failed. Try another solver.
-------------------- >> begin captured stdout << ---------------------
minimize log_sum_exp(var1)[0, 0]
[EqConstraint(Variable(2, 2), Constant(CONSTANT, UNKNOWN, (2, 2)))]
('solver', 'CVXOPT')
     pcost       dcost       gap    pres   dres
 0:  0.0000e+00  6.1371e-01  6e+00  1e+00  1e+00
 1:  3.3414e+00  6.4737e+00  3e+00  5e-01  6e-01
 2:  7.1059e+00  6.7962e+00  8e-01  8e-02  3e-01
 3:  7.1243e+00  7.0847e+00  1e-01  1e-02  6e-02
 4:  7.1291e+00  7.1247e+00  1e-02  2e-03  2e-02
 5:  7.1272e+00  7.1269e+00  4e-04  9e-05  2e-03
 6:  7.1269e+00  7.1269e+00  5e-06  1e-06  2e-04
 7:  7.1269e+00  7.1269e+00  5e-08  1e-08  3e-06
Terminated (singular KKT matrix).

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 12 tests in 0.134s

FAILED (errors=1)
```

Failure example #2:

```
cd $HOME/cvxpy && nosetests cvxpy.tests.test_constant_atoms
....E.......
======================================================================
ERROR: cvxpy.tests.test_constant_atoms.test_atom(<function <lambda> at 0x103f396e0>, Problem(Minimize(Expression(CONVEX, UNKNOWN, (1, 1))), [EqConstraint(Variable(2, 2), Constant(CONSTANT, UNKNOWN, (2, 2)))]), 0.04858735, 'CVXOPT')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/mwytock/cvxpy/cvxpy/tests/test_constant_atoms.py", line 266, in run_atom
    result = problem.solve(solver=solver, verbose=True)
  File "/Users/mwytock/cvxpy/cvxpy/problems/problem.py", line 173, in solve
    return self._solve(*args, **kwargs)
  File "/Users/mwytock/cvxpy/cvxpy/problems/problem.py", line 284, in _solve
    self._update_problem_state(results_dict, sym_data, solver)
  File "/Users/mwytock/cvxpy/cvxpy/problems/problem.py", line 396, in _update_problem_state
    "Solver '%s' failed. Try another solver." % solver.name())
SolverError: Solver 'CVXOPT' failed. Try another solver.
-------------------- >> begin captured stdout << ---------------------
minimize log_sum_exp(var17)[0, 1]
[EqConstraint(Variable(2, 2), Constant(CONSTANT, UNKNOWN, (2, 2)))]
('solver', 'CVXOPT')
     pcost       dcost       gap    pres   dres
 0:  0.0000e+00  6.1371e-01  6e+00  1e+00  1e+00
 1: -1.4084e-01  5.6947e-01  4e+00  7e-01  7e-01
 2: -5.5950e-02 -2.0643e-02  1e+00  3e-01  3e-01
 3:  1.1818e-01 -7.7679e-02  3e-01  3e-02  9e-02
 4:  5.7997e-02  3.5162e-02  3e-02  5e-03  1e-02
 5:  4.9417e-02  4.8291e-02  2e-03  9e-04  3e-03
 6:  4.8610e-02  4.8584e-02  4e-05  2e-05  4e-04
 7:  4.8588e-02  4.8587e-02  4e-07  2e-07  2e-05
 8:  4.8587e-02  4.8587e-02  4e-09  2e-09  3e-07
Terminated (singular KKT matrix).

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 12 tests in 0.131s

FAILED (errors=1)
```

Sometimes it passes fine:

```
cd $HOME/cvxpy && nosetests cvxpy.tests.test_constant_atoms
............
----------------------------------------------------------------------
Ran 12 tests in 0.137s

OK
```

**Comment by SteveDiamond** [comment]
I don't see any randomness on my machine. This snippet always fails:
```
from cvxpy import *
x = Variable(2,2)
obj = Minimize(log_sum_exp(x, axis=0)[0,0])
constr = [ x == [[5, 7], [0, -3]] ]
prob = Problem(obj, constr)
prob.solve(solver=CVXOPT, verbose=True)

sltn = Constant([7.12692801, 0.04858735]).T
```

**Comment by SteveDiamond** [comment]
The randomness you're seeing might be related to setting the CVXOPT solver options. These are stored globally, so nosetests can have race conditions when it's solving multiple CVXOPT problems. I raised this issue on the CVXOPT repo (https://github.com/cvxopt/cvxopt/issues/37), and it might be fixed in the latest version. But I think the options are the same for all the problems in ``test_constant_atoms.py``.

**Comment by mwytock** [comment]
Your snippet fails randomly as well:

In [4]:      pcost       dcost       gap    pres   dres
 0:  0.0000e+00  6.1371e-01  6e+00  1e+00  1e+00
 1:  3.3414e+00  6.4737e+00  3e+00  5e-01  6e-01
 2:  7.1059e+00  6.7962e+00  8e-01  8e-02  3e-01
 3:  7.1243e+00  7.0847e+00  1e-01  1e-02  6e-02
 4:  7.1291e+00  7.1247e+00  1e-02  2e-03  2e-02
 5:  7.1272e+00  7.1269e+00  4e-04  9e-05  2e-03
 6:  7.1269e+00  7.1269e+00  5e-06  1e-06  2e-04
 7:  7.1269e+00  7.1269e+00  5e-08  1e-08  3e-06
 8:  7.1269e+00  7.1269e+00  5e-10  1e-10  5e-08
Optimal solution found.

In [5]:      pcost       dcost       gap    pres   dres
 0:  0.0000e+00  6.1371e-01  6e+00  1e+00  1e+00
 1:  3.3414e+00  6.4737e+00  3e+00  5e-01  6e-01
 2:  7.1059e+00  6.7962e+00  8e-01  8e-02  3e-01
 3:  7.1243e+00  7.0847e+00  1e-01  1e-02  6e-02
 4:  7.1291e+00  7.1247e+00  1e-02  2e-03  2e-02
 5:  7.1272e+00  7.1269e+00  4e-04  9e-05  2e-03
 6:  7.1269e+00  7.1269e+00  5e-06  1e-06  2e-04
 7:  7.1269e+00  7.1269e+00  5e-08  1e-08  3e-06
Terminated (singular KKT matrix).

What output do you see? Is this with latest version of CVXOPT?

Matts-MacBook-Air:cvxpy mwytock$ pip list | grep cvxopt
cvxopt (1.1.8)

**Comment by mwytock** [comment]
It seems to be due to numerical issues in the KKT solver, if I switch kktsolver to one of "chol2", "ldl", "ldl2" it works reliably (please verify!) 

I'm inferring from the existing of ROBUST_KKTSOLVER that this is a known issue... (?) thus it seems best course of action is either

1) Add to KNOWN_SOLVER_ERRORS 
2) Some way to make default cvxopt more robust (e.g. use LDL by default) 

Let me know how you want to proceed.

**Comment by SteveDiamond** [comment]
I was using CVXOPT 1.1.7. I upgraded to 1.1.8 and it still fails every time. In any case, just add it to KNOWN_SOLVER_ERRORS. The LDL solver is unbelievably slow (it treats the sparse linear system as dense), so it's not reasonable to have it as the default.

**Comment by mwytock** [comment]
sounds good!
