### ISSUE TITLE
ImportError (no module named 'multiprocess')

### ISSUE THREAD

**Issue by anshulshah96** [cvxgrp/cvxpy#269]
I installed cvxpy from anaconda by
```
conda install pip nose numpy scipy cvxopt
```
then cloned the repo from https://github.com/cvxgrp/cvxpy and then ran
```
sudo python setup.py install.sh
```
After that running
```
nosetests cvxpy
```
gives me following error:

ERROR: Failure: ImportError (No module named 'multiprocess')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anshul/anaconda3/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/anshul/anaconda3/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/anshul/anaconda3/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/anshul/anaconda3/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/anshul/anaconda3/lib/python3.5/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/home/anshul/anaconda3/lib/python3.5/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/anshul/MyProjects/cvxpy/cvxpy/__init__.py", line 25, in <module>
    from cvxpy.problems.problem import Problem
  File "/home/anshul/MyProjects/cvxpy/cvxpy/problems/problem.py", line 34, in <module>
    import multiprocess as multiprocessing
ImportError: No module named 'multiprocess'

Any suggestions will be very helpful as I am trying to develop cone solvers testing module.

**Comment by SteveDiamond** [comment]
I'm really not sure what's causing this. Can you install the ``multiprocess`` package on its own? You may want to use Python 2.7.
