### ISSUE TITLE
Error message when importing. 

### ISSUE THREAD

**Issue by alexanderwhatley** [cvxgrp/cvxpy#323]
I'm on Ubuntu 16.10, Python 3.5. I get the following error message when importing:

```
>>> import cvxpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/cvxpy/__init__.py", line 21, in <module>
    from cvxpy.atoms import *
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/cvxpy/atoms/__init__.py", line 20, in <module>
    from cvxpy.atoms.affine_prod import affine_prod
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/cvxpy/atoms/affine_prod.py", line 20, in <module>
    from cvxpy.atoms.atom import Atom
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/cvxpy/atoms/atom.py", line 21, in <module>
    from .. import utilities as u
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/cvxpy/utilities/__init__.py", line 24, in <module>
    from .quadratic import QuadCoeffExtractor
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/cvxpy/utilities/quadratic.py", line 24, in <module>
    import canonInterface
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/canonInterface.py", line 16, in <module>
    import CVXcanon
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/CVXcanon.py", line 28, in <module>
    _CVXcanon = swig_import_helper()
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/CVXcanon.py", line 24, in swig_import_helper
    _mod = imp.load_module('_CVXcanon', fp, pathname, description)
  File "/home/alexander/anaconda3/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/alexander/anaconda3/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/alexander/anaconda3/lib/python3.5/site-packages/_CVXcanon.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev
```

**Comment by SteveDiamond** [comment]
Did you install everything using Anaconda and the cvxgrp channel? I've never seen this error before.

**Comment by alexanderwhatley** [comment]
I fixed it by installing using anaconda. The pip installation doesn't seem to work though.

**Comment by SteveDiamond** [comment]
Ok, that makes sense. The pip installation is fairly complicated and not recommended anymore.
