### ISSUE TITLE
got error:AttributeError: 'LinOp' object has no attribute 'shape'

### ISSUE THREAD

**Issue by nupurmodi** [cvxgrp/cvxpy#360]
Traceback (most recent call last):
  File "C:/python/intern_work/cvx_try.py", line 17, in <module>
    print ("Optimal value", prob.solve())
  File "C:\python\lib\site-packages\cvxpy-0.4.9-py3.6.egg\cvxpy\problems\problem.py", line 209, in solve
    return self._solve(*args, **kwargs)
  File "C:\python\lib\site-packages\cvxpy-0.4.9-py3.6.egg\cvxpy\problems\problem.py", line 331, in _solve
    kwargs)
  File "C:\python\lib\site-packages\cvxpy-0.4.9-py3.6.egg\cvxpy\problems\solvers\ecos_intf.py", line 118, in solve
    data = self.get_problem_data(objective, constraints, cached_data)
  File "C:\python\lib\site-packages\cvxpy-0.4.9-py3.6.egg\cvxpy\problems\solvers\solver.py", line 246, in get_problem_data
    cached_data)
  File "C:\python\lib\site-packages\cvxpy-0.4.9-py3.6.egg\cvxpy\problems\solvers\solver.py", line 224, in get_matrix_data
    self.nonlin_constr())
  File "C:\python\lib\site-packages\cvxpy-0.4.9-py3.6.egg\cvxpy\problems\problem_data\matrix_data.py", line 79, in __init__
    self._lin_matrix(self.obj_cache, caching=True)
  File "C:\python\lib\site-packages\cvxpy-0.4.9-py3.6.egg\cvxpy\problems\problem_data\matrix_data.py", line 181, in _lin_matrix
    constr_offsets
  File "C:\python\lib\site-packages\cvxcanon-0.1.1-py3.6-win-amd64.egg\canonInterface.py", line 67, in get_problem_matrix
    tree = build_lin_op_tree(lin, tmp)
  File "C:\python\lib\site-packages\cvxcanon-0.1.1-py3.6-win-amd64.egg\canonInterface.py", line 237, in build_lin_op_tree
    linC.size.push_back(int(linPy.shape[0]))
AttributeError: 'LinOp' object has no attribute 'shape'

**Comment by roversch** [comment]
One of the upcoming changes in cvxpy 1.0 is that `size` is replaced by `shape`, also in CVXcanon. Which versions of CVXPY and CVXcanon are you running?

**Comment by nupurmodi** [comment]
0.4.9 cvxpy and 0.1.1 cvxcanon

**Comment by roversch** [comment]
There seems to be an inconsistency, as CVXcanon 0.1.1 uses `shape` but cvxpy 0.4.9 uses `size`. @SteveDiamond , maybe change the version of CVXcanon to be `== 1.1.0`?

**Comment by nupurmodi** [comment]
no have installed python 3.6.0 directly and using pip to install packages

**Comment by SteveDiamond** [comment]
To be clear this should not happen unless you install CVXcanon from source.
