### ISSUE TITLE
gurobipy.GurobiError: Unsupported type (<class 'numpy.ndarray'>) for LinExpr addition argument

### ISSUE THREAD

**Issue by fhchl** [cvxgrp/cvxpy#370]
```python
import numpy as np
import cvxpy as cvx

n = 4
H = cvx.Constant(np.random.random((n,n)))
p = cvx.Constant(np.random.random((n)))
q = cvx.Variable(n)

obj = cvx.Minimize(cvx.square(cvx.norm((H*q-p))))
    
prob = cvx.Problem(obj)
prob.solve(solver=cvx.GUROBI, verbose=True)
```

fails with

```
Traceback (most recent call last):
  File "/home/fmheu/Dropbox/DTU/PhD/Subprojects/cvx/gurobi_numpyarraybug.py", line 14, in <module>
    prob.solve(solver=cvx.GUROBI, verbose=True)
  File "/home/fmheu/anaconda3/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 209, in solve
    return self._solve(*args, **kwargs)
  File "/home/fmheu/anaconda3/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 331, in _solve
    kwargs)
  File "/home/fmheu/anaconda3/lib/python3.6/site-packages/cvxpy/problems/solvers/gurobi_intf.py", line 244, in solve
    nonzero_locs, A, b
  File "/home/fmheu/anaconda3/lib/python3.6/site-packages/cvxpy/problems/solvers/gurobi_intf.py", line 398, in add_model_soc_constr
    model.addConstr(soc_vars[i] == lin_expr_list[i])
  File "model.pxi", line 2707, in gurobipy.Model.addConstr (../../src/python/gurobipy.c:82417)
  File "linexpr.pxi", line 432, in gurobipy.LinExpr.__sub__ (../../src/python/gurobipy.c:33171)
  File "linexpr.pxi", line 411, in gurobipy.LinExpr.__add__ (../../src/python/gurobipy.c:32776)
  File "linexpr.pxi", line 156, in gurobipy.LinExpr.add (../../src/python/gurobipy.c:30164)
gurobipy.GurobiError: Unsupported type (<class 'numpy.ndarray'>) for LinExpr addition argument
```
on anaconda Python 3.6.1 with these packages:

```
numpy                     1.13.1                   py36_0
cvxpy                     0.4.9                    py36_0    cvxgrp
gurobi                    7.5.0                    py36_0    gurobi
```

The default solver (ECOS) solves it without problems.

**Comment by SteveDiamond** [comment]
Pretty sure this is fixed by now.
