### ISSUE TITLE
AttributeError: 'SDP' object has no attribute 'variables'

### ISSUE THREAD

**Issue by hadasba1** [cvxgrp/cvxpy#376]
using SDP constraint I get the following error:
Traceback (most recent call last):
  File "C:/Users/hadas/PycharmProjects/projAlg/SDPup.py", line 102, in <module>
    main(numpy.array([0.2,0,0,0,0.3,0,0]),numpy.array([1,0.7,0,0,0.7,0,0]),[[[1],[0],[5]]])
  File "C:/Users/hadas/PycharmProjects/projAlg/SDPup.py", line 62, in main
    prob = Problem(objective,consts)
  File "C:\Users\hadas\Anaconda2\lib\site-packages\cvxpy\problems\problem.py", line 78, in __init__
    self._size_metrics = SizeMetrics(self)
  File "C:\Users\hadas\Anaconda2\lib\site-packages\cvxpy\problems\problem.py", line 672, in __init__
    for var in problem.variables():
  File "C:\Users\hadas\Anaconda2\lib\site-packages\cvxpy\problems\problem.py", line 145, in variables
    vars_ += constr.variables()
AttributeError: 'SDP' object has no attribute 'variables'

**Comment by SteveDiamond** [comment]
Sorry I need a minimal working example to look into this further. What do you mean by using SDP constraint exactly? You're not using the ``SDP`` class explicitly right? That's not permitted.
