### ISSUE TITLE
Issues with variables initialized with numpy.int64 dimensions

### ISSUE THREAD

**Issue by calebsander** [cvxgrp/cvxpy#380]
I was running into strange error messages from CVXPY and tracked it down to creating a `Variable` with a dimension of type `numpy.int64`. It will happily get created and some simple problems can actually be solved without issues. However, it throws errors when used in certain ways. These are two minimal programs I made to showcase the issue. Both crash on `problem.solve()` with CVXPY 0.4.10.
````python
import cvxpy as cvx
import numpy as np

q = cvx.Variable(np.int64(2))
objective = cvx.Minimize(cvx.norm(q, 1)) #but this works fine with np.identity(2) * q instead of q
problem = cvx.Problem(objective)
problem.solve()
print(q.value)
````

````python
import cvxpy as cvx
import numpy as np

q = cvx.Variable(np.int64(2))
objective = cvx.Minimize(cvx.norm(np.identity(2) * q, 1))
constraints = []
for index in range(-2, 0): #issue doesn't occur with positive indices (i.e. range(2))
    constraints.append(0 <= q[index])
    constraints.append(q[index] <= 2)
problem = cvx.Problem(objective, constraints)
problem.solve()
print(q.value)
````

These are the errors I get:
1.
````
Traceback (most recent call last):
  File ".\cvx-error.py", line 7, in <module>
    problem.solve()
  File "C:\Program Files\Python36\lib\site-packages\cvxpy\problems\problem.py", line 209, in solve
    return self._solve(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\cvxpy\problems\problem.py", line 331, in _solve
    kwargs)
  File "C:\Program Files\Python36\lib\site-packages\cvxpy\problems\solvers\ecos_intf.py", line 123, in solve
    **solver_opts)
  File "C:\Program Files\Python36\lib\site-packages\ecos.py", line 62, in solve
    return _ecos.csolve((m,n1,p), c, data, indices, colptr, h, dims, A.data, A.indices, A.indptr, b, **kwargs)
TypeError: dims['l'] ought to be a nonnegative integer
````
2.
````
Traceback (most recent call last):
  File ".\cvx-error.py", line 11, in <module>
    problem.solve()
  File "C:\Program Files\Python36\lib\site-packages\cvxpy\problems\problem.py", line 209, in solve
    return self._solve(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\cvxpy\problems\problem.py", line 331, in _solve
    kwargs)
  File "C:\Program Files\Python36\lib\site-packages\cvxpy\problems\solvers\ecos_intf.py", line 118, in solve
    data = self.get_problem_data(objective, constraints, cached_data)
  File "C:\Program Files\Python36\lib\site-packages\cvxpy\problems\solvers\solver.py", line 248, in get_problem_data
    cached_data)
  File "C:\Program Files\Python36\lib\site-packages\cvxpy\problems\solvers\solver.py", line 226, in get_matrix_data
    self.nonlin_constr())
  File "C:\Program Files\Python36\lib\site-packages\cvxpy\problems\problem_data\matrix_data.py", line 90, in __init__
    self._lin_matrix(self.ineq_cache, caching=True)
  File "C:\Program Files\Python36\lib\site-packages\cvxpy\problems\problem_data\matrix_data.py", line 181, in _lin_matrix
    constr_offsets
  File "C:\Program Files\Python36\lib\site-packages\canonInterface.py", line 52, in get_problem_matrix
    tree = build_lin_op_tree(lin, tmp)
  File "C:\Program Files\Python36\lib\site-packages\canonInterface.py", line 229, in build_lin_op_tree
    set_slice_data(linC, linPy)
  File "C:\Program Files\Python36\lib\site-packages\canonInterface.py", line 151, in set_slice_data
    vec.push_back(var)
  File "C:\Program Files\Python36\lib\site-packages\CVXcanon.py", line 426, in push_back
    return _CVXcanon.IntVector_push_back(self, x)
TypeError: in method 'IntVector_push_back', argument 2 of type 'std::vector< int >::value_type'
````

**Comment by calebsander** [comment]
Maybe it would be easiest to just convert all variable dimensions into Python ints?
