### ISSUE TITLE
Test for Bool/Int vars failed on Anaconda 5.0.1, x86_64 CentOS 6.9

### ISSUE THREAD

**Issue by smax1** [cvxgrp/cvxpy#412]
Hi,

With cvxpy branch 1.0 installed on Anaconda 5.0.1 on x86_64 CentOS release 6.9, running 'nosetests cvxpy' produced the failures shown below. 

These appear to be integer optimization tests. Do these test require some integer solvers? If so and the solvers are not installed, should cvxpy return an error when user attempts to solve a problem with integer/bool variables? Should the test then detect such an error and call it a PASS?

Best regards

.....
FAIL: test_bool_prob (cvxpy.tests.test_mip_vars.TestMIPVariable)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zxz/projects/cvxpy/cvxpy/tests/test_mip_vars.py", line 68, in test_bool_prob
    self.assertAlmostEqual(result, 0.04)
  File "/home/zxz/projects/cvxpy/cvxpy/tests/base_test.py", line 41, in assertAlmostEqual
    super(BaseTest, self).assertAlmostEqual(a, b, places=places)
AssertionError: -9.6512764254799896e-10 != 0.04 within 5 places

======================================================================
FAIL: test_int_prob (cvxpy.tests.test_mip_vars.TestMIPVariable)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zxz/projects/cvxpy/cvxpy/tests/test_mip_vars.py", line 104, in test_int_prob
    self.assertAlmostEqual(result, 0.04)
  File "/home/zxz/projects/cvxpy/cvxpy/tests/base_test.py", line 41, in assertAlmostEqual
    super(BaseTest, self).assertAlmostEqual(a, b, places=places)
AssertionError: 1.5064355097799085e-08 != 0.04 within 5 places

----------------------------------------------------------------------
Ran 1818 tests in 211.205s

FAILED (failures=2)

**Comment by SteveDiamond** [comment]
You need to update ECOS. The old version had a bug in the branch and bound module.

**Comment by smax1** [comment]
Thank you for the quick reply.

My current ECOS conda package is 2.0.4, which is the latest:
  https://anaconda.org/anaconda/ecos

This also appears to be the latest on github as well:
  https://github.com/embotech/ecos-python

Which version and source would you recommend?

**Comment by SteveDiamond** [comment]
Can you try installing ECOS from pip?

**Comment by smax1** [comment]
Version 2.0.4 appears to be the latest there too:
  https://pypi.python.org/pypi/ecos

**Comment by SteveDiamond** [comment]
Try again now. I forgot to upload it apparently.

**Comment by smax1** [comment]
Thank you very much. After running '$ pip install --user --ignore-installed
ecos' all '$ nosetests cvxpy' pass.

**Comment by smax1** [comment]
Sorry for the followup, but if this matters... Although the module version
is 2.0.5, it is installed into directory:
  ~/.local/lib/python3.6/site-packages/ecos-*2.0.4*
-py3.6-linux-x86_64.egg/ecos.py
, which implies version 2.0.4. Perhaps, setup.py also needs to be updated.
