### ISSUE TITLE
Failing to install CVXPY 1.0

### ISSUE THREAD

**Issue by jpiabrantes** [cvxgrp/cvxpy#461]
I followed the installation guide for version 1.0, everything worked but I can't import cvxpy now:
```sh
>>> import cvxpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joao/github/cvxpy/cvxpy/__init__.py", line 21, in <module>
    from cvxpy.atoms import *
  File "/home/joao/github/cvxpy/cvxpy/atoms/__init__.py", line 20, in <module>
    from cvxpy.atoms.geo_mean import geo_mean
  File "/home/joao/github/cvxpy/cvxpy/atoms/geo_mean.py", line 23, in <module>
    from cvxpy.utilities.power_tools import (fracify, decompose, approx_error, lower_bound,
  File "/home/joao/github/cvxpy/cvxpy/utilities/power_tools.py", line 21, in <module>
    from cvxpy.atoms.affine.reshape import reshape
  File "/home/joao/github/cvxpy/cvxpy/atoms/affine/reshape.py", line 20, in <module>
    from cvxpy.atoms.affine.affine_atom import AffAtom
  File "/home/joao/github/cvxpy/cvxpy/atoms/affine/affine_atom.py", line 25, in <module>
    from cvxpy.CVXcanon.python import canonInterface
  File "/home/joao/github/cvxpy/cvxpy/CVXcanon/python/canonInterface.py", line 32, in <module>
    import cvxpy.CVXcanon.python.CVXcanon as CVXcanon
  File "/home/joao/github/cvxpy/cvxpy/CVXcanon/python/CVXcanon.py", line 229, in <module>
    class LinOp(_object):
  File "/home/joao/github/cvxpy/cvxpy/CVXcanon/python/CVXcanon.py", line 247, in LinOp
    __swig_setmethods__["data_ndim"] = _CVXcanon.LinOp_data_ndim_set
AttributeError: module '_CVXcanon' has no attribute 'LinOp_data_ndim_set'
```

Note that I had the previous version of cvxpy already installed. I am running Python 3.6 on Ubuntu.

**Comment by jpiabrantes** [comment]
Uninstalling CVXcanon solved the problem.
`pip uninstall CVXcanon`

**Comment by varunbk** [comment]
I had used conda to install the earlier version of cvxpy (0.4.9), so "pip uninstall CVXcanon" did not work for me, but "conda uninstall CVXcanon" did.
