### ISSUE TITLE
KeyError with GUROBI solver

### ISSUE THREAD

**Issue by pronif** [cvxgrp/cvxpy#478]
Hello,

I encounter an error when I try to use *cvxpy* with GUROBI solver.

I set the solver to GUROBI in the example in the  *README.md*:

```
result = prob.solve(solver="GUROBI", verbose=True)
```
I get the following error:

    $ python test.py  
    Academic license - for non-commercial use only  
    Traceback (most recent call last):
    File "test.py", line 18, in <module>
    result = prob.solve(solver="GUROBI", verbose=True)
    File "/usr/local/lib/python2.7/site-packages/cvxpy-0.4.11-py2.7.egg/cvxpy/problems/problem.py", line 209, in solve
    return self._solve(*args, **kwargs)
    File "/usr/local/lib/python2.7/site-packages/cvxpy-0.4.11-py2.7.egg/cvxpy/problems/problem.py", line 331, in _solve
    kwargs)
    File "/usr/local/lib/python2.7/site-packages/cvxpy-0.4.11-py2.7.egg/cvxpy/problems/solvers/gurobi_intf.py", line 229, in solve
    A, b)
    File "/usr/local/lib/python2.7/site-packages/cvxpy-0.4.11-py2.7.egg/cvxpy/problems/solvers/gurobi_intf.py", line 326, in add_model_lin_constr
    expr_list[i].append((c, v))
    KeyError: 55

I get a similar error in different examples when I set the solver to Gurobi, but not with the default ECOS.

I installed *cvxpy* from the repo with ```python setup.py build``` and ```python setup.py install```. Gurobi seems installed correctly. I can import without error ```gurobipy``` and it shows in the list of installed solvers:

     >>> import cvxpy
     >>> print cvxpy.installed_solvers()
    ['ECOS_BB', 'SCS', 'ECOS', 'GUROBI', 'LS']

I am on a Macbook with Sierra.

**Comment by pronif** [comment]
I solved by downgrading to tag 0.4.0. My problem is now solved.

If I have time I will look into the issue. It should be a minor index error in the file `cvxpy/problem/solvers/gurobi_inft.py`

**Comment by rileyjmurray** [comment]
There are two parts to this.

First: cvxpy 1.0 is about to replace cvxpy 0.4, so this fix won't appear in any cvxpy 0.4.x variant.

Second: the file gurobi_inft.py is used in cvxpy 1.0 (a native 1.0 interface for Gurobi hasn't been written yet), so this issue *will* need to be investigated and fixed.
