### ISSUE TITLE
cvxpy.error.SolverError: The solver SCS is not installed.

### ISSUE THREAD

**Issue by jpiabrantes** [cvxgrp/cvxpy#488]
I've just followed the instructions on [cvxpy 1.0 installation guide](https://cvxgrp.github.io/cvxpy/install/index.html) in a brand new Ubuntu 16.04 machine. When I run `nosetests cvxpy` I get:

```sh
======================================================================
ERROR: Failure: ImportError (libmkl_intel_lp64.so: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/ubuntu/anaconda3/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/ubuntu/anaconda3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/tests/test_problem.py", line 34, in <module>
    import scs
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/scs.py", line 4, in <module>
    import _scs_indirect
ImportError: libmkl_intel_lp64.so: cannot open shared object file: No such file or directory

======================================================================
ERROR: Test a problem with entr.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/tests/test_scs.py", line 132, in test_entr
    p.solve(solver=cvx.SCS, verbose=True)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 246, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 356, in _solve
    raise e
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 354, in _solve
    solver=solver)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/reductions/solvers/solving_chain.py", line 48, in construct_solving_chain
    raise SolverError("The solver %s is not installed." % solver)
cvxpy.error.SolverError: The solver SCS is not installed.
-------------------- >> begin captured stdout << ---------------------
5

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: Test a problem with exp.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/tests/test_scs.py", line 143, in test_exp
    p.solve(solver=cvx.SCS, verbose=True)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 246, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 356, in _solve
    raise e
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 354, in _solve
    solver=solver)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/reductions/solvers/solving_chain.py", line 48, in construct_solving_chain
    raise SolverError("The solver %s is not installed." % solver)
cvxpy.error.SolverError: The solver SCS is not installed.
-------------------- >> begin captured stdout << ---------------------
5

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: Test a problem with kl_div.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/tests/test_scs.py", line 121, in test_kl_div
    result = klprob.solve(solver=cvx.SCS, verbose=True)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 246, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 356, in _solve
    raise e
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 354, in _solve
    solver=solver)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/reductions/solvers/solving_chain.py", line 48, in construct_solving_chain
    raise SolverError("The solver %s is not installed." % solver)
cvxpy.error.SolverError: The solver SCS is not installed.

======================================================================
ERROR: Test a problem with log.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/tests/test_scs.py", line 154, in test_log
    p.solve(solver=cvx.SCS, verbose=True)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 246, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 356, in _solve
    raise e
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 354, in _solve
    solver=solver)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/reductions/solvers/solving_chain.py", line 48, in construct_solving_chain
    raise SolverError("The solver %s is not installed." % solver)
cvxpy.error.SolverError: The solver SCS is not installed.
-------------------- >> begin captured stdout << ---------------------
5

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_log_problem (cvxpy.tests.test_scs.TestSCS)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/tests/test_scs.py", line 52, in test_log_problem
    result = p.solve(solver=cvx.SCS)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 246, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 356, in _solve
    raise e
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 354, in _solve
    solver=solver)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/reductions/solvers/solving_chain.py", line 48, in construct_solving_chain
    raise SolverError("The solver %s is not installed." % solver)
cvxpy.error.SolverError: The solver SCS is not installed.

======================================================================
ERROR: Test sdp var.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/tests/test_scs.py", line 87, in test_sdp_var
    prob.solve(verbose=True, solver=cvx.SCS)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 246, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 356, in _solve
    raise e
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 354, in _solve
    solver=solver)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/reductions/solvers/solving_chain.py", line 48, in construct_solving_chain
    raise SolverError("The solver %s is not installed." % solver)
cvxpy.error.SolverError: The solver SCS is not installed.

======================================================================
ERROR: Test sigma_max.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/tests/test_scs.py", line 77, in test_sigma_max
    result = prob.solve(solver=cvx.SCS)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 246, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 356, in _solve
    raise e
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 354, in _solve
    solver=solver)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/reductions/solvers/solving_chain.py", line 48, in construct_solving_chain
    raise SolverError("The solver %s is not installed." % solver)
cvxpy.error.SolverError: The solver SCS is not installed.

======================================================================
ERROR: Test warm starting.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/tests/test_scs.py", line 183, in test_warm_start
    result = prob.solve(solver=cvx.SCS, eps=1e-4)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 246, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 356, in _solve
    raise e
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 354, in _solve
    solver=solver)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/reductions/solvers/solving_chain.py", line 48, in construct_solving_chain
    raise SolverError("The solver %s is not installed." % solver)
cvxpy.error.SolverError: The solver SCS is not installed.

======================================================================
ERROR: Test that all the SCS solver options work.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/tests/test_solvers.py", line 95, in test_scs_options
    verbose=True, normalize=True, use_indirect=False)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 246, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 356, in _solve
    raise e
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 354, in _solve
    solver=solver)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/reductions/solvers/solving_chain.py", line 48, in construct_solving_chain
    raise SolverError("The solver %s is not installed." % solver)
cvxpy.error.SolverError: The solver SCS is not installed.
```

**Comment by SteveDiamond** [comment]
I updated the install instructions to match the build instructions.

**Comment by Kabongosalomon** [comment]
> conda install -c cvxgrp --yes ecos scs multiprocess
> python setup.py install

python: can't open file 'setup.py': [Errno 2] No such file or directory
