### ISSUE TITLE
Mosek _Task_library error with cvxpy 1.0.3 and Mosek 8.1.53

### ISSUE THREAD

**Issue by eckara** [cvxgrp/cvxpy#497]
Running the tsp_mip.py [example](https://github.com/cvxgrp/cvxpy/examples/tsp_mip.py ) suggests MOSEK interface errors.

`  
Integer solution solution summary
  Problem status  : PRIMAL_FEASIBLE
  Solution status : INTEGER_OPTIMAL
  Primal.  obj: 1.6386400651e+00    nrm: 5e+00    Viol.  con: 0e+00    var: 0e+00    itg: 0e+00  
Traceback (most recent call last):
  File "tsp_mip.py", line 51, in <module>
    prob.solve(verbose=True)
  File "/usr/local/lib/python2.7/dist-packages/cvxpy/problems/problem.py", line 246, in solve
    return solve_func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cvxpy/problems/problem.py", line 361, in _solve
    self.unpack_results(solution, self._solving_chain, inverse_data)
  File "/usr/local/lib/python2.7/dist-packages/cvxpy/problems/problem.py", line 453, in unpack_results
    solution = chain.invert(solution, inverse_data)
  File "/usr/local/lib/python2.7/dist-packages/cvxpy/reductions/chain.py", line 66, in invert
    solution = r.invert(solution, inv)
  File "/usr/local/lib/python2.7/dist-packages/cvxpy/reductions/solvers/conic_solvers/mosek_conif.py", line 460, in invert
    task.getprosta(sol)  # mosek "problem status"; unused.
  File "/root/.local/lib/python2.7/site-packages/mosek/__init__.py", line 142, in accept
    return fun(*[ t(a) for (t,a) in zip(argtlst,args) ])
  File "/root/.local/lib/python2.7/site-packages/mosek/__init__.py", line 37, in sync
    return f(self,*args,**kwds)
  File "/root/.local/lib/python2.7/site-packages/mosek/__init__.py", line 5310, in getprosta
    _,msg = self.__getlasterror(res)
  File "/root/.local/lib/python2.7/site-packages/mosek/__init__.py", line 37, in sync
    return f(self,*args,**kwds)
  File "/root/.local/lib/python2.7/site-packages/mosek/__init__.py", line 2237, in __getlasterror
    r = self.__library.MSK_XX_getlasterror64(self.__nativep, ctypes.byref(lasterr), 0, ctypes.byref(msglen),None)
AttributeError: Task instance has no attribute '_Task__library'

`

**Comment by rileyjmurray** [comment]
It looks like the error is occurring in mosek's python interface. The last call from within cvxpy was `task.getprosta(sol)`, which returns an integer from a mosek enum that cvxpy does not use. There's a chance that we're passing malformed input to the `getprosta` function, but I think that's unlikely.

I will investigate in greater detail in the next couple days. In the meantime, please update your MOSEK Python package, or consider running this example again in a separate virtual environment.

**Comment by eckara** [comment]
Thanks @rileyjmurray! 
Just did a seperate virtual environment on an opensuse machine, same issue: ECOS is fine, MOSEK gives the same error.

**Comment by miggy2129** [comment]
I'm also getting a similar error when running MOSEK 8.1 in CVXPY. I'll attach the image below. Aside from getprosta, I'm getting the same error from getsolsta.

<img width="581" alt="screen-shot-2018-05-22-at-1 12 28-pm" src="https://user-images.githubusercontent.com/38098216/40398134-ffbe4e42-5e68-11e8-8b7a-0da2fa1fe7ec.png">

**Comment by aszekMosek** [comment]
In ``solve_via_data`` the task object is created using a ``with`` clause and then returned in a ``return`` statement within that clause. I'm no expert here, but I think this may lead to the destructor of ``task`` being called, which is the usual source of errors that look like this (they suggest the task object has been cleaned up).

**Comment by rileyjmurray** [comment]
@aszekMosek that sounds eminently reasonable! I will make appropriate changes and post here with the results.

**Comment by miggy2129** [comment]
Great! It works perfectly on my problem now also! Thanks!
