### ISSUE TITLE
Pythonn 3.5 (Anaconda 4.1.1) - Error version numpy installation

### ISSUE THREAD

**Issue by JulienNic0las** [cvxgrp/cvxpy#501]
Hi,

I'm trying to install `cvxpy` on a Windows machine with Anaconda. I tried to run the recommended command from the documention `conda install -c cvxgrp cvxpy`, however I got an error when it came to build the ECOS wheel. Indeed I do not have Visual C++. As I am not adminstrator and thereby can't install what I want  I looked for a prebuilt wheel that I found here [https://www.lfd.uci.edu/~gohlke/pythonlibs/#ecos](url).

I succeeded to install `cvxpy` with various methods:

- Using the version proposed on the site described above
- Using `pip install cvxpy`
- Using `conda install -c cvxgrp cvxpy`

However when I try to import the module I have the following error message:

Traceback (most recent call last):
  File "C:\users-apps\Anaconda3\lib\site-packages\cvxpy\cvxcore\python\cvxcore.py", line 18, in swig
_import_helper
    fp, pathname, description = imp.find_module('_cvxcore', [dirname(__file__)])
  File "C:\users-apps\Anaconda3\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_cvxcore'

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
Traceback (most recent call last):
  File "C:\users-apps\Anaconda3\lib\site-packages\cvxpy\cvxcore\python\cvxcore.py", line 18, in swig
_import_helper
    fp, pathname, description = imp.find_module('_cvxcore', [dirname(__file__)])
  File "C:\users-apps\Anaconda3\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_cvxcore'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\users-apps\Anaconda3\lib\site-packages\cvxpy\__init__.py", line 21, in <module>
    from cvxpy.atoms import *
  File "C:\users-apps\Anaconda3\lib\site-packages\cvxpy\atoms\__init__.py", line 20, in <module>
    from cvxpy.atoms.geo_mean import geo_mean
  File "C:\users-apps\Anaconda3\lib\site-packages\cvxpy\atoms\geo_mean.py", line 23, in <module>
    from cvxpy.utilities.power_tools import (fracify, decompose, approx_error, lower_bound,
  File "C:\users-apps\Anaconda3\lib\site-packages\cvxpy\utilities\power_tools.py", line 21, in <modu
le>
    from cvxpy.atoms.affine.reshape import reshape
  File "C:\users-apps\Anaconda3\lib\site-packages\cvxpy\atoms\affine\reshape.py", line 20, in <modul
e>
    from cvxpy.atoms.affine.affine_atom import AffAtom
  File "C:\users-apps\Anaconda3\lib\site-packages\cvxpy\atoms\affine\affine_atom.py", line 25, in <m
odule>
    from cvxpy.cvxcore.python import canonInterface
  File "C:\users-apps\Anaconda3\lib\site-packages\cvxpy\cvxcore\python\canonInterface.py", line 32,
in <module>
    import cvxpy.cvxcore.python.cvxcore as cvxcore
  File "C:\users-apps\Anaconda3\lib\site-packages\cvxpy\cvxcore\python\cvxcore.py", line 28, in <mod
ule>
    _cvxcore = swig_import_helper()
  File "C:\users-apps\Anaconda3\lib\site-packages\cvxpy\cvxcore\python\cvxcore.py", line 20, in swig
_import_helper
    import _cvxcore
ImportError: numpy.core.multiarray failed to import

I am not an expert but it seems that `numpy` is the origin of the issue. The version I have is 1.11.3. I installed `cvxpy` version 1.03. The way I installed ECOS is likely the problem. 

So, is there a way to install `cvxpy` on Windows without having the compile something myself with Visual C++ ? 

Many thanks in advance,

Julien

**Comment by JulienNic0las** [comment]
Ok.. It appears that I messed something with the different version of Python I have. After a clean re-installation, everything went smooth. So I guess my previous ticket is no longer necessary.

Sorry for the inconvenience.
J
