### ISSUE TITLE
ImportError (numpy.core.multiarray failed to import)

### ISSUE THREAD

**Issue by pnystrup** [cvxgrp/cvxpy#504]
I updated cvxpy to 1.0.1 on Windows 10 using Anaconda. When I run nosetests cvxpy I get an error: RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
E
======================================================================
ERROR: Failure: ImportError (numpy.core.multiarray failed to import)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Peter\Anaconda\lib\site-packages\nose\loader.py", line 407, in loadTestsFromName
    module = resolve_name(addr.module)
  File "C:\Users\Peter\Anaconda\lib\site-packages\nose\util.py", line 312, in resolve_name
    module = __import__('.'.join(parts_copy))
  File "C:\Users\Peter\Anaconda\lib\site-packages\cvxpy\__init__.py", line 21, in <module>
    from cvxpy.atoms import *
  File "C:\Users\Peter\Anaconda\lib\site-packages\cvxpy\atoms\__init__.py", line 20, in <module>
    from cvxpy.atoms.geo_mean import geo_mean
  File "C:\Users\Peter\Anaconda\lib\site-packages\cvxpy\atoms\geo_mean.py", line 23, in <module>
    from cvxpy.utilities.power_tools import (fracify, decompose, approx_error, lower_bound,
  File "C:\Users\Peter\Anaconda\lib\site-packages\cvxpy\utilities\power_tools.py", line 21, in <module>
    from cvxpy.atoms.affine.reshape import reshape
  File "C:\Users\Peter\Anaconda\lib\site-packages\cvxpy\atoms\affine\reshape.py", line 20, in <module>
    from cvxpy.atoms.affine.affine_atom import AffAtom
  File "C:\Users\Peter\Anaconda\lib\site-packages\cvxpy\atoms\affine\affine_atom.py", line 25, in <module>
    from cvxpy.cvxcore.python import canonInterface
  File "C:\Users\Peter\Anaconda\lib\site-packages\cvxpy\cvxcore\python\canonInterface.py", line 32, in <module>
    import cvxpy.cvxcore.python.cvxcore as cvxcore
  File "C:\Users\Peter\Anaconda\lib\site-packages\cvxpy\cvxcore\python\cvxcore.py", line 28, in <module>
    _cvxcore = swig_import_helper()
  File "C:\Users\Peter\Anaconda\lib\site-packages\cvxpy\cvxcore\python\cvxcore.py", line 20, in swig_import_helper
    import _cvxcore
ImportError: numpy.core.multiarray failed to import

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)

Any ideas for how I can get cvxpy working again? Import CVXcanon doesn't give an error and I have numpy 1.12.1 installed.

**Comment by pnystrup** [comment]
Seems to work now that I upgraded numpy to 1.14.3. Conda install wouldn't upgrade numpy because scs depends on numpy 1.12, so I had to force the upgrade using pip install.

**Comment by SteveDiamond** [comment]
Ok that's odd. Are you saying that it is impossible with conda on Windows to install SCS and any version of NumPy higher than 1.12?

**Comment by pnystrup** [comment]
Yes, I had to force it with pip install, but then SCS didn't work. So I ended up doing a handful of uninstall/reinstalls before getting it to work with a 32-bit version of Conda and doing pip install cvxpy.

**Comment by SteveDiamond** [comment]
@rileyjmurray this might be the key to getting conda working on Windows. It could just be a mistake in the SCS package dependencies (something like NumPy == 1.12).

**Comment by pnystrup** [comment]
It works fine with pip install, but not with conda install.

**Comment by SteveDiamond** [comment]
This should be fixed, as much as possible.
