### ISSUE TITLE
Error when solving: TypeError: in method 'IntVector_push_back'

### ISSUE THREAD

**Issue by wrossmorrow** [cvxgrp/cvxpy#507]
I am getting an error 

    TypeError: in method 'IntVector_push_back', argument 2 of type 'std::vector< int >::value_type'

when trying to run `CVXPy` on a relatively simple problem. I saw at least one thread from the past about this error in the Google Group, but no information there about what it is or (really) how to fix it. 

I've installed with both `conda` and `pip`. Here is the result of `conda` list: 

    $conda list | sed -n '/cvx/p'
    cvxcanon                  0.1.1            py36ha6ddfb2_0  
    cvxpy                     0.4.9                    py36_0    cvxgrp
    ecos                      2.0.5            py36hf9b3073_0    cvxgrp
    ...

My problem is basically 

    def objective_fcn( A , YX , p , Lambda ):
        return sum( cp.logistic( YX * p ) ) + Lambda * cp.norm( p[A:] , 1 )
    p = cp.Variable( Nvars )
    constraints = [ S * p == zeros ]
    Lambda = cp.Parameter( sign="positive" )
    prob = cp.Problem( cp.Minimize( objective_fcn(A,YX,p,Lambda) ) , constraints )

where `YX` and `S` are `scipy.sparse.coo_matrix` objects. 

This has worked in the past. It actually worked right away a couple weeks ago. I am revisiting my problem after cleaning the data a bit and generalizing the "wrapper" code around my problem, and getting this error. 

Here is the full error: 

```
Traceback (most recent call last):
  File "idLogit.py", line 232, in <module>
    actual_run( L )
  File "idLogit.py", line 222, in actual_run
    betas , delta , loglk , success = trace_idLogit( I , A , N , inds , LR , y )
  File "idLogit.py", line 166, in trace_idLogit
    prob.solve( warm_start = True )
  File "/Users/morrowwr/anaconda/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 209, in solve
    return self._solve(*args, **kwargs)
  File "/Users/morrowwr/anaconda/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 331, in _solve
    kwargs)
  File "/Users/morrowwr/anaconda/lib/python3.6/site-packages/cvxpy/problems/solvers/ecos_intf.py", line 118, in solve
    data = self.get_problem_data(objective, constraints, cached_data)
  File "/Users/morrowwr/anaconda/lib/python3.6/site-packages/cvxpy/problems/solvers/solver.py", line 246, in get_problem_data
    cached_data)
  File "/Users/morrowwr/anaconda/lib/python3.6/site-packages/cvxpy/problems/solvers/solver.py", line 224, in get_matrix_data
    self.nonlin_constr())
  File "/Users/morrowwr/anaconda/lib/python3.6/site-packages/cvxpy/problems/problem_data/matrix_data.py", line 90, in __init__
    self._lin_matrix(self.ineq_cache, caching=True)
  File "/Users/morrowwr/anaconda/lib/python3.6/site-packages/cvxpy/problems/problem_data/matrix_data.py", line 181, in _lin_matrix
    constr_offsets
  File "/Users/morrowwr/anaconda/lib/python3.6/site-packages/canonInterface.py", line 52, in get_problem_matrix
    tree = build_lin_op_tree(lin, tmp)
  File "/Users/morrowwr/anaconda/lib/python3.6/site-packages/canonInterface.py", line 229, in build_lin_op_tree
    set_slice_data(linC, linPy)
  File "/Users/morrowwr/anaconda/lib/python3.6/site-packages/canonInterface.py", line 151, in set_slice_data
    vec.push_back(var)
  File "/Users/morrowwr/anaconda/lib/python3.6/site-packages/CVXcanon.py", line 426, in push_back
    return _CVXcanon.IntVector_push_back(self, x)
TypeError: in method 'IntVector_push_back', argument 2 of type 'std::vector< int >::value_type'
```

**Comment by SteveDiamond** [comment]
We only support CVXPY 1.0 and later now. For any older version of CVXPY, you'll need to solve your own problems. Sorry to be harsh but I don't want a Python 2 vs 3 situation!

**Comment by wrossmorrow** [comment]
That is definitely a problem... I'm embarrassed to have missed the old version. Although, I do wonder how this got installed, as I have (thought I have) followed the online instructions.
