### ISSUE TITLE
CVXPY failed to work on Mac OS with Anaconda

### ISSUE THREAD

**Issue by nxtruong** [cvxgrp/cvxpy#514]
I installed CVXPY (version: 1.0.5-py36_0) on Mac OS with Anaconda (configurations below), following the instructions on your website. The installation went smoothly. However when I tried to use CVXPY (`import cvxpy`) the following error occurred. I tried to remove CVXPY, clean up conda, and reinstall CVXPY, but the problem persisted. Testing the installation with nose resulted in the same error.

The error message:
```
Traceback (most recent call last):
  File "/Users/truong/miniconda3/lib/python3.6/site-packages/cvxpy/cvxcore/python/cvxcore.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_cvxcore', [dirname(__file__)])
  File "/Users/truong/miniconda3/lib/python3.6/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_cvxcore'

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
Traceback (most recent call last):
  File "/Users/truong/miniconda3/lib/python3.6/site-packages/cvxpy/cvxcore/python/cvxcore.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_cvxcore', [dirname(__file__)])
  File "/Users/truong/miniconda3/lib/python3.6/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_cvxcore'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/truong/miniconda3/lib/python3.6/site-packages/cvxpy/__init__.py", line 21, in <module>
    from cvxpy.atoms import *
  File "/Users/truong/miniconda3/lib/python3.6/site-packages/cvxpy/atoms/__init__.py", line 20, in <module>
    from cvxpy.atoms.geo_mean import geo_mean
  File "/Users/truong/miniconda3/lib/python3.6/site-packages/cvxpy/atoms/geo_mean.py", line 23, in <module>
    from cvxpy.utilities.power_tools import (fracify, decompose, approx_error, lower_bound,
  File "/Users/truong/miniconda3/lib/python3.6/site-packages/cvxpy/utilities/power_tools.py", line 21, in <module>
    from cvxpy.atoms.affine.reshape import reshape
  File "/Users/truong/miniconda3/lib/python3.6/site-packages/cvxpy/atoms/affine/reshape.py", line 20, in <module>
    from cvxpy.atoms.affine.affine_atom import AffAtom
  File "/Users/truong/miniconda3/lib/python3.6/site-packages/cvxpy/atoms/affine/affine_atom.py", line 25, in <module>
    from cvxpy.cvxcore.python import canonInterface
  File "/Users/truong/miniconda3/lib/python3.6/site-packages/cvxpy/cvxcore/python/canonInterface.py", line 32, in <module>
    import cvxpy.cvxcore.python.cvxcore as cvxcore
  File "/Users/truong/miniconda3/lib/python3.6/site-packages/cvxpy/cvxcore/python/cvxcore.py", line 28, in <module>
    _cvxcore = swig_import_helper()
  File "/Users/truong/miniconda3/lib/python3.6/site-packages/cvxpy/cvxcore/python/cvxcore.py", line 20, in swig_import_helper
    import _cvxcore
ImportError: numpy.core.multiarray failed to import
```

Configuration:
Mac OS 10.13.4
Conda version 4.5.4
Python version 3.6.1
Numpy version 1.12.1
SciPy version 0.19.1

**Comment by rileyjmurray** [comment]
Initial observations:
* cvxpy requires numpy 1.13 or higher (although this should be taken care of when you do a conda install cvxpy)
* cvxpy's build for Python 3.6 on OSX is passing (https://travis-ci.org/cvxgrp/cvxpy/). Although the build is being conducted on a machine with OSX 10.9.

Replicating the issue:
* I created a new conda environment on my personal mac (OSX 10.10.5) with Python 3.6.
* I installed cvxpy via `conda install -c cvxgrp cvxpy`. The version installed was 1.0.5.
* I launched Python and tried to import cvxpy, resulting in an error just about identical to that reported by @nxtruong. See below for full text of the error.

```
(bug514) Rileys-MacBook-Pro:~ RJMurray$ python
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:44:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cvxpy
Traceback (most recent call last):
  File "/Users/RJMurray/anaconda2/envs/bug514/lib/python3.6/site-packages/cvxpy/cvxcore/python/cvxcore.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_cvxcore', [dirname(__file__)])
  File "/Users/RJMurray/anaconda2/envs/bug514/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_cvxcore'

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
Traceback (most recent call last):
  File "/Users/RJMurray/anaconda2/envs/bug514/lib/python3.6/site-packages/cvxpy/cvxcore/python/cvxcore.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_cvxcore', [dirname(__file__)])
  File "/Users/RJMurray/anaconda2/envs/bug514/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_cvxcore'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/RJMurray/anaconda2/envs/bug514/lib/python3.6/site-packages/cvxpy/__init__.py", line 21, in <module>
    from cvxpy.atoms import *
  File "/Users/RJMurray/anaconda2/envs/bug514/lib/python3.6/site-packages/cvxpy/atoms/__init__.py", line 20, in <module>
    from cvxpy.atoms.geo_mean import geo_mean
  File "/Users/RJMurray/anaconda2/envs/bug514/lib/python3.6/site-packages/cvxpy/atoms/geo_mean.py", line 23, in <module>
    from cvxpy.utilities.power_tools import (fracify, decompose, approx_error, lower_bound,
  File "/Users/RJMurray/anaconda2/envs/bug514/lib/python3.6/site-packages/cvxpy/utilities/power_tools.py", line 21, in <module>
    from cvxpy.atoms.affine.reshape import reshape
  File "/Users/RJMurray/anaconda2/envs/bug514/lib/python3.6/site-packages/cvxpy/atoms/affine/reshape.py", line 20, in <module>
    from cvxpy.atoms.affine.affine_atom import AffAtom
  File "/Users/RJMurray/anaconda2/envs/bug514/lib/python3.6/site-packages/cvxpy/atoms/affine/affine_atom.py", line 25, in <module>
    from cvxpy.cvxcore.python import canonInterface
  File "/Users/RJMurray/anaconda2/envs/bug514/lib/python3.6/site-packages/cvxpy/cvxcore/python/canonInterface.py", line 32, in <module>
    import cvxpy.cvxcore.python.cvxcore as cvxcore
  File "/Users/RJMurray/anaconda2/envs/bug514/lib/python3.6/site-packages/cvxpy/cvxcore/python/cvxcore.py", line 28, in <module>
    _cvxcore = swig_import_helper()
  File "/Users/RJMurray/anaconda2/envs/bug514/lib/python3.6/site-packages/cvxpy/cvxcore/python/cvxcore.py", line 20, in swig_import_helper
    import _cvxcore
ImportError: numpy.core.multiarray failed to import
>>> 
```

**Comment by rileyjmurray** [comment]
The issue #504 describes similar errors, but in Windows. Following the discussion in #504 I tried importing cvxpy after installing numpy version 1.14. The output below shows that this succeeds.

```
(cvxpy1dev) Rileys-MacBook-Pro:research RJMurray$ source activate bug514
(bug514) Rileys-MacBook-Pro:research RJMurray$ conda install numpy=1.14
Solving environment: done

Please update conda by running

    $ conda update -n base conda

## Package Plan ##

  environment location: /Users/RJMurray/anaconda2/envs/bug514

  added / updated specs: 
    - numpy=1.14

The following packages will be UPDATED:

    blas:  1.0-mkl            --> 1.1-openblas                          conda-forge
    numpy: 1.13.1-py36_0      --> 1.14.4-py36_blas_openblash24bf2e0_200 conda-forge [blas_openblas]
    scipy: 0.19.1-np113py36_0 --> 1.1.0-py36_blas_openblas_200          conda-forge [blas_openblas]

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(bug514) Rileys-MacBook-Pro:research RJMurray$ python

Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:44:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cvxpy
>>> print(cvxpy.__version__)
1.0.5
```

Moreover, unlike in #504, SCS still worked (at least on a minimal example).

```
>>> x = cvxpy.Variable((5,1))
>>> constrs = [x >= 0, cvxpy.sum(x) == 1]
>>> obj = cvxpy.Minimize(cvxpy.sum(x))
>>> prob = cvxpy.Problem(obj, constrs)
>>> prob.solve(solver='SCS', verbose=True)
----------------------------------------------------------------------------
        SCS v1.2.6 - Splitting Conic Solver
        (c) Brendan O'Donoghue, Stanford University, 2012-2016
----------------------------------------------------------------------------
Lin-sys: sparse-indirect, nnz in A = 10, CG tol ~ 1/iter^(2.00)
eps = 1.00e-03, alpha = 1.50, max_iters = 2500, normalize = 1, scale = 1.00
Variables n = 5, constraints m = 6
Cones:  primal zero / dual free vars: 1
        linear vars: 5
Setup time: 2.19e-04s
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
     0| 1.77e-01  8.08e+15  1.00e+00  1.22e+00  1.17e+16  1.00e+00  2.33e-04 
    20| 1.44e-04  6.07e-04  2.06e-04  1.00e+00  9.99e-01  6.41e-17  2.98e-04 
----------------------------------------------------------------------------
Status: Solved
Timing: Solve time: 3.19e-04s
        Lin-sys: avg # CG iterations: 1.00, avg solve time: 5.49e-07s
        Cones: avg projection time: 5.33e-08s
----------------------------------------------------------------------------
Error metrics:
dist(s, K) = 6.4064e-17, dist(y, K*) = 0.0000e+00, s'y/|s||y| = -1.4333e-16
|Ax + s - b|_2 / (1 + |b|_2) = 1.4380e-04
|A'y + c|_2 / (1 + |c|_2) = 6.0674e-04
|c'x + b'y| / (1 + |c'x| + |b'y|) = 2.0641e-04
----------------------------------------------------------------------------
c'x = 0.9997, -b'y = 0.9991
============================================================================
0.9997409080102019
>>> 
```

**Comment by nxtruong** [comment]
After updating `numpy` (and fixing some issues with MOSEK), CVXPY can be imported successfully. However, there are quite a few errors running `notetests cvxpy`, but that's irrelevant to this issue, which can be closed now. Thanks!

**Comment by SteveDiamond** [comment]
Ok, so is the message that we need to update the cvxpy dependencies to numpy >= 1.14?

**Comment by nxtruong** [comment]
@SteveDiamond  Yes, I think so. Though I haven't tested which version is the minimum requirement.

**Comment by Travis-S** [comment]
Ran into this issue as well. Setting numpy = 1.15 worked. As @nxtruong noted, some of the tests didn't pass.

**Comment by zhangJianfeng** [comment]
@nxtruong , I have the same error message as you post above. The numpy version is higher that 1.14. I have tried to re-install the cvxpy, but it doesn't work..

The configuration is as follows:
numpy: 1.15.4
python: 3.7.1
OS: Ubuntu 16.04

**Comment by noahbjohnson** [comment]
@zhangJianfeng Working for me on 
numpy 1.16.3 
Python 3.7.1
Ubuntu 16LTS and 18LTS

**Comment by SteveDiamond** [comment]
Anyone on this thread, please keep us updated with Anaconda issues, we're trying to improve things. We're now recommending installing with pip, which you can do within anaconda (just pip install cvxpy). But we want Anaconda installation to work as well.

**Comment by yvonneyang1** [comment]
The same issue for the configuration is:
numpy: 1.16.4
python: 3.6
OS: Windows

**Comment by jarthurgross** [comment]
Had a similar problem installing `cvxpy` on Mac 10.14.5 using Anaconda, with numpy version `1.15.4` and Python version `3.7.1`. Seemed like it installed OK initially:
```
conda install -c cvxgrp cvxpy=1.0.24
WARNING conda.base.context:use_only_tar_bz2(632): Conda is constrained to only using the old .tar.bz2 file format because you have conda-build installed, and it is <3.18.3.  Update or remove conda-build to get smaller downloads and faster extractions.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/user_name/anaconda3

  added / updated specs:
    - cvxpy=1.0.24


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cvxpy-1.0.24               |           py37_0         679 KB  cvxgrp
    dill-0.3.0                 |           py37_0         113 KB  conda-forge
    ecos-2.0.7                 |py37h917ab60_1000          84 KB  conda-forge
    libgcc-4.8.5               |      hdbeacc1_10         302 KB  conda-forge
    multiprocess-0.70.8        |   py37h01d97ff_0         183 KB  conda-forge
    osqp-0.5.0                 |   py37h1d22016_1         156 KB  oxfordcontrol
    scs-2.0.2                  |py37h312d94d_1000          87 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         1.6 MB

The following NEW packages will be INSTALLED:

  cvxpy              cvxgrp/osx-64::cvxpy-1.0.24-py37_0
  dill               conda-forge/osx-64::dill-0.3.0-py37_0
  ecos               conda-forge/osx-64::ecos-2.0.7-py37h917ab60_1000
  libgcc             conda-forge/osx-64::libgcc-4.8.5-hdbeacc1_10
  multiprocess       conda-forge/osx-64::multiprocess-0.70.8-py37h01d97ff_0
  openblas           conda-forge/osx-64::openblas-0.3.3-hdc02c5d_1001
  osqp               oxfordcontrol/osx-64::osqp-0.5.0-py37h1d22016_1
  scs                conda-forge/osx-64::scs-2.0.2-py37h312d94d_1000


Proceed ([y]/n)? y


Downloading and Extracting Packages
osqp-0.5.0           | 156 KB    | ################################################################################################################## | 100% 
cvxpy-1.0.24         | 679 KB    | ################################################################################################################## | 100% 
ecos-2.0.7           | 84 KB     | ################################################################################################################## | 100% 
multiprocess-0.70.8  | 183 KB    | ################################################################################################################## | 100% 
dill-0.3.0           | 113 KB    | ################################################################################################################## | 100% 
scs-2.0.2            | 87 KB     | ################################################################################################################## | 100% 
libgcc-4.8.5         | 302 KB    | ################################################################################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
but when trying to import it in a jupyter notebook, I got an 
```
ImportError: No module named '_cvxcore'
```
error and something about `numpy.core._multiarray_umath` or something similar. Doing `conda remove cvxpy` and then `pip install cvxpy` fixed the problem.
