### ISSUE TITLE
Parallel test fails on Python 2.7

### ISSUE THREAD

**Issue by mcg1969** [cvxgrp/cvxpy#537]
The unit test fails, but here's a smaller reproducible script:
```
from cvxpy import Minimize, square
from cvxpy.expressions.constants import Parameter
from cvxpy.expressions.variable import Variable
from cvxpy.problems.problem import Problem
a = Variable(name='a')
b = Variable(name='b')
p = Parameter()
problem = Problem(Minimize(square(a) + square(b) + p),
                  [b >= 2, a >= 1])
p.value = 1
problem.solve(parallel=True)
```
On 3.6 it successfully returns `6.0`; on 2.7, I get this:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/builder/miniconda3/envs/cvxtest/lib/python2.7/site-packages/cvxpy/problems/problem.py", line 246, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/builder/miniconda3/envs/cvxtest/lib/python2.7/site-packages/cvxpy/problems/problem.py", line 344, in _solve
    verbose, **kwargs)
  File "/home/builder/miniconda3/envs/cvxtest/lib/python2.7/site-packages/cvxpy/problems/problem.py", line 411, in _parallel_solve
    solve_results = pool.map(_solve_problem, self._separable_problems)
  File "/home/builder/miniconda3/envs/cvxtest/lib/python2.7/site-packages/multiprocess/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/builder/miniconda3/envs/cvxtest/lib/python2.7/site-packages/multiprocess/pool.py", line 567, in get
    raise self._value
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
```
This is with `multiprocess 0.70.5` on Linux. Any ideas?

**Comment by mcg1969** [comment]
Just tested with `0.70.6.1` as well, same issue.

**Comment by rileyjmurray** [comment]
Environment info: Linux (RHEL 7), Python 2.7, cvxpy 1.0.6, multiprocess 0.70.5.

When I run @mcg1969 's example with SCS or ECOS, it succeeds:
```
Python 2.7.15 | packaged by conda-forge | (default, May  8 2018, 14:46:53) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from cvxpy import Minimize, square
>>> from cvxpy.expressions.constants import Parameter
>>> from cvxpy.expressions.variable import Variable
>>> from cvxpy.problems.problem import Problem
>>> a = Variable(name='a')
>>> b = Variable(name='b')
>>> p = Parameter()
>>> problem = Problem(Minimize(square(a) + square(b) + p),
...                   [b >= 2, a >= 1])
>>> p.value = 1
>>> problem.solve(solver='ECOS',parallel=True)
'5.999999959733015'
problem.solve(solver='SCS',parallel=True)
'5.997457898765897'
```
When I run it with Gurobi, it fails
```
problem.solve(solver='GUROBI',parallel=True)
Exception in thread Thread-18:
Traceback (most recent call last):
  File "/home/rmurray/anaconda2/envs/dev27/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/rmurray/anaconda2/envs/dev27/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/rmurray/anaconda2/envs/dev27/lib/python2.7/site-packages/multiprocess/pool.py", line 389, in _handle_results
    task = get()
  File "/home/rmurray/anaconda2/envs/dev27/lib/python2.7/site-packages/dill/dill.py", line 299, in loads
    return load(file)
  File "/home/rmurray/anaconda2/envs/dev27/lib/python2.7/site-packages/dill/dill.py", line 288, in load
    obj = pik.load()
  File "/home/rmurray/anaconda2/envs/dev27/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/home/rmurray/anaconda2/envs/dev27/lib/python2.7/pickle.py", line 1139, in load_reduce
    value = func(*args)
  File "exception.pxi", line 11, in gurobipy.GurobiError.__init__ (../../src/python/gurobipy.c:98113)
TypeError: __init__() takes exactly 3 positional arguments (1 given)


```
but it seems to fail for reasons distinct from those @mcg1969 experienced.

**Comment by akshayka** [comment]
@mcg1969 's MWE also fails on Python 3.7, Mac OS X:

```python
~/projects/cvxpy/cvxpy/problems/problem.py in _parallel_solve(self, solver, warm_start, verbose, **kwargs)
    599
    600         pool = multiprocessing.Pool(processes=multiprocessing.cpu_count())
--> 601         solve_results = pool.map(_solve_problem, self._separable_problems)
    602         pool.close()
    603         pool.join()

...

/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    522             reduce = getattr(obj, "__reduce_ex__", None)
    523             if reduce is not None:
--> 524                 rv = reduce(self.proto)
    525             else:
    526                 reduce = getattr(obj, "__reduce__", None)

TypeError: can't pickle PyCapsule objects
```

The unit test `cvxpy.tests.test_problem.TestProblem` fails as well, with

```python
TypeError: can't pickle PyCapsule objects
```

Does anyone use the `parallel=True` flag? I'm somewhat inclined to deprecate it and remove it in the next minor release (1.1.0). The `multiprocess` package doesn't seem to be very actively maintained, and the code won't work with the standard `multiprocessing` package because the `map` serializes objects that can't be Pickle'd.

**Comment by SteveDiamond** [comment]
@akshayka This was a fun feature to put in talks, but it doesn't seem to have gained much steam.

**Comment by akshayka** [comment]
@SteveDiamond Okay, perhaps we should deprecate it and stop running tests against it, even if we don't delete it. We might have some similar work land sometime this year anyway (specifically, something like [Epsilon](https://arxiv.org/pdf/1511.04815.pdf) ...).

**Comment by SteveDiamond** [comment]
The parallel=True stuff will be out in 1.1.
