### ISSUE TITLE
pnorm compile errors when axis=1

### ISSUE THREAD

**Issue by rileyjmurray** [cvxgrp/cvxpy#633]
The following code suggests that the "axis" option for cvxpy's pnorm atom may not be working properly. What appears to be a valid problem
```
import numpy as np
import cvxpy
b = np.random.rand(2)
X = cvxpy.Variable(shape=(2, 10))
expr = cvxpy.pnorm(X, p=2, axis=1) - b
con = [expr <= 0]
obj = cvxpy.Minimize(0)
prob = cvxpy.Problem(obj, con)
```
exhibits the following error at compile time
```
prob.solve(solver='ECOS')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/rmurray/anaconda2/envs/dev36/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 247, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/rmurray/anaconda2/envs/dev36/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 359, in _solve
    data, inverse_data = self._solving_chain.apply(self)
  File "/home/rmurray/anaconda2/envs/dev36/lib/python3.6/site-packages/cvxpy/reductions/chain.py", line 58, in apply
    problem, inv = r.apply(problem)
  File "/home/rmurray/anaconda2/envs/dev36/lib/python3.6/site-packages/cvxpy/reductions/solvers/conic_solvers/ecos_conif.py", line 109, in apply
    problem, neq_constr, ECOS.EXP_CONE_ORDER)
  File "/home/rmurray/anaconda2/envs/dev36/lib/python3.6/site-packages/cvxpy/reductions/solvers/conic_solvers/conic_solver.py", line 261, in group_coeff_offset
    coeff, offset = self.format_constr(problem, cons, exp_cone_order)
  File "/home/rmurray/anaconda2/envs/dev36/lib/python3.6/site-packages/cvxpy/reductions/solvers/conic_solvers/conic_solver.py", line 228, in format_constr
    offset[i*gap+1:(i+1)*gap] = offsets[1][i::gap-1]
ValueError: could not broadcast input array from shape (2) into shape (10)
```

For reference, if I use axis=0, then the corresponding problem (now with ``b`` as a vector of length 10) behaves normally at solve-time.
```
import numpy as np
import cvxpy
b = np.random.rand(10)
X = cvxpy.Variable(shape=(2, 10))
expr = cvxpy.pnorm(X, p=2, axis=0) - b
con = [expr <= 0]
obj = cvxpy.Minimize(0)
prob = cvxpy.Problem(obj, con)
prob.solve(solver='ECOS')
0.0
```

Finally, I looked at the cvxpy's tests for the pnorm atom, and there is no test with axis != 0.
https://github.com/cvxgrp/cvxpy/blob/16ad9adad944d4cb34275e2f7dd0e27788b47b18/cvxpy/tests/test_atoms.py#L171

A simple work-around would be for ``cvxpy.pnorm`` to transpose the input data whenever ``axis=1``, however this will not generalize to Expressions with ``ndim > 2`` (such Expressions are not yet allowed in cvxpy, but there is a definite desire for them).

**Comment by SteveDiamond** [comment]
I believe this is fixed now.
