### ISSUE TITLE
Broadcast Array Error

### ISSUE THREAD

**Issue by arose13** [cvxgrp/cvxpy#647]
I'm getting a very strange broadcast array error for a model and cost function I know is correct (when I test it in NumPy).

Code required to reproduce the error
```
import numpy as np
import cvxpy as cvx
from scipy import stats

print(cvx.__version__)


def vec_to_array(vector: np.ndarray) -> np.ndarray:
    return vector.reshape((len(vector), 1))


def check_properties(obj, name=''):
    print(name, f'DCP {obj.is_dcp()}', f'Convexity {obj.is_convex()}')


def y_hat(beta_0, theta_0, beta, theta, x, z):  # Confirmed DCP and Convex
    n = x.shape[0]
    p = x.shape[1]
    k = z.shape[1]
    print(f'n {n}, p {p}, k {k}')

    intercepts = beta_0 + (z @ theta_0)

    shared_model = x @ beta

    pliables = np.zeros(n)
    for j_i in range(p):
        x_j = np.tile(vec_to_array(x[:, j_i]), (1, k))
        # sum_term = cvx.matmul((x_j * z), theta[j_i, :])
        sum_term = (x_j * z) @ theta[j_i, :]
        pliables = pliables + sum_term

    output = intercepts + shared_model + pliables
    return output


def j(beta_0, theta_0, beta, theta, x, y, z, lam):
    n = x.shape[0]
    p = x.shape[1]

    mse = (0.5 * n) * cvx.norm(y - y_hat(beta_0, theta_0, beta, theta, x, z), p=2) ** 2

    beta_matrix = cvx.reshape(beta, (p, 1))
    penalty_1 = cvx.sum(cvx.norm(cvx.hstack([beta_matrix, theta]), p=2, axis=1))
    penalty_2 = cvx.sum(cvx.norm(theta, p=2, axis=1))
    penalty_3 = cvx.sum(cvx.norm(theta, p=1))

    penalty_a = lam * (penalty_1 + penalty_2)
    penalty_b = lam * penalty_3

    loss = mse + penalty_a + penalty_b
    check_properties(loss, 'loss')
    return loss


if __name__ == '__main__':
    # Fake data
    n = 100
    p = 50
    k = 4

    beta_true = np.zeros(p)
    beta_true[:4] = [2, -2, 2, 2]
    print(beta_true)

    data = stats.norm().rvs(size=(n, p))

    beta_true = np.zeros(p)
    beta_true[:4] = [2, -2, 2, 2]

    z_true = stats.bernoulli(p=0.5).rvs(size=(n, k))
    print(z_true.shape)

    coefs = z_true.copy()
    coefs[:, 0] = beta_true[0]
    coefs[:, 1] = beta_true[1]
    coefs[:, 2] = beta_true[2] + 2 * z_true[:, 0]
    coefs[:, 3] = beta_true[3] * (1 - 2 * z_true[:, 1])
    print(coefs.shape)

    target = np.diag(data[:, :4] @ coefs.T) + stats.norm().rvs(n)
    print(target.shape)

    # Setup
    # Parameters
    beta_0 = cvx.Variable(1)
    theta_0 = cvx.Variable(k)
    beta = cvx.Variable(p)
    theta = cvx.Variable((p, k))

    print('beta_0', beta_0.shape)
    print('theta_0', theta_0.shape)
    print('beta', beta.shape)
    print('theta', theta.shape)
    print('=' * 20)

    # Hyperparameters
    lam = cvx.Parameter(nonneg=True, value=3.0)
    # lam.value = 3.0

    problem = cvx.Problem(
        cvx.Minimize(j(beta_0, theta_0, beta, theta, data, target, z_true, lam))
    )
    soln = problem.solve()
```

Calling the helper methods shows that the problem is both convex and follows DCP.

I get this falling error that I'm very sure much be a bug or error

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/antho/PycharmProjects/rosey/plasso.py", line 109, in <module>
    soln = problem.solve()
  File "C:\Users\antho\PycharmProjects\rosey\venv\lib\site-packages\cvxpy\problems\problem.py", line 268, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\Users\antho\PycharmProjects\rosey\venv\lib\site-packages\cvxpy\problems\problem.py", line 381, in _solve
    data, inverse_data = self._solving_chain.apply(self)
  File "C:\Users\antho\PycharmProjects\rosey\venv\lib\site-packages\cvxpy\reductions\chain.py", line 65, in apply
    problem, inv = r.apply(problem)
  File "C:\Users\antho\PycharmProjects\rosey\venv\lib\site-packages\cvxpy\reductions\solvers\conic_solvers\ecos_conif.py", line 109, in apply
    problem, neq_constr, ECOS.EXP_CONE_ORDER)
  File "C:\Users\antho\PycharmProjects\rosey\venv\lib\site-packages\cvxpy\reductions\solvers\conic_solvers\conic_solver.py", line 261, in group_coeff_offset
    coeff, offset = self.format_constr(problem, cons, exp_cone_order)
  File "C:\Users\antho\PycharmProjects\rosey\venv\lib\site-packages\cvxpy\reductions\solvers\conic_solvers\conic_solver.py", line 228, in format_constr
    offset[i*gap+1:(i+1)*gap] = offsets[1][i::gap-1]
ValueError: could not broadcast input array from shape (50) into shape (5)
```

I don't even know where an arrayof shape (5) could have come in, that's how confused I am 😢

**Comment by akshayka** [comment]
Thanks for reporting this, this is definitely a bug. 

@SteveDiamond, any idea what's could be going wrong here?

**Comment by rileyjmurray** [comment]
I’ve seen similar errors before. I think the problem comes from using certain cvxpy atoms with the “axis” option. There should be other posts about this in the GitHub issues.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akshayka** [comment]
Thanks @rileyjmurray, I found the related issue you filed (@633). We should definitely fix this ...

**Comment by SteveDiamond** [comment]
Can you pull the latest master and try again?

**Comment by arose13** [comment]
Yes I can, give me a few hours.

**Comment by arose13** [comment]
I don't know what you did but it works now! 😄

**Comment by SteveDiamond** [comment]
Great!

**Comment by aburabazam** [comment]
``
 File "/home/aburabazam/PycharmProjects/xsim/xsim/Node.py", line 172, in propagate_mpc
    self.problem.solve(verbose=False, solver=cvx.ECOS)
  File "/home/aburabazam/anaconda3/envs/heating/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 481, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/aburabazam/anaconda3/envs/heating/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 1008, in _solve
    data, solving_chain, inverse_data = self.get_problem_data(
  File "/home/aburabazam/anaconda3/envs/heating/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 639, in get_problem_data
    data, solver_inverse_data = solving_chain.solver.apply(
  File "/home/aburabazam/anaconda3/envs/heating/lib/python3.8/site-packages/cvxpy/reductions/solvers/conic_solvers/ecos_conif.py", line 113, in apply
    c, d, A, b = problem.apply_parameters()
  File "/home/aburabazam/anaconda3/envs/heating/lib/python3.8/site-packages/cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py", line 188, in apply_parameters
    param_vec = canonInterface.get_parameter_vector(
  File "/home/aburabazam/anaconda3/envs/heating/lib/python3.8/site-packages/cvxpy/cvxcore/python/canonInterface.py", line 59, in get_parameter_vector
    param_vec[col:col + size] = value

ValueError: could not broadcast input array from shape (93,) into shape (96,)
``
I also got this error after my Simulation with the MPC-Propagation was simulated for over 50 000 timesteps without problems.
The code to reproduce the error is quite heavy and works on parallel cores so I cannot provide it :(

**Comment by aburabazam** [comment]
``
 File "/home/aburabazam/PycharmProjects/xsim/xsim/Node.py", line 172, in propagate_mpc
    self.problem.solve(verbose=False, solver=cvx.ECOS)
  File "/home/aburabazam/anaconda3/envs/heating/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 481, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/aburabazam/anaconda3/envs/heating/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 1008, in _solve
    data, solving_chain, inverse_data = self.get_problem_data(
  File "/home/aburabazam/anaconda3/envs/heating/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 639, in get_problem_data
    data, solver_inverse_data = solving_chain.solver.apply(
  File "/home/aburabazam/anaconda3/envs/heating/lib/python3.8/site-packages/cvxpy/reductions/solvers/conic_solvers/ecos_conif.py", line 113, in apply
    c, d, A, b = problem.apply_parameters()
  File "/home/aburabazam/anaconda3/envs/heating/lib/python3.8/site-packages/cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py", line 188, in apply_parameters
    param_vec = canonInterface.get_parameter_vector(
  File "/home/aburabazam/anaconda3/envs/heating/lib/python3.8/site-packages/cvxpy/cvxcore/python/canonInterface.py", line 59, in get_parameter_vector
    param_vec[col:col + size] = value
ValueError: could not broadcast input array from shape (93,) into shape (96,)
``

Got this error after simulation with a MPC and 50 000 timesteps simulated without an error. Code is quite heavy because it runs with MPI and threading on different cores, but i think its the same Issue like above.

**Comment by SteveDiamond** [comment]
What version of cvxpy are you using?
