### ISSUE TITLE
CPLEX 102 (optimal problem but within tolerance) status raises Error

### ISSUE THREAD

**Issue by tarpalsus** [cvxgrp/cvxpy#676]
**Describe the bug**
Certain kind of data, which I am not allowed to share causes SolverError, while exactly the same problem is solved in Matlab using CPLEX binding.
I have checked CVXPY code for Cplex interfaces (e.g. CPLEX class in cplex_qpif) and found that they do not consider all possible CPLEX output statuses. There is even TODO attributed to mapping declaration. Mainly code 102 (optimal problem but within tolerance) is not implemented, which causes this crash.

**To Reproduce**
Certain kind of problem setup, which I am not allowed to share causes problem to be solved as optimal within tolerance. Maybe you can find some other problem setup that would cause this type of CPLEX status.

**Expected behavior**
102 code should return either s.OPTIMAL cvxpy status or some new status should be implemented.

**Output**
Traceback (most recent call last):

  File "<ipython-input-13-86dd2f02a64e>", line 1, in <module>
    runfile('C:/Users/kondrat/.spyder-py3/cvxpy_opt_module.py', wdir='C:/Users/kondrat/.spyder-py3')

  File "C:\Users\kondrat\AppData\Local\Continuum\anaconda3\envs\optimization\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "C:\Users\kondrat\AppData\Local\Continuum\anaconda3\envs\optimization\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/kondrat/.spyder-py3/cvxpy_opt_module.py", line 106, in <module>
    supply_comp, supply_current)

  File "C:/Users/kondrat/.spyder-py3/cvxpy_opt_module.py", line 26, in run_optimization
    status, opt_value, opt_x, opt_y = opt_solver.solve_problem()

  File "C:\Users\kondrat\.spyder-py3\optimization_solver.py", line 62, in solve_problem
    self.prob.solve(solver=solver, verbose=verbose, warm_start=False)

  File "C:\Users\kondrat\.spyder-py3\cvxpy\problems\problem.py", line 266, in solve
    return solve_func(self, *args, **kwargs)

  File "C:\Users\kondrat\.spyder-py3\cvxpy\problems\problem.py", line 382, in _solve
    self.unpack_results(solver_output, self._solving_chain, inverse_data)

  File "C:\Users\kondrat\.spyder-py3\cvxpy\problems\problem.py", line 519, in unpack_results
    "Try another solver or solve with verbose=True for more "

SolverError: Solver 'CPLEX' failed. Try another solver or solve with verbose=True for more information. Try recentering the problem data around 0 and rescaling to reduce the dynamic range.

**Version**
 - OS: Windows
 - CVXPY Version:  1.0.14

**Additional context**

**Comment by SteveDiamond** [comment]
I don't have CPLEX so I can't test this. Can you modify ``cplex_intf.py`` in a pull request so that status 102 is handled correctly?

**Comment by tarpalsus** [comment]
Sure I can modify that, but I believe that this should be changed in cplex_qpif.py. This is the file in which the status mapping from CPLEX to CVXPY is implemented. Could you confirm that this is true? Thanks!

**Comment by SteveDiamond** [comment]
It depends if you're solving a QP or a SOCP. I'm planning to rewrite cplex_intf.py, so hold off on editing that if you are solving an SOCP. Feel free to make a pull request for cplex_qpif.py.

**Comment by SteveDiamond** [comment]
I merged in your PR.
