### ISSUE TITLE
Serious installation problem.

### ISSUE THREAD

**Issue by SteveDiamond** [cvxgrp/cvxpy#677]
**Describe the bug**
The conda installation doesn't work with the latest conda. God knows what they changed, but the whole build is broken.

**To Reproduce**
Upgrade your conda, then run. 
```
      conda config --add channels conda-forge
      conda install -c cvxgrp cvxpy
      conda install nose
      nosetests cvxpy
```

**Expected behavior**
All the tests should pass (of course).

**Output**
```
Traceback (most recent call last):
  File "/Users/stevend2/PythonProjects/cvxpy/cvxpy/cvxcore/python/cvxcore.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_cvxcore', [dirname(__file__)])
  File "/Users/stevend2/anaconda/envs/tester/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_cvxcore'

During handling of the above exception, another exception occurred:

ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
E
======================================================================
ERROR: Failure: ImportError (numpy.core.multiarray failed to import)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/stevend2/PythonProjects/cvxpy/cvxpy/cvxcore/python/cvxcore.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_cvxcore', [dirname(__file__)])
  File "/Users/stevend2/anaconda/envs/tester/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_cvxcore'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stevend2/anaconda/envs/tester/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/stevend2/anaconda/envs/tester/lib/python3.7/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/stevend2/anaconda/envs/tester/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/stevend2/anaconda/envs/tester/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/stevend2/anaconda/envs/tester/lib/python3.7/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/Users/stevend2/anaconda/envs/tester/lib/python3.7/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/stevend2/PythonProjects/cvxpy/cvxpy/__init__.py", line 18, in <module>
    from cvxpy.atoms import *
  File "/Users/stevend2/PythonProjects/cvxpy/cvxpy/atoms/__init__.py", line 18, in <module>
    from cvxpy.atoms.geo_mean import geo_mean
  File "/Users/stevend2/PythonProjects/cvxpy/cvxpy/atoms/geo_mean.py", line 20, in <module>
    from cvxpy.utilities.power_tools import (fracify, decompose, approx_error, lower_bound,
  File "/Users/stevend2/PythonProjects/cvxpy/cvxpy/utilities/power_tools.py", line 18, in <module>
    from cvxpy.atoms.affine.reshape import reshape
  File "/Users/stevend2/PythonProjects/cvxpy/cvxpy/atoms/affine/reshape.py", line 17, in <module>
    from cvxpy.atoms.affine.affine_atom import AffAtom
  File "/Users/stevend2/PythonProjects/cvxpy/cvxpy/atoms/affine/affine_atom.py", line 22, in <module>
    from cvxpy.cvxcore.python import canonInterface
  File "/Users/stevend2/PythonProjects/cvxpy/cvxpy/cvxcore/python/canonInterface.py", line 17, in <module>
    import cvxpy.cvxcore.python.cvxcore as cvxcore
  File "/Users/stevend2/PythonProjects/cvxpy/cvxpy/cvxcore/python/cvxcore.py", line 28, in <module>
    _cvxcore = swig_import_helper()
  File "/Users/stevend2/PythonProjects/cvxpy/cvxpy/cvxcore/python/cvxcore.py", line 20, in swig_import_helper
    import _cvxcore
ImportError: numpy.core.multiarray failed to import

----------------------------------------------------------------------
Ran 1 test in 0.002s
```

**Version**
 - OS: OSX 10.13
 - CVXPY Version: 1.01.8

**Additional context**
I may have screwed up my environment. I was trying to replicate errors people are reporting in the convex optimization class. My best guess is conda changed somehow, but maybe I'm wrong.

**Comment by rileyjmurray** [comment]
Jesus.

Conda definitely changed recently. At the end of Jan they released version 4.6. This new version has some awesome features (radically improved Windows support), but some regressions may have been introduced in the process. There are multiple people on the anaconda-client GitHub page complaining about silent failures when uploading conda builds. I ran into similar issues myself when working on the conda Windows builds.

When you say "the latest conda build doesn't work with the latest conda", what version of conda are you running? 4.6? Because if so then it is of note that the "latest" miniconda (i.e. the one we use on Travis builds) is still currently at conda 4.5.

**Comment by rileyjmurray** [comment]
If the issue is indeed a matter of a "conda 4.5 build" vs a "conda 4.6 local installation", then one fix would be to 

1. update the Travis "install.sh" file to include ``conda update conda -y`` right after the miniconda install.
2. bump the cvxpy version on master, to trigger a new upload to the cvxgrp channel after the Travis build.

Obviously not ideal. In fact, if that does fix your problem, then I would report it right away to the Anaconda developers (because breaking backwards compatibility like that would be a huge problem for them).

**Comment by SteveDiamond** [comment]
We have ``conda update conda -y`` after the miniconda install in "install.sh". I honestly am not sure what's going on, or what will fix it. In my experience, conda regressions are not unusual (though they have been improving on this front).

**Comment by SteveDiamond** [comment]
Or we have ``conda --yes update conda``. Is that the same?

**Comment by rileyjmurray** [comment]
``conda --yes update conda`` is the same. But I looked and it seems that we only have the update statement for linux. So there's a chance that it's still an issue for you (and others on OSX).

**Comment by SteveDiamond** [comment]
Good catch! I pushed that change, will see what happens.

**Comment by rileyjmurray** [comment]
Keep in mind that you'll also need to bump the version. Travis builds don't upload to conda without a new version number (so 1.01.8 would need to be 1.01.9).

^ I can change that behavior if you want, but keeping things to "one version number, one conda file" helps with resolving user issues. We could also have build numbers (e.g. 1.01.8a, 1.01.8b) but those will require some small changes to our "versiongetter.py" helper module.

**Comment by SteveDiamond** [comment]
I'll bump the version, thanks! No need to change that behavior. It's great as it is.

**Comment by SteveDiamond** [comment]
The problem does not seem to be conda 0.4.5 vs 0.4.6. If we install, we get an import error. Here's someone's report.
```
$ python
Python 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 09:07:38) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cvxpy as cp
Traceback (most recent call last):
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/site-packages/cvxpy/cvxcore/python/cvxcore.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_cvxcore', [dirname(__file__)])
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_cvxcore'

During handling of the above exception, another exception occurred:

ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/site-packages/cvxpy/cvxcore/python/cvxcore.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_cvxcore', [dirname(__file__)])
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_cvxcore'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/site-packages/cvxpy/__init__.py", line 18, in <module>
    from cvxpy.atoms import *
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/site-packages/cvxpy/atoms/__init__.py", line 18, in <module>
    from cvxpy.atoms.geo_mean import geo_mean
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/site-packages/cvxpy/atoms/geo_mean.py", line 20, in <module>
    from cvxpy.utilities.power_tools import (fracify, decompose, approx_error, lower_bound,
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/site-packages/cvxpy/utilities/power_tools.py", line 18, in <module>
    from cvxpy.atoms.affine.reshape import reshape
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/site-packages/cvxpy/atoms/affine/reshape.py", line 17, in <module>
    from cvxpy.atoms.affine.affine_atom import AffAtom
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/site-packages/cvxpy/atoms/affine/affine_atom.py", line 22, in <module>
    from cvxpy.cvxcore.python import canonInterface
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/site-packages/cvxpy/cvxcore/python/canonInterface.py", line 17, in <module>
    import cvxpy.cvxcore.python.cvxcore as cvxcore
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/site-packages/cvxpy/cvxcore/python/cvxcore.py", line 28, in <module>
    _cvxcore = swig_import_helper()
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/site-packages/cvxpy/cvxcore/python/cvxcore.py", line 20, in swig_import_helper
    import _cvxcore
ImportError: numpy.core.multiarray failed to import
```

**Comment by bstellato** [comment]
It looks like a numpy problem. Have you tried forcing an older version for now?

**Comment by akshayka** [comment]
Googling

ImportError: numpy.core.multiarray failed to import


results in a bunch of hits, related to when people have multiple numpy
installations

**Comment by akshayka** [comment]
Eg

https://github.com/tensorflow/tensorflow/issues/559

**Comment by SteveDiamond** [comment]
Ironically I updated the numpy version in order to avoid this issue. I'm not sure downgrading will get rid of it. Can anyone try on their own machines?

**Comment by rileyjmurray** [comment]
I just tried on my laptop.

Environment:
- OSX 10.13.4
- conda 4.6.7
- base python (not used in environments!): 2.7.3.final.0
- python for conda environments: 3.6
- conda channels: defaults, conda-forge

I ran two separate configurations. For the first configuration I installed SCS from conda-forge before installing cvxpy. By doing this I make sure I get the most up-to-date version of SCS (2.x). For the second configuration, the very first thing I did was install cvxpy. The first configuration passed all tests. The second configuration passed all but two tests (which failed because of precision errors in SCS). To be extra clear, here are the commands (verbatim) I ran in my console.

Configuration 1:
```
conda create -n cvxpyInstall2019Mar1 python=3.6 -y
source activate cvxpyInstall2019Mar1
conda install -c conda-forge scs -y
conda install -c cvxgrp cvxpy -y
conda install nose -y
nosetests cvxpy
```

Configuration 2:
```
conda create -n cvxpyInstall2019Mar1_2 python=3.6 -y
source activate cvxpyInstall2019Mar1_2
conda install -c cvxgrp cvxpy -y
conda install nose -y
nosetests cvxpy
```

Here are the packages installed on my system for each configuration:

Configuration 1:
```
# packages in environment at /Users/RJMurray/anaconda2/envs/cvxpyInstall2019Mar1:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl  
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
cvxpy                     1.0.19                   py36_0    cvxgrp
dill                      0.2.9                    py36_0    conda-forge
ecos                      2.0.5            py36hf9b3073_0    cvxgrp
fastcache                 1.0.2           py36h1de35cc_1001    conda-forge
future                    0.17.1                py36_1000    conda-forge
intel-openmp              2019.1                      144  
lapack                    3.6.1                ha44fe06_2    conda-forge
libcxx                    7.0.0                h2d50403_2    conda-forge
libffi                    3.2.1             h0a44026_1005    conda-forge
libgcc                    4.8.5               hdbeacc1_10    conda-forge
libgfortran               3.0.1                         0    conda-forge
llvm-meta                 7.0.0                         0    conda-forge
mkl                       2019.1                      144  
mkl_fft                   1.0.10           py36h1de35cc_1    conda-forge
mkl_random                1.0.2            py36h1702cab_2    conda-forge
multiprocess              0.70.4                   py36_0    cvxgrp
ncurses                   6.1               h0a44026_1002    conda-forge
nose                      1.3.7                 py36_1002    conda-forge
numpy                     1.16.2           py36hacdab7b_0  
numpy-base                1.16.2           py36h6575580_0  
openblas                  0.3.3             hdc02c5d_1001    conda-forge
openssl                   1.1.1b               h1de35cc_0    conda-forge
osqp                      0.4.1           py36h1702cab_1001    conda-forge
pip                       19.0.3                   py36_0    conda-forge
python                    3.6.7             h8dc6b48_1004    conda-forge
readline                  7.0               hcfe32e1_1001    conda-forge
scipy                     1.2.1            py36h1410ff5_0  
scs                       2.0.2           py36h312d94d_1000    conda-forge
setuptools                40.8.0                   py36_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
sqlite                    3.26.0            h1765d9f_1000    conda-forge
tk                        8.6.9             ha441bb4_1000    conda-forge
wheel                     0.33.1                   py36_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zlib                      1.2.11            h1de35cc_1004    conda-forge
```

Configuration 2:
```
# packages in environment at /Users/RJMurray/anaconda2/envs/cvxpyInstall2019Mar1_2:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl  
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
cvxpy                     1.0.19                   py36_0    cvxgrp
dill                      0.2.9                    py36_0    conda-forge
ecos                      2.0.5            py36hf9b3073_0    cvxgrp
fastcache                 1.0.2           py36h1de35cc_1001    conda-forge
future                    0.17.1                py36_1000    conda-forge
intel-openmp              2019.1                      144  
lapack                    3.6.1                ha44fe06_2    conda-forge
libcxx                    7.0.0                h2d50403_2    conda-forge
libffi                    3.2.1             h0a44026_1005    conda-forge
libgcc                    4.8.5               hdbeacc1_10    conda-forge
libgfortran               3.0.1                         0    conda-forge
llvm-meta                 7.0.0                         0    conda-forge
mkl                       2019.1                      144  
mkl_fft                   1.0.10           py36h1de35cc_1    conda-forge
mkl_random                1.0.2            py36h1702cab_2    conda-forge
multiprocess              0.70.4                   py36_0    cvxgrp
ncurses                   6.1               h0a44026_1002    conda-forge
nose                      1.3.7                 py36_1002    conda-forge
numpy                     1.16.2           py36hacdab7b_0  
numpy-base                1.16.2           py36h6575580_0  
openssl                   1.1.1b               h1de35cc_0    conda-forge
osqp                      0.4.1           py36h1702cab_1001    conda-forge
pip                       19.0.3                   py36_0    conda-forge
python                    3.6.7             h8dc6b48_1004    conda-forge
readline                  7.0               hcfe32e1_1001    conda-forge
scipy                     1.2.1            py36h1410ff5_0  
scs                       1.2.6                    py36_0    cvxgrp
setuptools                40.8.0                   py36_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
sqlite                    3.26.0            h1765d9f_1000    conda-forge
tk                        8.6.9             ha441bb4_1000    conda-forge
wheel                     0.33.1                   py36_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zlib                      1.2.11            h1de35cc_1004    conda-forge
```

**Comment by SteveDiamond** [comment]
@rileyjmurray thanks so much! It seems like I overreacted. Probably not condas problem. I'll monitor what the students say about installation issues and see if any action is needed.

**Comment by SteveDiamond** [comment]
I run the same commands (environment 1) and get ``ImportError: numpy.core.multiarray failed to import``. Not sure what's going on.

**Comment by akshayka** [comment]
Did you look into
https://github.com/tensorflow/tensorflow/issues/559? You might accidentally
have multiple numpy installations

**Comment by SteveDiamond** [comment]
That kind of helped. Clearly my conda is a mess of numpys. Maybe we should switch the default installation method to pip?

**Comment by akshayka** [comment]
I exclusively use pip + virtualenv, and I've never had a problem installing
anything, including CVXPY. So I endorse making pip the default installation
method!

**Comment by SteveDiamond** [comment]
Ok I changed the default installation method to pip.
