### ISSUE TITLE
Installing 1.0.18 fails to install on Ubuntu 18.04

### ISSUE THREAD

**Issue by aneergaard** [cvxgrp/cvxpy#678]
**Describe the bug**
CVXPY fails installation on Ubuntu 18.04 with both conda and pip. I suspect the g++ compiler is the issue for pip and building from source, since adding that to environment solves the issue.

**To Reproduce**
Using conda:
```
$ conda create -n cvx-test python=3
$ conda activate cvx-test
$ conda install -c conda-forge lapack
$ conda install -c cvxgrp cvxpy=1.0.18
```
Using pip:
```
$ conda create -n cvx-test python=3
$ conda activate cvx-test
$ pip install cvxpy==1.0.18
```

The problem persists from conda 4.5 to conda 4.6.

**Output**
Using conda:
```
$ conda install -c cvxgrp cvxpy=1.0.18
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - cvxpy=1.0.18 -> osqp

Current channels:

  - https://conda.anaconda.org/cvxgrp/linux-64
  - https://conda.anaconda.org/cvxgrp/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Using pip:
[Link to error trace](https://gist.github.com/aneergaard/0900bc7560fd06a3ae4245e157edd93f)

**Version**
 - OS: Ubuntu 18.0
 - CVXPY Version: 1.0.18
- conda version: >= 4.5

**Additional context**
Conda environment:
```
$ conda list
# packages in environment at /home/neergaard/anaconda3/envs/cvx-test:
#
# Name                    Version                   Build  Channel
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py37_1000    conda-forge
lapack                    3.6.1                ha44fe06_2    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran               3.0.0                         1    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1  
ncurses                   6.1                  he6710b0_1  
openssl                   1.1.1b               h14c3975_0    conda-forge
pip                       19.0.3                   py37_0  
python                    3.7.2                h0371630_0  
readline                  7.0                  h7b6447c_5  
setuptools                40.8.0                   py37_0  
sqlite                    3.26.0               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
wheel                     0.33.1                   py37_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  

```
Furthermore, for the conda case, I tried installing osqp and then installing cvxpy, but fails again:
```
$ conda install -c oxfordcontrol osqp
$ conda install -c cvxgrp cvxpy=1.0.18
Collecting package metadata: done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - cvxpy=1.0.18
Use "conda search <package> --info" to see the dependencies for each package.

```

I **think** the problem is with the g++ compiler for the pip case, which is also the issue when building from source. Gcc was already installed on the system, I had to do `conda install libgcc` before running `python setup.py install`. Doing that resolves the issue.

**Comment by SteveDiamond** [comment]
What if you apt-get install gcc?

**Comment by SteveDiamond** [comment]
Do pip and installation from source work then?

**Comment by SteveDiamond** [comment]
We've also updated the installation instructions to
```
conda config --add channels conda-forge
conda install -c cvxgrp cvxpy
```
That will at least resolve the osqp issue.

**Comment by aneergaard** [comment]
gcc is already installed on the system.

**Comment by aneergaard** [comment]
Using the updated installation instructions installs 1.0.18 fine, but it fails on import:

```
$ python
Python 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 09:07:38) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cvxpy as cp
Traceback (most recent call last):
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/site-packages/cvxpy/cvxcore/python/cvxcore.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_cvxcore', [dirname(__file__)])
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_cvxcore'

During handling of the above exception, another exception occurred:

ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/site-packages/cvxpy/cvxcore/python/cvxcore.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_cvxcore', [dirname(__file__)])
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_cvxcore'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/site-packages/cvxpy/__init__.py", line 18, in <module>
    from cvxpy.atoms import *
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/site-packages/cvxpy/atoms/__init__.py", line 18, in <module>
    from cvxpy.atoms.geo_mean import geo_mean
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/site-packages/cvxpy/atoms/geo_mean.py", line 20, in <module>
    from cvxpy.utilities.power_tools import (fracify, decompose, approx_error, lower_bound,
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/site-packages/cvxpy/utilities/power_tools.py", line 18, in <module>
    from cvxpy.atoms.affine.reshape import reshape
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/site-packages/cvxpy/atoms/affine/reshape.py", line 17, in <module>
    from cvxpy.atoms.affine.affine_atom import AffAtom
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/site-packages/cvxpy/atoms/affine/affine_atom.py", line 22, in <module>
    from cvxpy.cvxcore.python import canonInterface
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/site-packages/cvxpy/cvxcore/python/canonInterface.py", line 17, in <module>
    import cvxpy.cvxcore.python.cvxcore as cvxcore
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/site-packages/cvxpy/cvxcore/python/cvxcore.py", line 28, in <module>
    _cvxcore = swig_import_helper()
  File "/home/neergaard/anaconda3/envs/cvx-test/lib/python3.6/site-packages/cvxpy/cvxcore/python/cvxcore.py", line 20, in swig_import_helper
    import _cvxcore
ImportError: numpy.core.multiarray failed to import
```

**Comment by aneergaard** [comment]
@SteveDiamond I just tried installing v. 1.0.19 on Ubuntu using the guidelines for conda on Linux systems posted at the website, and that works with conda 4.6. Still couldn't get the pip version to work though, but I'll do some more tests.

**Comment by SteveDiamond** [comment]
Ok thanks for testing. I was still having problems myself so I changed the default installation instructions to recommend pip. For pip, are you just missing gcc?

**Comment by bstellato** [comment]
> We've also updated the installation instructions to
> 
> ```
> conda config --add channels conda-forge
> conda install -c cvxgrp cvxpy
> ```
> That will at least resolve the osqp issue.

@SteveDiamond the conda-forge channel is not maintained by us, has an older osqp version and does not include windows recipes. I suggest you to use the `oxfordcontrol` channel intead. https://anaconda.org/oxfordcontrol/osqp This is related to https://github.com/cvxgrp/cvxpy/issues/587

**Comment by aneergaard** [comment]
No

**Comment by aneergaard** [comment]
@SteveDiamond My installation fails using pip, it's still building the wheels that is the issue. I have g++ installed on my system, but it can't find it. My previous workaround of installing libgcc doesn't work now, and building from source doesn't either. I also think it is a bad idea to do `conda config --add channels conda-forge` from a user perspective, as it forces all subsequent conda installs through conda-forge instead of the default channel. If the user is not aware of this, it could make complications for other installations.

**Comment by SteveDiamond** [comment]
@aneergaard Ok fair enough. I changed the instructions. @bstellato I changed the instructions to add the oxfordcontrol channel instead of conda-forge. Some channel has to be added with OSQP.

**Comment by aneergaard** [comment]
@SteveDiamond I'm closing the issue, since the 1.0.21 works with pip.

**Comment by SteveDiamond** [comment]
Glad we fixed it!
