### ISSUE TITLE
Error in canonicalizing a quadratic expression with constant regularization

### ISSUE THREAD

**Issue by nimily** [cvxgrp/cvxpy#682]
**Describe the bug**
Let `a` be a scalar parameter and `b` be a scalar variable. CVXPY 1.0.19 fails to minimize `b ** 2 + cvx.abs(a)`, but CVXPY 0.4.11 successfully solves it. Surprisingly, this error won't happen when minimizing `b ** 2 + cvx.abs(b)` or `b + cvx.abs(a)`.

**To Reproduce**
The following code reproduces the error:
```
import cvxpy as cvx
a = cvx.Parameter(value=1)
b = cvx.Variable()

obj = cvx.Minimize(b ** 2 + cvx.abs(a))
prob = cvx.Problem(obj)
prob.solve()
print(obj.value)
```

**Expected behavior**
Print 1.0 to the standard output.

**Output**
```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    prob.solve()
  File "/Users/nima/anaconda/envs/test/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 271, in solve
    return solve_func(self, *args, **kwargs)
  File "/Users/nima/anaconda/envs/test/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 496, in _solve
    self._solving_chain.apply(self._intermediate_problem)
  File "/Users/nima/anaconda/envs/test/lib/python3.6/site-packages/cvxpy/reductions/chain.py", line 65, in apply
    problem, inv = r.apply(problem)
  File "/Users/nima/anaconda/envs/test/lib/python3.6/site-packages/cvxpy/reductions/matrix_stuffing.py", line 63, in apply
    new_obj, new_var, r = self.stuffed_objective(problem, extractor)
  File "/Users/nima/anaconda/envs/test/lib/python3.6/site-packages/cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py", line 45, in stuffed_objective
    C, R = extractor.affine(problem.objective.expr)
  File "/Users/nima/anaconda/envs/test/lib/python3.6/site-packages/cvxpy/utilities/coeff_extractor.py", line 77, in affine
    op_list = [e.canonical_form[0] for e in expr_list]
  File "/Users/nima/anaconda/envs/test/lib/python3.6/site-packages/cvxpy/utilities/coeff_extractor.py", line 77, in <listcomp>
    op_list = [e.canonical_form[0] for e in expr_list]
  File "/Users/nima/anaconda/envs/test/lib/python3.6/site-packages/cvxpy/utilities/performance_utils.py", line 37, in _lazyprop
    setattr(self, attr_name, func(self))
  File "/Users/nima/anaconda/envs/test/lib/python3.6/site-packages/cvxpy/utilities/canonical.py", line 39, in canonical_form
    return self.canonicalize()
  File "/Users/nima/anaconda/envs/test/lib/python3.6/site-packages/cvxpy/atoms/atom.py", line 233, in canonicalize
    obj, constr = arg.canonical_form
  File "/Users/nima/anaconda/envs/test/lib/python3.6/site-packages/cvxpy/utilities/performance_utils.py", line 37, in _lazyprop
    setattr(self, attr_name, func(self))
  File "/Users/nima/anaconda/envs/test/lib/python3.6/site-packages/cvxpy/utilities/canonical.py", line 39, in canonical_form
    return self.canonicalize()
  File "/Users/nima/anaconda/envs/test/lib/python3.6/site-packages/cvxpy/atoms/atom.py", line 240, in canonicalize
    data)
TypeError: 'NotImplementedType' object is not iterable
```

**Version**
 - OS: macOS 10.14.3
 - CVXPY Version: 1.0.19

**Comment by SteveDiamond** [comment]
Thanks for pointing this out! It's fixed now in master.
