### ISSUE TITLE
Clearer failure messages from solvers

### ISSUE THREAD

**Issue by r-barnes** [cvxgrp/cvxpy#716]
**Is your feature request related to a problem? Please describe.**
cvxpy doesn't provide helpful feedback when solvers fail. For instance, if a solver hits a maximum iteration count, cvxpy shows the following:
```
Traceback (most recent call last):
  File "/home/rick/.local/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 635, in unpack_results
    self.unpack(solution)
  File "/home/rick/.local/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 610, in unpack
    raise ValueError("Cannot unpack invalid solution.")
ValueError: Cannot unpack invalid solution.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./perennial.py", line 83, in <module>
    val = prob.solve(solver=cp.OSQP, max_iter=20000)
  File "/home/rick/.local/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 271, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/rick/.local/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 506, in _solve
    self.unpack_results(solution, full_chain, inverse_data)
  File "/home/rick/.local/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 639, in unpack_results
    "Try another solver or solve with verbose=True for more "
cvxpy.error.SolverError: Solver 'OSQP' failed. Try another solver or solve with verbose=True for more information. Try recentering the problem data around 0 and rescaling to reduce the dynamic range.
```

While setting `verbose=True` does provide some diagnostic information, it varies from solver to solver. The suggestion to recenter and rescale data may also lead users astray since this is not always the real problem.

**Describe the solution you'd like**
I'd prefer to see:
```
cvxpy.error.MaxIterations: Solver 'OSQP' hit maximum iterations. Try recentering, rescaling, increasing the `max_iter` variable, or adding additional constraints to the problem.
```
A downside: setting these messages appropriately may require somehow parsing output from the solvers to determine what has gone wrong and standardizing this information, which creates issues if the solvers change their displays. On the other hand, I think this would make switching between solvers easier.

**Additional context**
The attached code hits a maximum iteration count:
```
#!/usr/bin/env python3

import math
import numpy as np
import cvxpy as cp
import matplotlib.pyplot as plt

print("Building model")
years    = 1
days     = 7
P0       = 0.1
S0       = 0
R0       = 5
dt       = 1
discount = 0.9

P = np.empty((years,days),   dtype=object)
S = np.empty((years,days),   dtype=object)
R = np.empty((years,days),   dtype=object)
u = np.empty((years,days,3), dtype=object)

variabler = np.vectorize(lambda x: cp.Variable())
P = variabler(P)
S = variabler(S)
R = variabler(R)
u = variabler(u)

cons = []

cons += [0<=x for x in u.flatten()]
cons += [0<=x for x in P.flatten()]
cons += [0<=x for x in S.flatten()]
cons += [0<=x for x in R.flatten()]

for y in range(years):
  for d in range(days):
    if y==0 and d==0:
      cons.append(P[0,0] == P0)
      cons.append(S[0,0] == S0)
      cons.append(R[0,0] == R0)
      # cons += [x==0 for x in u[y,d,:]]
    elif y>0 and d==0:
      cons.append(P[y,0] == S[y-1,-1])
      cons.append(S[y,0] == 0)
      cons.append(R[y,0] == 0)
    else:
      cons.append(P[y,d] == P[y,d-1]+u[y,d,0]*dt)
      cons.append(S[y,d] == S[y,d-1]+u[y,d,1]*dt)
      cons.append(R[y,d] == R[y,d-1]+u[y,d,2]*dt)
      cons.append(np.sum(u[y,d,:])==P[y,d-1])

obj = 0
for y in range(years):
  obj += R[y,-1] * discount**(years-1)

print("Building problem")
prob = cp.Problem(cp.Maximize(obj), cons)

print("Solving problem")
val = prob.solve(solver=cp.OSQP, verbose=True, max_iter=20000)
```

**Comment by akshayka** [comment]
Thanks for reporting, assigning myself to do a partial fix.

**Comment by akshayka** [comment]
I pushed a partial fix to this. At master, running your problem should now only trigger the SolverError, and the ValueError won't be re-raised. 

Regarding your proposed solution, that would indeed be tricker to implement. In order to report more specific errors, we'd need a common interface that solvers agreed to support. (Parsing the verbose output would be too brittle.) That in itself would be a significant project, but one that might be worth pursuing in the future.

**Comment by r-barnes** [comment]
Thanks! I'll close for now, but hold hope of more informative errors.
