### ISSUE TITLE
pip install fails with python 2.7

### ISSUE THREAD

**Issue by EnricoBeltramo** [cvxgrp/cvxpy#724]
Laungching the command:
pip install cvxpy

the installation fails with follow log:

~/VideoPopup$ pip install cvxpy
Collecting cvxpy
  Using cached https://files.pythonhosted.org/packages/82/d5/0b787694c85297e36d3afd4c8574973809a7cc52aa2c602413012da8999d/cvxpy-1.0.21.tar.gz
Collecting ecos>=2 (from cvxpy)
  Using cached https://files.pythonhosted.org/packages/69/f1/f46f338769b79a0d98093d0911744e1aba7595ca70d4119c0d22e38205ae/ecos-2.0.7.post1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting fastcache (from cvxpy)
  Using cached https://files.pythonhosted.org/packages/5f/a3/b280cba4b4abfe5f5bdc643e6c9d81bf3b9dc2148a11e5df06b6ba85a560/fastcache-1.1.0.tar.gz
Collecting multiprocess (from cvxpy)
  Using cached https://files.pythonhosted.org/packages/31/60/6d74caa02b54ca43092e745640c7d98f367f07160441682a01602ce00bc5/multiprocess-0.70.7.tar.gz
Requirement already satisfied: numpy>=1.15 in /home/ulix/.local/lib/python2.7/site-packages (from cvxpy) (1.16.3)
Collecting osqp (from cvxpy)
  Using cached https://files.pythonhosted.org/packages/cd/97/94c24a224560f043e3a2ba5ca199b59d6427a02b22b13f38fb4b3d36a623/osqp-0.5.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting scipy>=1.1.0 (from cvxpy)
  Using cached https://files.pythonhosted.org/packages/81/39/f1457091d0a45a84a2bd7815e2cf6bd45d4fe240728e9ed567cbb17c8abe/scipy-1.2.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting scs>=1.1.3 (from cvxpy)
  Using cached https://files.pythonhosted.org/packages/07/a7/0b19c8f9476a4762d296c6c5fa860f2fe580a4f579fa53aaa8515f4ca217/scs-2.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Namespace(blas64=False, extraverbose=False, float32=False, gpu=False, int32=False, scs=False)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-PK2gOz/scs/setup.py", line 219, in <module>
        run_install()
      File "/tmp/pip-install-PK2gOz/scs/setup.py", line 216, in run_install
        install_scs()
      File "/tmp/pip-install-PK2gOz/scs/setup.py", line 206, in install_scs
        long_description=('Solves convex cone programs via operator splitting. '
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 724, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 791, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 704, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 730, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 915, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1183, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1169, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-sjnAcO/scipy-1.3.0rc1/setup.py", line 31, in <module>
        '--float',
    RuntimeError: Python version >= 3.5 required.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-PK2gOz/scs/

 - OS: Ubuntu 19.01

**Comment by SteveDiamond** [comment]
It looks like SciPy is no longer supporting Python 2.7 for the version we require (https://python3statement.org/). Not sure what to do about this.

**Comment by akshayka** [comment]
We only require SciPy >= 1.1.0, which does support Python 2.7. The above trace fails because it attempts to install SciPy 1.3.0rc1 (the release candidate --- 1.3.0 is not even released yet!):

```/tmp/easy_install-sjnAcO/scipy-1.3.0rc1/setup.py```

I have no idea what's pulling in 1.3.0rc1 ...

@SteveDiamond , we should come up with a clear policy for Python 2.7 support going forward, perhaps one that's similar to NumPy/SciPy's policies.

**Comment by raymond-grointel** [comment]
`scipy-1.3.0rc1` etc is being picked up by the:

```
setup_requires=['numpy >= 1.7', 'scipy >= 0.13.2'],
```

line in `scs-2.1.0`'s `setup.py`. 

According to https://pip.readthedocs.io/en/1.4.1/cookbook.html#controlling-setup-requires:

> Setuptools offers the `setup_requires` setup() keyword for specifying dependencies that need to be present in order for the `setup.py script` to run. Internally, Setuptools uses `easy_install` to fulfill these dependencies.

Ref. https://github.com/pytest-dev/pytest-xdist/issues/136

By invoking `easy_install`, it's going for the latest `scipy` version according to `scipy >= 0.13.2`. But `easy_install` is not `pip`, so it's not even bothering to check if pip has a queued compatible `scipy` version waiting to be installed.

**Comment by raymond-grointel** [comment]
A workaround would be to install a compatible `scipy` version _before_ trying to install `cvxpy`

**Comment by raghavanand98** [comment]
@raymond-grointel I installed scipy 1.1.0 (the minimum required for cvxpy) and I did 
`pip install cvxpy --ignore-installed` but I still run into the same error. Is there some way to work around this?

**Comment by rileyjmurray** [comment]
Since this issue hasn't moved in 6 months, and since the python foundation dropped py2.7 earlier this year, I'm going to close this issue. User should keep in mind that CVXPY will officially drop py2.7 support when CVXPY v1.1 is released in the very near future.
