### ISSUE TITLE
DQCP solver fails on Python3: TypeError '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by huevosabio** [cvxgrp/cvxpy#731]
**Describe the bug**
On Python3 `reductions/dqcp2dcp/inverse.py` [line 35](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/dqcp2dcp/inverse.py#L35) fails with
```
TypeError '>' not supported between instances of 'NoneType' and 'int'
```
when solving a QCP problem. The issue arises because the parameter `t` set in `reductions/dqcp2dcp/dqcp2dcp.py` [lines 95-100](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/dqcp2dcp/dqcp2dcp.py#L95) is set without a value (i.e.`t.value == None`), and greater/less than comparisons are no longer allowed in Python3 (see https://stackoverflow.com/a/55465407):
```python
# python2.7
>>> None > 1
False
>>> None < 1
True
```

```python
# python3.7
>>> None > 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '>' not supported between instances of 'NoneType' and 'int'

>>> None < 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**To Reproduce**
```python
# problem data
n = 3
# transitions
W = np.random.random((n + 1, n + 1))
W /= W.sum(axis=1)[:,None]
W[-1, :] = np.zeros(n  + 1)
W[-1, -1] = 1.
# visits
Q = np.linalg.inv(np.eye(n) - W[:n,:n])
# entry vec
sigma = np.random.rand(n)
sigma = sigma / sigma.sum()
# time
times = np.random.rand(n)
# max supply
max_supply_s = 10.
max_supply_w = 2.

# price
price = cp.Variable((n,), pos=True)
price.value = np.zeros(n)
# revenue
rev = sigma.dot(Q) * price

# shift
shift = sigma.dot(Q).dot(times)

# supply func
def F_w(wage):
    lam =50
    k = 1
    return 1 - (cp.exp(-(wage/lam)**k))
# wage 
wage = rev / shift
# supply based on wage
wage_supply_s = max_supply_s * F_w(wage)
wage_supply_w = max_supply_w * F_w(wage)
assert wage_supply_s.is_dqcp() and wage_supply_w.is_dqcp()

# demand func
def F_p(p):
    lam = 10
    k = 1
    return (cp.exp(-(p/lam)**k))

# max demands
max_demand_s = np.random.rand(n) * 10
max_demand_w = max_demand_s * 0.2

# demand constants
demand_constant_s = max_demand_s / sigma.dot(Q)
demand_constant_w = max_demand_w / sigma.dot(Q)

# scaled demands
scaled_demand_s = []
for i in range(n):
    scaled_demand_s.append(
        demand_constant_s[i] * F_p(price[i])
    )
    
scaled_demand_w = []
for i in range(n):
    scaled_demand_w.append(
        demand_constant_w[i] * F_p(price[i])
    )
    
scaled_demand_tot = []
for i in range(n):
    scaled_demand_tot.append(
        (demand_constant_s[i] + demand_constant_w[i]) * F_p(price[i])
    )
# s constraints
h = cp.minimum(
    wage_supply_s,
    cp.minimum(*scaled_demand_s)
)
problem = cp.Problem(cp.Maximize(h))
problem.solve(qcp=True)
```

**Expected behavior**
The problem should solver.

**Output**
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-566-3c8b7f594b07> in <module>
----> 1 problem.solve(qcp=True,solver='SCS')

~/development/wa-amod/venv/lib/python3.7/site-packages/cvxpy/problems/problem.py in solve(self, *args, **kwargs)

~/development/wa-amod/venv/lib/python3.7/site-packages/cvxpy/problems/problem.py in _solve(self, solver, warm_start, verbose, parallel, gp, qcp, **kwargs)

~/development/wa-amod/venv/lib/python3.7/site-packages/cvxpy/reductions/reduction.py in reduce(self)

~/development/wa-amod/venv/lib/python3.7/site-packages/cvxpy/reductions/chain.py in apply(self, problem)

~/development/wa-amod/venv/lib/python3.7/site-packages/cvxpy/reductions/dqcp2dcp/dqcp2dcp.py in apply(self, problem)

~/development/wa-amod/venv/lib/python3.7/site-packages/cvxpy/reductions/dqcp2dcp/dqcp2dcp.py in _canonicalize_constraint(self, constr)

~/development/wa-amod/venv/lib/python3.7/site-packages/cvxpy/reductions/dqcp2dcp/dqcp2dcp.py in _canonicalize_constraint(self, constr)

~/development/wa-amod/venv/lib/python3.7/site-packages/cvxpy/reductions/dqcp2dcp/dqcp2dcp.py in <listcomp>(.0)

~/development/wa-amod/venv/lib/python3.7/site-packages/cvxpy/reductions/dqcp2dcp/dqcp2dcp.py in _canonicalize_constraint(self, constr)

~/development/wa-amod/venv/lib/python3.7/site-packages/cvxpy/reductions/dqcp2dcp/dqcp2dcp.py in <listcomp>(.0)

~/development/wa-amod/venv/lib/python3.7/site-packages/cvxpy/reductions/dqcp2dcp/dqcp2dcp.py in _canonicalize_constraint(self, constr)

~/development/wa-amod/venv/lib/python3.7/site-packages/cvxpy/reductions/dqcp2dcp/dqcp2dcp.py in _canonicalize_constraint(self, constr)

~/development/wa-amod/venv/lib/python3.7/site-packages/cvxpy/reductions/dqcp2dcp/inverse.py in <lambda>(t)

TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Version**
 - OS: 10.13.14
 - CVXPY Version: 1.0.22

**Additional context**
This works in Python2

**Comment by akshayka** [comment]
Thanks for reporting! I'll take a look.

**Comment by huevosabio** [comment]
Also, using the same code, and changing in `inverse.py`:
```
if t.value > 0
``` 
for 
```
if t.value is not None and t.value > 0
```

I get the following:

```
SolverError: Solver failed with status unbounded_inaccurate
```

Any idea of how I can debug the underlying unbounded issue?

The verbose output:
```
Preparing to bisect problem

minimize 0.0
subject to -param78 <= 10.0 * (1.0 + -var96)
           ExpCone(-([2.04883749 0.99158498 2.50502679] * var0 / 3.6369486092266325) / 50.0, 1.0, var96)
           -inf <= -var0[0] / 10.0
           -inf <= -var0[1] / 10.0
           -inf <= -var0[2] / 10.0

Finding interval for bisection ...
```

**Comment by akshayka** [comment]
@huevosabio : I pushed a fix for this issue to master. We'll cut a bug-fix release for CVXPY soon, so you can make use of the fix. Thanks for using cutting-edge technology, and for filing a helpful bug report! :) 

I ran your script with the fix. Here's the output:

```
********************************************************************************
Preparing to bisect problem

minimize 0.0
subject to -param74 <= 10.0 * (1.0 + -var92)
           ExpCone(-([1.30194173 0.93359284 1.34135821] * var0 / 1.4084753739529998) / 50.0, 1.0, var92)

Finding interval for bisection ...
initial lower bound: -16.000000
initial upper bound: -8.000000

(iteration 0) lower bound: -16.000000
(iteration 0) upper bound: -8.000000
(iteration 0) query point: -12.000000
(iteration 0) query was infeasible.

(iteration 5) lower bound: -10.250000
(iteration 5) upper bound: -10.000000
(iteration 5) query point: -10.125000
(iteration 5) query was infeasible.

(iteration 10) lower bound: -10.007812
(iteration 10) upper bound: -10.000000
(iteration 10) query point: -10.003906
(iteration 10) query was infeasible.

(iteration 15) lower bound: -10.000244
(iteration 15) upper bound: -10.000000
(iteration 15) query point: -10.000122
(iteration 15) query was infeasible.

(iteration 20) lower bound: -10.000008
(iteration 20) upper bound: -10.000000
(iteration 20) query point: -10.000004
(iteration 20) query was infeasible.

Bisection completed, with lower bound -10.000001 and upper bound -10.0000000
********************************************************************************

optimal price:  [651.69339911 472.2998959  676.32923748]
```
