### ISSUE TITLE
CVXPY + Gurobi=7.0.2 gives error when using CVXPY parameter

### ISSUE THREAD

**Issue by abyvinod** [cvxgrp/cvxpy#742]
**Describe the bug**
A bug in CVXPY + Gurobi=7.0.2 (default installation from conda install -c gurobi gurobi) in the ways cvxpy parameter variables are handled. The bug does not appear for Gurobi version 7.5.2 or 8.1.1. 

**To Reproduce**

The following code works with ECOS but not GUROBI.
```
import numpy as np
import cvxpy as cp

a = cp.Variable(1)
b = cp.Variable(1, nonneg=True)
c = cp.Parameter(1)

prob = cp.Problem(cp.Minimize(a), [a >= b*c, c>= 0])

c.value = np.array([3])
print(prob.solve(solver='ECOS'))   #Works
print(prob.solve(solver='GUROBI')) #Fails
```

**Output**
```
Solution from ECOS -4.423412571261413e-10
Traceback (most recent call last):
  File "cvxpy_mwe.py", line 12, in <module>
    print('\n\nSolution from GUROBI', prob.solve(solver='GUROBI')) #Fails
  File "XXX/lib/python3.5/site-packages/cvxpy/problems/problem.py", line 289, in solve
    return solve_func(self, *args, **kwargs)
  File "XXX/lib/python3.5/site-packages/cvxpy/problems/problem.py", line 571, in _solve
    self, data, warm_start, verbose, kwargs)
  File "XXX/lib/python3.5/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 194, in solve_via_data
    solver_opts, problem._solver_cache)
  File "XXX/lib/python3.5/site-packages/cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py", line 157, in solve_via_data
    expr = grb.LinExpr(coeff, variables)
  File "linexpr.pxi", line 35, in gurobipy.LinExpr.__init__ (../../src/python/gurobipy.c:27093)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Version**
 - OS: Ubuntu 18.04
 - CVXPY Version: 1.0.24
 - Python version: 3.5
 - Gurobi version: 7.0.2

**Additional context**
The documentation should be updated at https://www.cvxpy.org/install/index.html#install-with-gurobi-support to specify the minimum working version.

**Comment by SteveDiamond** [comment]
Sorry for the slow response. I've updated the Gurobi installation instructions on the website as you suggested.
