### ISSUE TITLE
A DCP problem arises AssertionError

### ISSUE THREAD

**Issue by WillysMa** [cvxgrp/cvxpy#750]
import numpy as np
import scipy.io as sio
import cvxpy as cp
antennas, UE, Bs = 2, 3, 2
H_ = np.mat([[0.05221169+0.02236014j, 0.11507819+0.23286528j, 0.04240248+0.05163106j],
 [0.0647228 +0.12858326j, 0.27416864+0.36640208j, 0.01989594+0.07813894j],
 [0.62388787+0.62330062j, 0.02298837+0.03943087j, 0.03940723+0.01719871j],
 [0.63787985+0.2536698j,  0.16819581+0.2366397j,  0.15092605+0.1541783j]])

sigma = [[1.]]
gamma = 1.
Pc =100.
w = cp.Variable((antennas * Bs, UE), complex=True)
Pw = cp.Variable(Bs)

constr = []
for m in range(UE):
    e = np.mat(np.eye(UE, UE))
    e[m, m] = 0
    # a=np.real(H_[:, m])
    # print(a)
    t = cp.real(H_[:, m].H @ w[:, m])
    x = cp.hstack([H_[:, m].H @ w @ e, sigma])
    constr += [cp.SOC(t / cp.sqrt(gamma), x), cp.imag(H_[:, m].H @ w[:, m]) == 0]

for q in range(Bs):
    constr += [cp.norm(w[q*antennas:(q+1)*antennas, :], 'fro') <= Pw[q], Pw[q] <= cp.sqrt(Pc)]

print(constr)
prob = cp.Problem(cp.Minimize(cp.sum(Pw)), constr)
print(prob)
print(prob.is_dcp())
prob.solve()
print('Optimal value:', prob.value)
____________________________________________________________
After I run the code, it arise an error:
Traceback (most recent call last):
  File "H:/Python_Code/channel_setup/test2.py", line 35, in <module>
    prob.solve(solver=cp.ECOS)
  File "C:\Users\MMY\AppData\Roaming\Python\Python36\site-packages\cvxpy\problems\problem.py", line 289, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\Users\MMY\AppData\Roaming\Python\Python36\site-packages\cvxpy\problems\problem.py", line 567, in _solve
    self._construct_chains(solver=solver, gp=gp)
  File "C:\Users\MMY\AppData\Roaming\Python\Python36\site-packages\cvxpy\problems\problem.py", line 510, in _construct_chains
    raise e
  File "C:\Users\MMY\AppData\Roaming\Python\Python36\site-packages\cvxpy\problems\problem.py", line 501, in _construct_chains
    self._intermediate_chain.apply(self)
  File "C:\Users\MMY\AppData\Roaming\Python\Python36\site-packages\cvxpy\reductions\chain.py", line 65, in apply
    problem, inv = r.apply(problem)
  File "C:\Users\MMY\AppData\Roaming\Python\Python36\site-packages\cvxpy\reductions\complex2real\complex2real.py", line 52, in apply
    constraint, inverse_data.real2imag, leaf_map)
  File "C:\Users\MMY\AppData\Roaming\Python\Python36\site-packages\cvxpy\reductions\complex2real\complex2real.py", line 115, in canonicalize_tree
    leaf_map)
  File "C:\Users\MMY\AppData\Roaming\Python\Python36\site-packages\cvxpy\reductions\complex2real\complex2real.py", line 128, in canonicalize_expr
    assert all(v is None for v in imag_args)
AssertionError

The problem already satisfies the DCP rules but still failed. How to solve this problem? Some help would be appreciated

**Comment by SteveDiamond** [comment]
I'm working on this. The first issue was that SOC was not set up to handle complex arguments. I fixed that, but there was still a really odd bug that I'll look at today. In the very short term, your problem may work if you avoid using SOC.

**Comment by SteveDiamond** [comment]
Ok, this is fixed now on master. There's a dimension issue in your SOC constraints right now. It should have raised an error, and does now on master. You need to write ``cp.SOC(t / cp.sqrt(gamma), x.T)`` or ``cp.SOC(t / cp.sqrt(gamma), x.flatten())``.

**Comment by WillysMa** [comment]
> Ok, this is fixed now on master. There's a dimension issue in your SOC constraints right now. It should have raised an error, and does now on master. You need to write `cp.SOC(t / cp.sqrt(gamma), x.T)` or `cp.SOC(t / cp.sqrt(gamma), x.flatten())`.

I‘ve tried  `cp.SOC(t / cp.sqrt(gamma), x.T)` and `cp.SOC(t / cp.sqrt(gamma), x.flatten())`, and still AssertionError arises. But if I use 't >= cp.sqrt(gamma) * cp.norm(x)', it will solve my problem without error.  Thanks for your help, I've solved my problem.
