### ISSUE TITLE
complex examples fails

### ISSUE THREAD

**Issue by keithbriggs** [cvxgrp/cvxpy#769]
This code:

  n=4
  np.random.seed(1)
  A=np.random.randn(n,n) 
  B=np.random.randn(n,n)
  x=cp.Variable(1,complex=True)
  obj=x*A-B
  cost=cp.sum_squares(cp.real(obj))
  prob=cp.Problem(cp.Minimize(cost))
  prob.solve()

gives:

Traceback (most recent call last):
  File "try_least_squares_00.py", line 39, in <module>
    test_01()
  File "try_least_squares_00.py", line 32, in test_01
    prob.solve()
  File "/usr/local/lib/python3.4/dist-packages/cvxpy/problems/problem.py", line 247, in solve
    return solve_func(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/cvxpy/problems/problem.py", line 362, in _solve
    self.unpack_results(solution, self._solving_chain, inverse_data)
  File "/usr/local/lib/python3.4/dist-packages/cvxpy/problems/problem.py", line 454, in unpack_results
    solution = chain.invert(solution, inverse_data)
  File "/usr/local/lib/python3.4/dist-packages/cvxpy/reductions/chain.py", line 66, in invert
    solution = r.invert(solution, inv)
  File "/usr/local/lib/python3.4/dist-packages/cvxpy/reductions/complex2real/complex2real.py", line 75, in invert
    1j*solution.primal_vars[imag_id]
KeyError: 1

However, if the line defining A is changed to:

A=np.random.randn(n,n)+0j*np.random.randn(n,n)

then it works even though A has not actually changed. 

In general the FAQ on complex variables seems out-of-date, and it has a broken link to picos.

**Comment by SteveDiamond** [comment]
Sorry for the slow response. This is fixed now on master, and I've updated the FAQ.
