### ISSUE TITLE
raise ValueError("'shape' elements cannot be negative")

### ISSUE THREAD

**Issue by GQ93** [cvxgrp/cvxpy#792]
**Describe the bug**
raise ValueError("'shape' elements cannot be negative")

**To Reproduce**
A [minimal code example](https://stackoverflow.com/help/mcve) that reproduces the bug or unexpected behavior.
import numpy as np
import cvxpy as cp

x = cp.abs(np.random.randn(264, 100))
n = x.shape[0]
eta = 1000
I_ = cp.Parameter((1, n), nonneg=True)
I_.value = np.ones((1, n))
L = cp.Variable(shape=(n, n), symmetric=True)

func = cp.trace(x.T*L*x) + eta * cp.norm(L, 'fro')
objective = cp.Minimize(func)
constraints = [I_ * L == 0, cp.trace(L) == n, L - cp.diag(cp.diag(L)) <= 0]
prob = cp.Problem(objective, constraints)

print("Optimization start.....")
print("Optimal value", prob.solve())
**Expected behavior**

**Output**
If applicable, include program output. If reporting a program crash, please include the entire stack trace.
Traceback (most recent call last):
  File "C:/Users/l/Desktop/G/unknow/LearningLaplacian/TRY.py", line 16, in <module>
    print("Optimal value", prob.solve())
  File "C:\Users\l\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 289, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\Users\l\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 569, in _solve
    self._intermediate_problem)
  File "C:\Users\l\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\reductions\chain.py", line 65, in apply
    problem, inv = r.apply(problem)
  File "C:\Users\l\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\reductions\solvers\conic_solvers\ecos_conif.py", line 109, in apply
    problem, neq_constr, ECOS.EXP_CONE_ORDER)
  File "C:\Users\l\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\reductions\solvers\conic_solvers\conic_solver.py", line 285, in group_coeff_offset
    coeff, offset = self.format_constr(problem, cons, exp_cone_order)
  File "C:\Users\l\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\reductions\solvers\conic_solvers\conic_solver.py", line 241, in format_constr
    reshaped = X_coeff.reshape((coeffs[0].shape[0], -1))
  File "C:\Users\l\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\sparse\coo.py", line 231, in reshape
    shape=shape, copy=False)
  File "C:\Users\l\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\sparse\coo.py", line 154, in __init__
    self._shape = check_shape((M, N))
  File "C:\Users\l\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\sparse\sputils.py", line 285, in check_shape
    raise ValueError("'shape' elements cannot be negative")
ValueError: 'shape' elements cannot be negative

**Version**
 - OS: windows
 - CVXPY Version:1.0.24

**Additional context**

**Comment by GQ93** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> raise ValueError("'shape' elements cannot be negative")
> 
> **To Reproduce**
> A [minimal code example](https://stackoverflow.com/help/mcve) that reproduces the bug or unexpected behavior.
> import numpy as np
> import cvxpy as cp
> 
> x = cp.abs(np.random.randn(264, 100))
> n = x.shape[0]
> eta = 1000
> I_ = cp.Parameter((1, n), nonneg=True)
> I_.value = np.ones((1, n))
> L = cp.Variable(shape=(n, n), symmetric=True)
> 
> func = cp.trace(x.T_L_x) + eta * cp.norm(L, 'fro')
> objective = cp.Minimize(func)
> constraints = [I_ * L == 0, cp.trace(L) == n, L - cp.diag(cp.diag(L)) <= 0]
> prob = cp.Problem(objective, constraints)
> 
> print("Optimization start.....")
> print("Optimal value", prob.solve())
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Output**
> If applicable, include program output. If reporting a program crash, please include the entire stack trace.
> Traceback (most recent call last):
> File "C:/Users/l/Desktop/G/unknow/LearningLaplacian/TRY.py", line 16, in 
> print("Optimal value", prob.solve())
> File "C:\Users\l\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 289, in solve
> return solve_func(self, *args, **kwargs)
> File "C:\Users\l\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 569, in _solve
> self._intermediate_problem)
> File "C:\Users\l\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\reductions\chain.py", line 65, in apply
> problem, inv = r.apply(problem)
> File "C:\Users\l\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\reductions\solvers\conic_solvers\ecos_conif.py", line 109, in apply
> problem, neq_constr, ECOS.EXP_CONE_ORDER)
> File "C:\Users\l\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\reductions\solvers\conic_solvers\conic_solver.py", line 285, in group_coeff_offset
> coeff, offset = self.format_constr(problem, cons, exp_cone_order)
> File "C:\Users\l\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\reductions\solvers\conic_solvers\conic_solver.py", line 241, in format_constr
> reshaped = X_coeff.reshape((coeffs[0].shape[0], -1))
> File "C:\Users\l\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\sparse\coo.py", line 231, in reshape
> shape=shape, copy=False)
> File "C:\Users\l\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\sparse\coo.py", line 154, in **init**
> self._shape = check_shape((M, N))
> File "C:\Users\l\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\sparse\sputils.py", line 285, in check_shape
> raise ValueError("'shape' elements cannot be negative")
> ValueError: 'shape' elements cannot be negative
> 
> **Version**
> 
> * OS: windows
> * CVXPY Version:1.0.24
> 
> **Additional context**
> Add any other context about the problem here.

**Comment by jkyl** [comment]
I have the same issue with Python 3.6.7, Windows 10, cvxpy v1.1.0a1. Downgrading Python version did not solve.

**Comment by YongchangHu** [comment]
https://github.com/cvxgrp/cvxpy/issues/826#issuecomment-648618636

**Comment by YongchangHu** [comment]
Already solved it.
See  https://github.com/cvxgrp/cvxpy/issues/826#issuecomment-648618636

**Comment by YongchangHu** [comment]
Already solved it.
See  https://github.com/cvxgrp/cvxpy/issues/826#issuecomment-648618636
