### ISSUE TITLE
[1.1] Get SDP code path working for parameterized cone programs

### ISSUE THREAD

**Issue by akshayka** [cvxgrp/cvxpy#817]
The SDP code path for parameterized cone programs does not yet work. These are the failing tests from `test_scs.py`. It appears that something is wrong with solution retrieval.

```
E.....E.E.
======================================================================
ERROR: Test complex matrices.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Akshay/projects/cvxpy/cvxpy/tests/test_scs.py", line 105, in test_cplx_mats
    sol_scs = problem.solve(solver='SCS')
  File "/Users/Akshay/projects/cvxpy/cvxpy/problems/problem.py", line 271, in solve
    return solve_func(self, *args, **kwargs)
  File "/Users/Akshay/projects/cvxpy/cvxpy/problems/problem.py", line 471, in _solve
    self.unpack_results(solution, self._solving_chain, inverse_data)
  File "/Users/Akshay/projects/cvxpy/cvxpy/problems/problem.py", line 532, in unpack_results
    solution = chain.invert(solution, inverse_data)
  File "/Users/Akshay/projects/cvxpy/cvxpy/reductions/chain.py", line 73, in invert
    solution = r.invert(solution, inv)
  File "/Users/Akshay/projects/cvxpy/cvxpy/reductions/matrix_stuffing.py", line 135, in invert
    order='F'
  File "<__array_function__ internals>", line 6, in reshape
  File "/Users/Akshay/projects/cvxpy/.eggs/numpy-1.17.2-py3.7-macosx-10.13-x86_64.egg/numpy/core/fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/Akshay/projects/cvxpy/.eggs/numpy-1.17.2-py3.7-macosx-10.13-x86_64.egg/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 56 into shape (8,8)


======================================================================
ERROR: Test PSD constraint.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Akshay/projects/cvxpy/cvxpy/tests/test_scs.py", line 191, in test_psd_constraint
    r = prob.solve(solver=cvx.SCS)
  File "/Users/Akshay/projects/cvxpy/cvxpy/problems/problem.py", line 271, in solve
    return solve_func(self, *args, **kwargs)
  File "/Users/Akshay/projects/cvxpy/cvxpy/problems/problem.py", line 471, in _solve
    self.unpack_results(solution, self._solving_chain, inverse_data)
  File "/Users/Akshay/projects/cvxpy/cvxpy/problems/problem.py", line 532, in unpack_results
    solution = chain.invert(solution, inverse_data)
  File "/Users/Akshay/projects/cvxpy/cvxpy/reductions/chain.py", line 73, in invert
    solution = r.invert(solution, inv)
  File "/Users/Akshay/projects/cvxpy/cvxpy/reductions/matrix_stuffing.py", line 135, in invert
    order='F'
  File "<__array_function__ internals>", line 6, in reshape
  File "/Users/Akshay/projects/cvxpy/.eggs/numpy-1.17.2-py3.7-macosx-10.13-x86_64.egg/numpy/core/fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/Akshay/projects/cvxpy/.eggs/numpy-1.17.2-py3.7-macosx-10.13-x86_64.egg/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 3 into shape (2,2)


======================================================================
ERROR: Test sigma_max.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Akshay/projects/cvxpy/cvxpy/tests/test_scs.py", line 71, in test_sigma_max
    result = prob.solve(solver=cvx.SCS)
  File "/Users/Akshay/projects/cvxpy/cvxpy/problems/problem.py", line 271, in solve
    return solve_func(self, *args, **kwargs)
  File "/Users/Akshay/projects/cvxpy/cvxpy/problems/problem.py", line 471, in _solve
    self.unpack_results(solution, self._solving_chain, inverse_data)
  File "/Users/Akshay/projects/cvxpy/cvxpy/problems/problem.py", line 532, in unpack_results
    solution = chain.invert(solution, inverse_data)
  File "/Users/Akshay/projects/cvxpy/cvxpy/reductions/chain.py", line 73, in invert
    solution = r.invert(solution, inv)
  File "/Users/Akshay/projects/cvxpy/cvxpy/reductions/matrix_stuffing.py", line 135, in invert
    order='F'
  File "<__array_function__ internals>", line 6, in reshape
  File "/Users/Akshay/projects/cvxpy/.eggs/numpy-1.17.2-py3.7-macosx-10.13-x86_64.egg/numpy/core/fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/Akshay/projects/cvxpy/.eggs/numpy-1.17.2-py3.7-macosx-10.13-x86_64.egg/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 15 into shape (5,5)

----------------------------------------------------------------------
Ran 10 tests in 0.585s

```

**Comment by akshayka** [comment]
Canonicalization (for all conic solvers) is also not right. e.g.,

```
======================================================================
FAIL: test_matrix_lp (cvxpy.tests.test_linear_cone.TestLinearCone)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Akshay/projects/cvxpy/cvxpy/tests/test_linear_cone.py", line 186, in test_matrix_lp
    self.assertAlmostEqual(sltn.opt_val, result - 1)
  File "/Users/Akshay/projects/cvxpy/cvxpy/tests/base_test.py", line 38, in assertAlmostEqual
    super(BaseTest, self).assertAlmostEqual(a, b, places=places)
AssertionError: 0.9999999999999873 != -1.2656542480726785e-14 within 5 places (1.0 difference)

----------------------------------------------------------------------
```
