### ISSUE TITLE
[1.1] test_problem.TestProblem.test_redundant_constraints is segfaulting (ECOS)

### ISSUE THREAD

**Issue by akshayka** [cvxgrp/cvxpy#823]
It segfaults when the problem is solved with ECOS, but not with SCS.

minimal repro:

```
import cvxpy as cp

x = cp.Variable()
obj = cp.Minimize(0)
constr = [x - x == 0]
problem = cp.Problem(obj, constr)
problem.solve(solver=cp.ECOS)
```

**Comment by akshayka** [comment]
@SteveDiamond , it seems like this problem is specific to ECOS (or the ECOS codepath is revealing a more general bug)

**Comment by akshayka** [comment]
This does seem to be specific to the ECOS codepath. cvxcore appears to return valid data.

**Comment by akshayka** [comment]
For what it's worth, the repro actually fails in 1.0.25 as well, just with a different error ...

```
(playground) akshayka:tmp Akshay$ python test_red.py
Traceback (most recent call last):
  File "test_red.py", line 8, in <module>
    problem.solve(solver=cp.ECOS)
  File "/Users/Akshay/virtualenvs/playground/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 289, in solve
    return solve_func(self, *args, **kwargs)
  File "/Users/Akshay/virtualenvs/playground/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 569, in _solve
    self._intermediate_problem)
  File "/Users/Akshay/virtualenvs/playground/lib/python3.7/site-packages/cvxpy/reductions/chain.py", line 65, in apply
    problem, inv = r.apply(problem)
  File "/Users/Akshay/virtualenvs/playground/lib/python3.7/site-packages/cvxpy/reductions/solvers/conic_solvers/ecos_conif.py", line 103, in apply
    problem, constr_map[Zero], ECOS.EXP_CONE_ORDER)
  File "/Users/Akshay/virtualenvs/playground/lib/python3.7/site-packages/cvxpy/reductions/solvers/conic_solvers/conic_solver.py", line 285, in group_coeff_offset
    coeff, offset = self.format_constr(problem, cons, exp_cone_order)
  File "/Users/Akshay/virtualenvs/playground/lib/python3.7/site-packages/cvxpy/reductions/solvers/conic_solvers/conic_solver.py", line 217, in format_constr
    return coeffs[0].tocsc(), -offsets[0]
AttributeError: 'numpy.ndarray' object has no attribute 'tocsc'
```

**Comment by rileyjmurray** [comment]
Chiming in here. In my personal experience I’ve found that ECOS can segfault on problems where one of the constraint matrices is all zero. For example, if “A” and “b” are all zeros (in the ECOS meanings for these symbols) then ECOS can behave in non-deterministic ways. The most common outcome I’ve seen is a segfault. Note that although equality constraints are trivial for that problem data, the segfault can still happen with nontrivial conic constraints.

My advice would be to check the number of nonzeros of all problem data right before calling ECOS in solve_via_data. If you have all zeros, something is odd is happening in your compilation process.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akshayka** [comment]
@rileyjmurray , it turns out you're right. Thanks a ton for chiming in. 

`test_problem.TestProblem.test_redundant_constraints` doesn't fail on master, even though it's failing on the 1.1 alpha branch. On master, the `A` matrix is all zeros, but two of the zeros are stored explicitly as doubles (so technically A.nnz == 2). On 1.1alpha, the `A` matrix is semantically the same but A.nnz == 0. This causes the segfault. Otherwise the problem data we pass to ECOS is identical, so this is definitely a bug in ECOS.
