### ISSUE TITLE
[1.1] Get Mosek code path working

### ISSUE THREAD

**Issue by akshayka** [cvxgrp/cvxpy#825]
The Mosek interface (mosek_conif) expects a CVXPY problem, but it receives a ParamConeProg and fails. Many of the unit test are erroring as a consequence of this discrepancy.

**Comment by akshayka** [comment]
961cc5f44dea652d36ee40f977a82d7fbf48c4c8 restores most functionality, but notably SDPs are not yet working

e.g.:
```
======================================================================
ERROR: Solve "Example 8.3" from Convex Optimization by Boyd & Vandenberghe.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Akshay/projects/cvxpy/cvxpy/tests/test_mosek_conif.py", line 83, in test_mosek_sdp
    prob.solve(solver=cvx.MOSEK)
  File "/Users/Akshay/projects/cvxpy/cvxpy/problems/problem.py", line 284, in solve
    return solve_func(self, *args, **kwargs)
  File "/Users/Akshay/projects/cvxpy/cvxpy/problems/problem.py", line 536, in _solve
    verbose, kwargs)
  File "/Users/Akshay/projects/cvxpy/cvxpy/reductions/solvers/solving_chain.py", line 282, in solve_via_data
    solver_opts, problem._solver_cache)
  File "/Users/Akshay/projects/cvxpy/cvxpy/reductions/solvers/conic_solvers/mosek_conif.py", line 423, in solve_via_data
    task.putbaraij(i, j, [mat], [1.0])
  File "/Users/Akshay/virtualenvs/cvxpy-dev/lib/python3.7/site-packages/mosek/__init__.py", line 7659, in putbaraij
    raise Error(rescode(res),msg)
mosek.Error: (1204) The index value 16 occurring in argument 'i' is too large.
```
