### ISSUE TITLE
NotImplementedError when calling solve() after indexing variable with list

### ISSUE THREAD

**Issue by morrisongraeme** [cvxgrp/cvxpy#852]
**Describe the bug**
Constructing a Problem and calling problem.solve() raises a NotImplementedError if a variable has been indexed using a list when constructing the cost function. If the same problem is constructed using a slice to index the variable then the solver succeeds.

**To Reproduce**
`import cvxpy as cvx
import numpy as np

x = cvx.Variable((1, 3))
y = cvx.sum(x[:, 0:2], axis=1)
cost = cvx.QuadForm(y, np.diag([1]))
prob = cvx.Problem(cvx.Minimize(cost))
prob.solve()

x = cvx.Variable((1, 3))
y = cvx.sum(x[:, [0, 1]], axis=1)
cost = cvx.QuadForm(y, np.diag([1]))
prob = cvx.Problem(cvx.Minimize(cost))
prob.solve()`

**Expected behavior**
The second call to prob.solve() should return the same result as the first call to prob.solve()

**Output**
`Traceback (most recent call last):
  File "/Users/graeme/temp/cvxpy_bug_demo.py", line 14, in <module>
    prob.solve()
  File "/anaconda3/envs/my_env/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 268, in solve
    return solve_func(self, *args, **kwargs)
  File "/anaconda3/envs/my_env/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 381, in _solve
    data, inverse_data = self._solving_chain.apply(self)
  File "/anaconda3/envs/my_env/lib/python3.6/site-packages/cvxpy/reductions/chain.py", line 65, in apply
    problem, inv = r.apply(problem)
  File "/anaconda3/envs/my_env/lib/python3.6/site-packages/cvxpy/reductions/matrix_stuffing.py", line 79, in apply
    Afull, bfull = extractor.affine(expr_list)
  File "/anaconda3/envs/my_env/lib/python3.6/site-packages/cvxpy/utilities/coeff_extractor.py", line 75, in affine
    op_list = [e.canonical_form[0] for e in expr_list]
  File "/anaconda3/envs/my_env/lib/python3.6/site-packages/cvxpy/utilities/coeff_extractor.py", line 75, in <listcomp>
    op_list = [e.canonical_form[0] for e in expr_list]
  File "/anaconda3/envs/my_env/lib/python3.6/site-packages/cvxpy/utilities/performance_utils.py", line 37, in _lazyprop
    setattr(self, attr_name, func(self))
  File "/anaconda3/envs/my_env/lib/python3.6/site-packages/cvxpy/utilities/canonical.py", line 39, in canonical_form
    return self.canonicalize()
  File "/anaconda3/envs/my_env/lib/python3.6/site-packages/cvxpy/atoms/atom.py", line 233, in canonicalize
    obj, constr = arg.canonical_form
  File "/anaconda3/envs/my_env/lib/python3.6/site-packages/cvxpy/utilities/performance_utils.py", line 37, in _lazyprop
    setattr(self, attr_name, func(self))
  File "/anaconda3/envs/my_env/lib/python3.6/site-packages/cvxpy/utilities/canonical.py", line 39, in canonical_form
    return self.canonicalize()
  File "/anaconda3/envs/my_env/lib/python3.6/site-packages/cvxpy/atoms/atom.py", line 233, in canonicalize
    obj, constr = arg.canonical_form
  File "/anaconda3/envs/my_env/lib/python3.6/site-packages/cvxpy/utilities/performance_utils.py", line 37, in _lazyprop
    setattr(self, attr_name, func(self))
  File "/anaconda3/envs/my_env/lib/python3.6/site-packages/cvxpy/utilities/canonical.py", line 39, in canonical_form
    return self.canonicalize()
  File "/anaconda3/envs/my_env/lib/python3.6/site-packages/cvxpy/atoms/atom.py", line 240, in canonicalize
    data)
TypeError: 'NotImplementedType' object is not iterable`

**Version**
 - OS: MacOS 10.14.6, Python 3.6
 - CVXPY Version: 1.0.14

**Comment by rileyjmurray** [comment]
@SteveDiamond @akshayka please take a look at this. I'm in the process of writing a "support function" atom, and during tests this ended up being an issue. The issue seems to be that ``cvxpy.atoms.affine.index.special_index`` cannot handle non-constant expressions. At least, if you index into a variable with logical indexing, or list indexing, then call ``.canonical_form`` on the result, you will be hit with an error.

Here is a minimal working example:
```
import cvxpy
import numpy as np

x = cvxpy.Variable(shape=(2,))
cf0 = x.canonical_form  # works fine
expr = x[np.array([False, True])]
print(type(expr))  # shows the special_index class
cf1 = expr.canonical_form  # raises a NotImplementedError
```

**Comment by rileyjmurray** [comment]
I'm digging into this a little more. It seems we're looking at part of cvxpy which is deprecated. Calling ``expr.canonical_form`` looks for an implementation of the function ``graph_implementation`` for ``type(expr)`` objects. There is no such implementation for ``special_index`` objects. In virtually all situations when you apply fancy indexing with cvxpy>=1.0, the ``graph_implementation`` function isn't called; cvxpy is supposed to call ``cvxpy.reductions.utilities.special_index_canon``.

In my case, since I'm writing an atom, it's reasonable that I need to use the ``special_index_canon`` function. However it isn't clear to me why it isn't clear to me why the canonicalizer tries to access ``special_index.graph_implementation`` for @morrisongraeme's example.

**Comment by SteveDiamond** [comment]
@rileyjmurray it's because @morrisongraeme's example is following a different code path specific to QPs. Previously special index was defined as ``reshape(A@vec(x),...)`` where ``A`` picks out the entries and ``reshape`` converts things back to the right shape. The easiest fix would be to go back to that (the code is in ``special_index_canon``, but there were some reasons why we made special_index its own class). Anyway we'll fix it soon.

**Comment by SteveDiamond** [comment]
I fixed the bug on master.
