### ISSUE TITLE
Errors in nosetests with 1.1.0a0

### ISSUE THREAD

**Issue by spenrich** [cvxgrp/cvxpy#853]
After installing CVXPY v1.1.0a0 via `pip install cvxpy==1.1.0a0`, running `nosetests cvxpy` results in `FAILED (SKIP=3, errors=192)`. From scrolling through, it seems that all of the errors are of the type `RuntimeError: Constant must be a scalar`. The same error occurs when I try to run the quadratic program example from the docs: [https://www.cvxpy.org/examples/basic/quadratic_program.html](url)

CVXPY v1.0.25 works fine on my machine.

 - OS: MacOS Mojave (10.14.6)
 - CVXPY Version: 1.1.0a0

Below is the stack trace for one of the tests:
```
======================================================================
ERROR: Test the list of installed solvers.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/spenrich/Tools/anaconda3/lib/python3.6/site-packages/cvxpy/tests/test_solvers.py", line 1042, in test_installed_solvers
    prob.solve(solver=solver)
  File "/Users/spenrich/Tools/anaconda3/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 302, in solve
    return solve_func(self, *args, **kwargs)
  File "/Users/spenrich/Tools/anaconda3/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 586, in _solve
    data, solving_chain, inverse_data = self.get_problem_data(solver, gp)
  File "/Users/spenrich/Tools/anaconda3/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 412, in get_problem_data
    data, inverse_data = solving_chain.apply(self)
  File "/Users/spenrich/Tools/anaconda3/lib/python3.6/site-packages/cvxpy/reductions/chain.py", line 65, in apply
    problem, inv = r.apply(problem)
  File "/Users/spenrich/Tools/anaconda3/lib/python3.6/site-packages/cvxpy/reductions/qp2quad_form/qp_matrix_stuffing.py", line 72, in apply
    new_obj, new_var, r = self.stuffed_objective(problem, extractor)
  File "/Users/spenrich/Tools/anaconda3/lib/python3.6/site-packages/cvxpy/reductions/qp2quad_form/qp_matrix_stuffing.py", line 58, in stuffed_objective
    P, q, r = extractor.quad_form(expr)
  File "/Users/spenrich/Tools/anaconda3/lib/python3.6/site-packages/cvxpy/utilities/coeff_extractor.py", line 181, in quad_form
    raise RuntimeError("Constant must be a scalar")
RuntimeError: Constant must be a scalar
```

**Comment by akshayka** [comment]
Thanks for being an alpha tester! :) It’s strange that this bug didn’t surface in our CI, or on our local machines. We’ll look into it!

**Comment by akshayka** [comment]
@spenrich , a few questions:

Did you install 1.1.0a0 in a fresh conda environment (that has no Python packages installed)? If not, can you try doing that?

Do you have any commercial solvers installed (eg, Gurobi, MOSEK), and if so which ones? We don’t test commercial solvers on our CI ... though I would be surprised if that was the issue here. 

What happens when you try to solve the basic QP with solver=cp.OSQP and solver=cp.SCS?

**Comment by spenrich** [comment]
@akshayka A fresh environment did the trick (with pip, NumPy, SciPy, CVXPY, and any automatically installed dependencies). Nosetests resulted in `OK (SKIP=3)`. Sorry, I should've tried that first before posting!

I'll try checking the more commonly used packages I had installed to see if one of them caused the issue.

**Comment by akshayka** [comment]
No worries! If you find out what caused the issue, feel free to report back here.
