### ISSUE TITLE
CPLEX support broken with latest from github (commit a747351)

### ISSUE THREAD

**Issue by rkersh** [cvxgrp/cvxpy#866]
**Describe the bug**
Running the unit tests, with the CPLEX solver installed, results in errors (see output section below).

**To Reproduce**
Assuming the `cplex` packages is installed (the free community edition available via `pip install cplex` should be sufficient), run the following:

`python cvxpy/tests/test_solvers.py`

**Expected behavior**
Expecting all tests to pass as they were with the 1.0.25 release.

**Output**
We see errors like the following:

```
Traceback (most recent call last):
  File "cvxpy/tests/test_solvers.py", line 1032, in test_installed_solvers
    prob.solve(solver=solver)
  File "/home/rkersh/git/mycvxpy2/cvxpy/problems/problem.py", line 302, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/rkersh/git/mycvxpy2/cvxpy/problems/problem.py", line 589, in _solve
    self.unpack_results(solution, solving_chain, inverse_data)
  File "/home/rkersh/git/mycvxpy2/cvxpy/problems/problem.py", line 661, in unpack_results
    solution = chain.invert(solution, inverse_data)
  File "/home/rkersh/git/mycvxpy2/cvxpy/reductions/chain.py", line 73, in invert
    solution = r.invert(solution, inv)
  File "/home/rkersh/git/mycvxpy2/cvxpy/reductions/qp2quad_form/qp_matrix_stuffing.py", line 140, in invert
    order='F'
  File "<__array_function__ internals>", line 6, in reshape
  File "/home/rkersh/virtualenv/3.6/mycvxpy/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/rkersh/virtualenv/3.6/mycvxpy/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 0 into shape (2,)
```

**Version**
 - OS: x86-64 Linux (probably any)
 - CVXPY Version: current master (commit a747351d1844ed1af08f64b2b6ae2b22320baf70).

**Additional context**

A `git bisect` gives the following:

```
badc0a79701da0785acaaf994b9d072bafb64efb is the first bad commit
commit badc0a79701da0785acaaf994b9d072bafb64efb
Author: Akshay Agrawal <akshaykagrawal7@gmail.com>
Date:   Fri Oct 18 09:54:34 2019 -0700

    1.1 alpha (#841)
```

Here is the gitbisect log:

```
git bisect start
# good: [b0e850077e841022bd4580316b4ca67f01a5b044] Bump version: 1.0.24 → 1.0.25
git bisect good b0e850077e841022bd4580316b4ca67f01a5b044
# bad: [852951e19c5a42d88d65a45d4ef69610d0ca24c9] support functions (transform, and atom) (#860)
git bisect bad 852951e19c5a42d88d65a45d4ef69610d0ca24c9
# bad: [fa5388f631cfd752cc9c7b91a3c1c4df711939f4] Update text on homepage to have v number for alpha
git bisect bad fa5388f631cfd752cc9c7b91a3c1c4df711939f4
# bad: [b2bdd561ac4d5fc53e0b6623735af85c4109b761] Fix license in cvxcore.i (#834) (#836)
git bisect bad b2bdd561ac4d5fc53e0b6623735af85c4109b761
# good: [5b28239537e94315d84c275eff1dc7957c4308b5] removing more mentiosn of six
git bisect good 5b28239537e94315d84c275eff1dc7957c4308b5
# good: [b3820156336e035b7f48be6af322f20c2c2432d3] Fix typo is DQCP docs
git bisect good b3820156336e035b7f48be6af322f20c2c2432d3
# good: [d746b3d6c1027048d508595324500840ea495956] Update text about 1.1
git bisect good d746b3d6c1027048d508595324500840ea495956
# bad: [badc0a79701da0785acaaf994b9d072bafb64efb] 1.1 alpha (#841)
git bisect bad badc0a79701da0785acaaf994b9d072bafb64efb
# good: [816414b09580113e7406670551e8b4ca3a395a97] Remove extra verb from the operators subsection at the atomic functions section (#838)
git bisect good 816414b09580113e7406670551e8b4ca3a395a97
# first bad commit: [badc0a79701da0785acaaf994b9d072bafb64efb] 1.1 alpha (#841)
```

**Comment by rkersh** [comment]
@akshayka: I'm not familiar with the code that is breaking (nor what changed in the commit mentioned above). Any ideas?

**Comment by SteveDiamond** [comment]
This is my mistake, I was supposed to make sure all the interfaces worked in that commit. I've fixed the CPLEX solver in master. I'm taking a look at the other solvers.
