### ISSUE TITLE
Error with quasiconvex atom

### ISSUE THREAD

**Issue by dberkens** [cvxgrp/cvxpy#904]
I am finding the following error with a min max quasiconvex program.

Input code
` t = cp.Variable(5,pos=True)
obj = cp.max((1-2*cp.sqrt(t)+t)/t)
 prob = cp.Problem(cp.Minimize(obj))
prob.solve(qcp=True)`

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 289, in solve
    return solve_func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 557, in _solve
    chain.reduce(), solver=solver, verbose=verbose, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/reductions/reduction.py", line 92, in reduce
    problem, retrieval_data = self.apply(self.problem)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/reductions/chain.py", line 65, in apply
    problem, inv = r.apply(problem)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/reductions/dqcp2dcp/dqcp2dcp.py", line 101, in apply
    constraints += self._canonicalize_constraint(objective <= t)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/reductions/dqcp2dcp/dqcp2dcp.py", line 177, in _canonicalize_constraint
    sublevel_set = sets.sublevel(lhs.copy(canon_args), t=rhs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/reductions/dqcp2dcp/sets.py", line 150, in sublevel
    return SUBLEVEL_SETS[type(expr)](expr, t)
KeyError: <class 'cvxpy.atoms.max.max'>`

This appears to be happening for other atoms applied to qcp problems as well. For instance, although max should be allowed under qcp=True (and sent the issue above) I also tried sum on qcp (which shouldn't work) and got a similar error, though not a flag that the problem was not qcp due to the summation.

**Comment by akshayka** [comment]
Thanks for reporting! We'll take a look. Do you have source code that you can share to reproduce the bug involving the sum atom?

**Comment by dberkens** [comment]
For sure, and thanks for taking a look! For the summation example, 

`import cvxpy as cp

t = cp.Variable(5,pos=True)

obj = cp.sum(cp.square(t)/t)

prob = cp.Problem(cp.Minimize(obj))

prob.solve(qcp=True)`

produces the following:

`Traceback (most recent call last):
  File "sum_error.py", line 5, in <module>
    prob.solve(qcp=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 289, in solve
    return solve_func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 557, in _solve
    chain.reduce(), solver=solver, verbose=verbose, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/reductions/reduction.py", line 92, in reduce
    problem, retrieval_data = self.apply(self.problem)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/reductions/chain.py", line 65, in apply
    problem, inv = r.apply(problem)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/reductions/dqcp2dcp/dqcp2dcp.py", line 101, in apply
    constraints += self._canonicalize_constraint(objective <= t)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/reductions/dqcp2dcp/dqcp2dcp.py", line 177, in _canonicalize_constraint
    sublevel_set = sets.sublevel(lhs.copy(canon_args), t=rhs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/reductions/dqcp2dcp/sets.py", line 150, in sublevel
    return SUBLEVEL_SETS[type(expr)](expr, t)
KeyError: <class 'cvxpy.atoms.affine.sum.Sum'>`

Seems like this should produce some kind of non-disciplined convex program error...

**Comment by dberkens** [comment]
BTW if helpful the following bisection code seems to work a-ok in cvxpy,

```python
import cvxpy as cp

x = cp.Variable(2,pos=True)

eps = .001

# solving min max((1-2*sqrt(x)+x)/x)
# via bisection with x[0] <= .5
#                    x[1] <= .9
#
# iterate solution of
#
# min 1 
# st max(1-2*sqrt(x)+x - t*x) <= 0
#    x[0] - .5 <= 0
#    x[1] - .9 <= 0
#

l = 0.0
u = 100.0

i = 1
while (u-l) > eps:
    t = (l+u)/2.
    obj = 1
    constraint = [x[0]-.5<=0, x[1]-.9<=0, cp.max(1-2*cp.sqrt(x)+x-t*x) <= 0]
    prob = cp.Problem(cp.Minimize(obj),constraint)
    prob.solve()
    print('prob value = ', prob.value, ' x[0] val = ', x[0].value, ' x[1] val = ', x[1].value)

    if prob.value == 1:
        u = t
    else:
        l = t

print('Final value of x[0] = ', x[0].value, ' x[1] = ', x[1].value)
```

with the following output 

```
prob value =  1.0  x[0] val =  0.12680124123102843  x[1] val =  0.21554589963066342
prob value =  1.0  x[0] val =  0.15367011580463869  x[1] val =  0.254671935355481
prob value =  1.0  x[0] val =  0.19051612329459786  x[1] val =  0.307852498544531
prob value =  1.0  x[0] val =  0.2327744021881528  x[1] val =  0.3727140330437784
prob value =  1.0  x[0] val =  0.33775385965455096  x[1] val =  0.5278672034118689
prob value =  1.0  x[0] val =  0.36769834818510655  x[1] val =  0.5636792435159235
prob value =  1.0  x[0] val =  0.4035909463955593  x[1] val =  0.5989754227810449
prob value =  1.0  x[0] val =  0.4446612650646662  x[1] val =  0.6374049900429277
prob value =  1.0  x[0] val =  0.49152800102254807  x[1] val =  0.6751550733302792
prob value =  inf  x[0] val =  None  x[1] val =  None
prob value =  inf  x[0] val =  None  x[1] val =  None
prob value =  inf  x[0] val =  None  x[1] val =  None
prob value =  1.0  x[0] val =  0.49595909696520596  x[1] val =  0.6820290699285073
prob value =  1.0  x[0] val =  0.4982226730809303  x[1] val =  0.6787212387020509
prob value =  1.0  x[0] val =  0.49929529238480513  x[1] val =  0.6748416462876611
prob value =  1.0  x[0] val =  0.49975165568546065  x[1] val =  0.6779124006929196
prob value =  1.0  x[0] val =  0.49997206753340906  x[1] val =  0.6766140266864319
Final value of x[0] =  0.49997206753340906  x[1] =  0.6766140266864319
```

so seems like the bisection of 

```
minimize 1
such that:
    max (p(x)-t*q(x))<=0
    ...
```

works, if that helps at all, love the quasiconvex inclusion!

**Comment by akshayka** [comment]
Definitely helpful, thanks! I believe I know what the bug is, and how to fix it. I'll try to get a fix in within the next week or so.

**Comment by dberkens** [comment]
cool thanks!

**Comment by akshayka** [comment]
@dberkens, I've pushed a fix to master. We'll release a new version of CVXPY that includes the fix soon. Please let me know if you run into any other issues!

**Comment by akshayka** [comment]
@dberkens: We've released a pre-release on PyPi, version 1.1.0.a2, that contains a fix for this issue. If you're willing to use a pre-release, you can install it with

```
pip install --pre --ugprade cvxpy
```

Hope that helps!

**Comment by dberkens** [comment]
Thanks! Will give it a try and report back.

Dan

**Comment by dberkens** [comment]
Very nice - I've been able to verify the new release works for both cases. Thanks for the help!

**Comment by akshayka** [comment]
Great! Thanks for confirming.

**Comment by rodfloripa** [comment]
I have the same problem

import numpy as np
import cvxpy as cp
import matplotlib.pyplot as plt

class Edge(object):
    """ An undirected, capacity limited edge. """
    def __init__(self):
        self.c1 = []
        self.c2 = []

    # Connects two nodes via the edge.
    def connect(self, in_node, out_node):
        self.c1.append(in_node.color)
        self.c2.append(out_node.color)
        

    # Returns the edge's internal constraints.
    def constraints(self):
        
        return [cp.pos(self.c1[0] - self.c2[0]) >= 1]
    
class Node(object):
    """ A node with accumulation. """
    def __init__(self, number):
        self.number = number
        if number == max_neigb:
            self.color = 0
        else:
            self.color = cp.Variable(integer=True)

edges = [(1,0),(1,2),(1,3)]
n_nodes = 4
nodes_lst = []
n_edges = 3
edges_lst = []
max_neigb = []

for i in edges:
    max_neigb.append(i[0])
    max_neigb.append(i[1])
max_neigb = max(max_neigb,key=max_neigb.count)
for i in range(0,n_nodes):
    nodes_lst.append(Node(i))
for i in range(0,n_edges):
    edges_lst.append(Edge())    
for i in range(0,n_edges):
    edges_lst[i].connect(nodes_lst[edges[i][0]],nodes_lst[edges[i][1]])    

sum_ = []
for i in range(0,n_edges):
    sum_.append(edges_lst[i].c1[0])
    sum_.append(edges_lst[i].c2[0])

constraints = []
for obj in edges_lst:
    constraints += obj.constraints()
prob = cp.Problem(cp.Minimize(cp.sum(sum_)), constraints)

result = prob.solve(qcp=True)
print(result)

Traceback (most recent call last):
  File "/usr/app/t.py", line 65, in <module>
    result = prob.solve(qcp=True)
  File "/usr/local/lib/python3.9/site-packages/cvxpy/problems/problem.py", line 462, in solve
    return solve_func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cvxpy/problems/problem.py", line 945, in _solve
    chain.reduce(), solver=solver, verbose=verbose, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cvxpy/reductions/reduction.py", line 94, in reduce
    problem, retrieval_data = self.apply(self.problem)
  File "/usr/local/lib/python3.9/site-packages/cvxpy/reductions/chain.py", line 76, in apply
    problem, inv = r.apply(problem)
  File "/usr/local/lib/python3.9/site-packages/cvxpy/reductions/dqcp2dcp/dqcp2dcp.py", line 94, in apply
    constraints += self._canonicalize_constraint(constr)
  File "/usr/local/lib/python3.9/site-packages/cvxpy/reductions/dqcp2dcp/dqcp2dcp.py", line 201, in _canonicalize_constraint
    superlevel_set = sets.superlevel(rhs.copy(canon_args), t=lhs)
  File "/usr/local/lib/python3.9/site-packages/cvxpy/reductions/dqcp2dcp/sets.py", line 158, in superlevel
    return SUPERLEVEL_SETS[type(expr)](expr, t)
KeyError: <class 'cvxpy.atoms.elementwise.maximum.maximum'>
