### ISSUE TITLE
 AttributeError: module 'mosek' has no attribute 'conetype'  

### ISSUE THREAD

**Issue by nirvana1122** [cvxgrp/cvxpy#931]
Hi,

I am having problem using cvxpy on my windows machine which had a Mosek installation in the past. Any idea how to fix this issue?

Thanks

Microsoft Windows [Version 10.0.18363.535]
(c) 2019 Microsoft Corporation. All rights reserved.
C:\Users\NAME>python Y:\pyLib\library\riskModel\fundamental_factors.py --start_date 20090101 --end_date 20121231
Traceback (most recent call last):
  File "Y:\pyLib\library\riskModel\fundamental_factors.py", line 12, in <module>
    import cvxpy as cv
  File "C:\Anaconda3\lib\site-packages\cvxpy\__init__.py", line 22, in <module>
    from cvxpy.problems.problem import Problem
  File "C:\Anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 20, in <module>
    from cvxpy.reductions.chain import Chain
  File "C:\Anaconda3\lib\site-packages\cvxpy\reductions\__init__.py", line 32, in <module>
    from cvxpy.reductions.solvers.solving_chain import SolvingChain
  File "C:\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\solving_chain.py", line 8, in <module>
    from cvxpy.reductions.solvers import defines as slv_def
  File "C:\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\defines.py", line 93, in <module>
    INSTALLED_SOLVERS = installed_solvers()
  File "C:\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\defines.py", line 82, in installed_solvers
    if solver.is_installed():
  File "C:\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\solver.py", line 70, in is_installed
    self.import_solver()
  File "C:\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\conic_solvers\mosek_conif.py", line 105, in import_solver
    if hasattr(mosek.conetype, 'pexp') and ExpCone not in MOSEK.SUPPORTED_CONSTRAINTS:
AttributeError: module 'mosek' has no attribute 'conetype'

**Comment by zhan-gao** [comment]
I met the same issue on a MacBook. Is the problem solved?
