### ISSUE TITLE
pip install cvxpy, nosetests failed, ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by Vivian-SJ** [cvxgrp/cvxpy#935]
**Describe the bug**
I try to install the cvxpy using pip. After installing successfully, when I test using 'nosetests cvxpy' command, it report 
'ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
..............................................EE..ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................S........S..........................................F.......ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
...........................................................................................ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
..........................................................................................................................ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
...ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
..ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
..ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
.
======================================================================
ERROR: test_least_squares (cvxpy.tests.test_benchmarks.TestBenchmarks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/tests/test_benchmarks.py", line 82, in test_least_squares
    benchmark(least_squares, iters=1)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/tests/test_benchmarks.py", line 15, in benchmark
    func(*func_args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/tests/test_benchmarks.py", line 81, in least_squares
    cp.Problem(cp.Minimize(cost)).get_problem_data(cp.OSQP)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 385, in get_problem_data
    self._construct_chains(solver=solver, gp=gp)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 510, in _construct_chains
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 496, in _construct_chains
    gp=gp)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 433, in _find_candidate_solvers
    raise error.SolverError("The solver %s is not installed." % solver)
cvxpy.error.SolverError: The solver OSQP is not installed.

======================================================================
ERROR: test_qp (cvxpy.tests.test_benchmarks.TestBenchmarks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/tests/test_benchmarks.py", line 101, in test_qp
    benchmark(qp, iters=1)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/tests/test_benchmarks.py", line 15, in benchmark
    func(*func_args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/tests/test_benchmarks.py", line 100, in qp
    cp.matmul(A, x) == b]).get_problem_data(cp.OSQP)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 385, in get_problem_data
    self._construct_chains(solver=solver, gp=gp)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 510, in _construct_chains
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 496, in _construct_chains
    gp=gp)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 433, in _find_candidate_solvers
    raise error.SolverError("The solver %s is not installed." % solver)
cvxpy.error.SolverError: The solver OSQP is not installed.

======================================================================
FAIL: test_lin_frac (cvxpy.tests.test_dqcp.TestDqcp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cvxpy/tests/test_dqcp.py", line 357, in test_lin_frac
    np.testing.assert_almost_equal(x.value, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 568, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 973, in assert_array_almost_equal
    precision=decimal)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 789, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 7 decimals

(mismatch 50.0%)
 x: array([7.9410198e-08, 1.8426759e-07])
 y: array(0)

----------------------------------------------------------------------
Ran 1930 tests in 49.555s

FAILED (SKIP=2, errors=2, failures=1)'

**Version**
 - OS: MacOS 10.14.6
 - CVXPY Version: I install it directly using 'pip install cvxpy', so I guess it's the latest version.

**Comment by SteveDiamond** [comment]
Try uninstalling cvxpy and numpy, then installing numpy then cvxpy?

**Comment by Vivian-SJ** [comment]
It works!!! Thank you!

**Comment by SteveDiamond** [comment]
Great!
