### ISSUE TITLE
Cannot import: AttributeError: module 'mosek' has no attribute 'conetype'

### ISSUE THREAD

**Issue by zhan-gao** [cvxgrp/cvxpy#977]
Any comments or solution would be greatly appreciated.

**Describe the bug**
With Mosek 9.1.13 installed. cvxpy installed via Anaconda. When import cvxpy, got the error: `AttributeError: module 'mosek' has no attribute 'conetype'.`

**Output**
```
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
Type "copyright", "credits" or "license" for more information.

IPython 7.12.0 -- An enhanced Interactive Python.

import cvxpy as cp
Traceback (most recent call last):

  File "<ipython-input-1-b9466877789b>", line 1, in <module>
    import cvxpy as cp

  File "/opt/anaconda3/lib/python3.7/site-packages/cvxpy/__init__.py", line 22, in <module>
    from cvxpy.problems.problem import Problem

  File "/opt/anaconda3/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 20, in <module>
    from cvxpy.reductions.chain import Chain

  File "/opt/anaconda3/lib/python3.7/site-packages/cvxpy/reductions/__init__.py", line 32, in <module>
    from cvxpy.reductions.solvers.solving_chain import SolvingChain

  File "/opt/anaconda3/lib/python3.7/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 8, in <module>
    from cvxpy.reductions.solvers import defines as slv_def

  File "/opt/anaconda3/lib/python3.7/site-packages/cvxpy/reductions/solvers/defines.py", line 93, in <module>
    INSTALLED_SOLVERS = installed_solvers()

  File "/opt/anaconda3/lib/python3.7/site-packages/cvxpy/reductions/solvers/defines.py", line 82, in installed_solvers
    if solver.is_installed():

  File "/opt/anaconda3/lib/python3.7/site-packages/cvxpy/reductions/solvers/solver.py", line 70, in is_installed
    self.import_solver()

  File "/opt/anaconda3/lib/python3.7/site-packages/cvxpy/reductions/solvers/conic_solvers/mosek_conif.py", line 105, in import_solver
    if hasattr(mosek.conetype, 'pexp') and ExpCone not in MOSEK.SUPPORTED_CONSTRAINTS:

AttributeError: module 'mosek' has no attribute 'conetype'
```

**Version**
 - OS: 10.15.4

**Comment by aszekMosek** [comment]
A typical reason I have seen for such issues is that ``mosek`` is imported as something else than you thought, for example you have a file called ``mosek.py`` or some other ``mosek`` module in your python path.

**Comment by zhan-gao** [comment]
> A typical reason I have seen for such issues is that `mosek` is imported as something else than you thought, for example you have a file called `mosek.py` or some other `mosek` module in your python path.

Hi @aszekMosek , thank you very much for your reply. Indeed, `import mosek` can be implement without error. I checked `echo $PYTHONPATH`, it's empty. Any suggestions to remove the mosek module? Appreciation in advance.

**Comment by rileyjmurray** [comment]
It is possible that ``import mosek`` succeeds, but this does not correctly import the mosek python package. As aszekMosek explained, this can happen when you have another file or folder in your working directory with the name "mosek". Please make sure this is not the case.

**Comment by rileyjmurray** [comment]
Closing due to inactivity.
