### ISSUE TITLE
Error: import cvxpy as cp

### ISSUE THREAD

**Issue by HuiHu1** [cvxgrp/cvxpy#991]
**Describe the bug**
After installing cvxpy package, it can't be imported normally.
Install step: 
(1) Install Anaconda.
(2) conda install pip
    pip install --upgrade setuptools
(3) Download the Visual Studio build tools for Python 3.
(4) pip install cvxpy

The first error is:
    File "C:\Fair_D2.py", line 10, in <module>
    import cvxpy as cp

  File "C:\Users\Anaconda3\lib\site-packages\cvxpy\__init__.py", line 22, in <module>
    from cvxpy.problems.problem import Problem

  File "C:\Users\Anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 20, in <module>
    from cvxpy.reductions.chain import Chain

  File "C:\Users\lib\site-packages\cvxpy\reductions\__init__.py", line 32, in <module>
    from cvxpy.reductions.solvers.solving_chain import SolvingChain

  File "C:\Users\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\solving_chain.py", line 8, in <module>
    from cvxpy.reductions.solvers import defines as slv_def

  File "C:\Users\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\defines.py", line 93, in <module>
    INSTALLED_SOLVERS = installed_solvers()

  File "C:\Users\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\defines.py", line 82, in installed_solvers
    if solver.is_installed():

  File "C:\Users\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\solver.py", line 70, in is_installed
    self.import_solver()

  File "C:\Users\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\conic_solvers\mosek_conif.py", line 105, in import_solver
    if hasattr(mosek.conetype, 'pexp') and ExpCone not in MOSEK.SUPPORTED_CONSTRAINTS:

AttributeError: module 'mosek' has no attribute 'conetype'

The second error is:

 File "C:\Users\Anaconda3\lib\site-packages\cvxpy\__init__.py", line 22, in <module>
    from cvxpy.problems.problem import Problem

  File "C:\Users\Anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 23, in <module>
    from cvxpy.reductions.solvers.solving_chain import construct_solving_chain

  File "C:\Users\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\solving_chain.py", line 4, in <module>
    from cvxpy.reductions import (Chain, ConeMatrixStuffing, EvalParams,

  File "C:\Users\Anaconda3\lib\site-packages\cvxpy\reductions\__init__.py", line 32, in <module>
    from cvxpy.reductions.solvers.solving_chain import SolvingChain

ImportError: cannot import name 'SolvingChain' from 'cvxpy.reductions.solvers.solving_chain' (C:\Users\huihu\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\solving_chain.py)

**Version**
 - OS: Win 10
 -Python version: 3.7
 - CVXPY Version: 1.0.29

I tried to uninstall it thoroughly and then installed it again, but it didn't work.

**Comment by akshayka** [comment]
The first error likely has to do with having an old version of MOSEK, or having a file or directory called mosek in your working directory.

The second error suggests we might have a cyclic import, which surprises me because our continuous integration tests are working, and it works for me locally. I'll take a look.

**Comment by HuiHu1** [comment]
Could you offer me remote help through TeamViewer if you are available? I uninstalled all optimization software on my computer, then installed it again, but it always has the same question.
________________________________

**Comment by akshayka** [comment]
I'm not available for teleconferencing, but we can talk through the issue here.

Try doing the following:

1. Check for a folder or file called mosek or mosek.py in your working directory. If such a folder exist, that will explain your first error. A solution would be to work in another directory, such as C:\projects, for example.

2. Try downgrading to CVXPY 1.0.28. Another user ran into a similar issue, and said that using 1.0.28 fixed the problem. See #985

**Comment by HuiHu1** [comment]
Ok, I will have a try and let you know the result. Thanks, Akshay!
________________________________

**Comment by akshayka** [comment]
@HuiHu1 : We just released a new version on PyPi, 1.0.31, that might fix the second error (the circular dependency). A third thing you could try is to upgrade CVXPY to 1.0.31 (if you're using pip: pip install --upgrade cvxpy).

**Comment by HuiHu1** [comment]
Ok, Akshay. Thanks!
________________________________

**Comment by HuiHu1** [comment]
Hi, Akshay:

 I changed the directory, and upgrade cvxpy (1.0.31), but it has the same question. The details are as follows:

runfile('C:/HUIHU/Research/Third Project/Version3/Fair_D2.py', wdir='C:/HUIHU/Research/Third Project/Version3')
Traceback (most recent call last):
​
  File "C:\HUIHU\Research\Third Project\Version3\Fair_D2.py", line 10, in <module>
    import cvxpy as cp
​
  File "C:\Users\huihu\Anaconda3\lib\site-packages\cvxpy\__init__.py", line 22, in <module>
    from cvxpy.problems.problem import Problem
​
  File "C:\Users\huihu\Anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 20, in <module>
    from cvxpy.reductions.chain import Chain
​
  File "C:\Users\huihu\Anaconda3\lib\site-packages\cvxpy\reductions\__init__.py", line 32, in <module>
    from cvxpy.reductions.solvers.solving_chain import SolvingChain
​
  File "C:\Users\huihu\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\solving_chain.py", line 10, in <module>
    from cvxpy.reductions.solvers import defines as slv_def
​
  File "C:\Users\huihu\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\defines.py", line 93, in <module>
    INSTALLED_SOLVERS = installed_solvers()
​
  File "C:\Users\huihu\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\defines.py", line 82, in installed_solvers
    if solver.is_installed():
​
  File "C:\Users\huihu\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\solver.py", line 70, in is_installed
    self.import_solver()
​
  File "C:\Users\huihu\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\conic_solvers\mosek_conif.py", line 105, in import_solver
    if hasattr(mosek.conetype, 'pexp') and ExpCone not in MOSEK.SUPPORTED_CONSTRAINTS:
​
AttributeError: module 'mosek' has no attribute 'conetype'

Best,
Hui


________________________________

**Comment by akshayka** [comment]
Okay, at least it seems like the second error is gone, so upgrading to 1.0.31 fixed that at least.

Take a look at issue #977 for guidance with the Mosek error.

**Comment by HuiHu1** [comment]
Cool! Akshay, you helped me solve this question perfectly! Thanks again!

Best,
Hui
________________________________

**Comment by akshayka** [comment]
Great!

**Comment by HuiHu1** [comment]
Hi, Akshay:
     I have another question about CVXPY package:
           Does this package include a solver for the following optimization problem:   -t=<f1-f2<=t where t>=0, f1 and f2 are convex functions like L2 norm? I tried DCP, DCCP solvers, both are failed.
My optimization codes are:
        t=cp.Variable(1)
        constraints = [t>=0,cp.sum_squares(d_i)==1,f1<=f2+t,f2<=t+f1]
        obj=cp.Minimize(t)
        prob =cp.Problem(obj,constraints)
        prob.solve(method='dccp',verbose=True)
But, it doesn't work. Thanks for your help!

Best,
Hui

________________________________

**Comment by rileyjmurray** [comment]
Constraints like ``|f1 - f2| <= t`` for nonlinear convex ``f1,f2`` are generally not tractable. The other issue with your example is ``cp.sum_squares(d_i) == 1``, which is not convex.

**Comment by HuiHu1** [comment]
So, I can't use this package to solve this optimization problem. Do you have other recommendations to solve it?
________________________________

**Comment by HuiHu1** [comment]
Hey, Akshay:
       Seemly, this idea works:
        t1=cp.Variable(1)
        t2=cp.Variable(1)
        constraints = [t1>=0,t2>=0,cp.sum_squares(d_i)==1,cp.abs(f1)<=t1,cp.abs(f2)<=t2]​
        obj=cp.Minimize(cp.abs(t1-t2))​
        prob =cp.Problem(obj,constraints)​
        prob.solve(method='dccp')

       DCCP can solve it.
________________________________

**Comment by HuiHu1** [comment]
Hi, Akshay:

   I submitted an issue about DCCP optimization at https://github.com/cvxgrp/dccp/issues/50. Could you help me?
   Thanks!

Best,
Hui
________________________________
